package org.dreambot.gamedata.items.equipment;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.dreambot.api.methods.container.impl.equipment.EquipmentSlot;
import org.dreambot.framework.requirements.Requirement;
import org.dreambot.framework.requirements.RequirementBuilder;
import org.dreambot.gamedata.combat.AttackBonus;
import org.dreambot.gamedata.combat.DefenceBonus;
import org.dreambot.gamedata.combat.SkillsBonus;
import org.dreambot.gamedata.items.GenericItemRef;
import org.dreambot.gamedata.items.WeaponItemRef;
import org.dreambot.gamedata.items.equipment.ammunition.AmmoType;

@Getter
@AllArgsConstructor
public enum AmmunitionSlotRef implements EquipmentRef {
    ADAMANT_ARROW_P_PLUS_PLUS(
            WeaponItemRef.ADAMANT_ARROW_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 31, 0, 0),
            0.0,
            WeaponItemRef.ADAMANT_ARROW_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.ARROW),
    ADAMANT_ARROW(
            WeaponItemRef.ADAMANT_ARROW,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 31, 0, 0),
            0.0,
            WeaponItemRef.ADAMANT_ARROW.getSimilarItems(),
            AmmoType.ARROW),
    ADAMANT_BOLTS_P_PLUS_PLUS(
            WeaponItemRef.ADAMANT_BOLTS_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 100, 0, 0),
            0.0,
            WeaponItemRef.ADAMANT_BOLTS_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.BOLT),
    ADAMANT_BOLTS(
            WeaponItemRef.ADAMANT_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 100, 0, 0),
            0.0,
            WeaponItemRef.ADAMANT_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    ADAMANT_BRUTAL(
            WeaponItemRef.ADAMANT_BRUTAL,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 45, 0, 0),
            0.0,
            WeaponItemRef.ADAMANT_BRUTAL.getSimilarItems(),
            AmmoType.BRUTAL),
//    ADAMANT_FIRE_ARROW_UNLIT(
//            WeaponItemRef.ADAMANT_FIRE_ARROW_UNLIT,
//            true,
//            new AttackBonus(0, 0, 0, 0, 0),
//            new DefenceBonus(0, 0, 0, 0, 0),
//            new SkillsBonus(0, 31, 0, 0),
//            0.0,
//            WeaponItemRef.ADAMANT_FIRE_ARROW_UNLIT.getSimilarItems(),
//            AmmoType.ARROW),
    ADAMANT_JAVELIN_P_PLUS_PLUS(
            WeaponItemRef.ADAMANT_JAVELIN_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 102, 0, 0),
            0.0,
            WeaponItemRef.ADAMANT_JAVELIN_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.JAVELIN),
    ADAMANT_JAVELIN(
            WeaponItemRef.ADAMANT_JAVELIN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 102, 0, 0),
            0.0,
            WeaponItemRef.ADAMANT_JAVELIN.getSimilarItems(),
            AmmoType.JAVELIN),
    AMETHYST_ARROW_P_PLUS_PLUS(
            WeaponItemRef.AMETHYST_ARROW_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 55, 0, 0),
            0.0,
            WeaponItemRef.AMETHYST_ARROW_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.ARROW),
    AMETHYST_ARROW(
            WeaponItemRef.AMETHYST_ARROW,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 55, 0, 0),
            0.0,
            WeaponItemRef.AMETHYST_ARROW.getSimilarItems(),
            AmmoType.ARROW),
    AMETHYST_BROAD_BOLTS(
            WeaponItemRef.AMETHYST_BROAD_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 115, 0, 0),
            0.0,
            WeaponItemRef.AMETHYST_BROAD_BOLTS.getSimilarItems(),
            AmmoType.BROAD_BOLT),
//    AMETHYST_FIRE_ARROW_UNLIT(
//            WeaponItemRef.AMETHYST_FIRE_ARROW_UNLIT,
//            true,
//            new AttackBonus(0, 0, 0, 0, 0),
//            new DefenceBonus(0, 0, 0, 0, 0),
//            new SkillsBonus(0, 55, 0, 0),
//            0.0,
//            WeaponItemRef.AMETHYST_FIRE_ARROW_UNLIT.getSimilarItems(),
//            AmmoType.ARROW),
    AMETHYST_JAVELIN_P_PLUS_PLUS(
            WeaponItemRef.AMETHYST_JAVELIN_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 135, 0, 0),
            0.0,
            WeaponItemRef.AMETHYST_JAVELIN_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.JAVELIN),
    AMETHYST_JAVELIN(
            WeaponItemRef.AMETHYST_JAVELIN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 135, 0, 0),
            0.0,
            WeaponItemRef.AMETHYST_JAVELIN.getSimilarItems(),
            AmmoType.JAVELIN),
    ANCIENT_BLESSING(
            WeaponItemRef.ANCIENT_BLESSING,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 1),
            0.51,
            WeaponItemRef.ANCIENT_BLESSING.getSimilarItems(),
            null),
    ATLATL_DART(
            WeaponItemRef.ATLATL_DART,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.0,
            WeaponItemRef.ATLATL_DART.getSimilarItems(),
            AmmoType.ATLATL_DART),
    BARBED_ARROW(
            WeaponItemRef.BARBED_ARROW,
            true,
            new AttackBonus(0, 0, 0, 0, 46),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 125, 0, 0),
            0.0,
            WeaponItemRef.BARBED_ARROW.getSimilarItems(),
            AmmoType.ARROW),
    BARBED_BOLTS(
            WeaponItemRef.BARBED_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 12, 0, 0),
            0.0,
            WeaponItemRef.BARBED_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    BLACK_BRUTAL(
            WeaponItemRef.BLACK_BRUTAL,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 22, 0, 0),
            0.0,
            WeaponItemRef.BLACK_BRUTAL.getSimilarItems(),
            AmmoType.BRUTAL),
    BLUNT_ARROW(
            WeaponItemRef.BLUNT_ARROW,
            true,
            new AttackBonus(0, 0, 0, 0, 46),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 125, 0, 0),
            0.0,
            WeaponItemRef.BLUNT_ARROW.getSimilarItems(),
            AmmoType.ARROW),
    BLURITE_BOLTS_P_PLUS_PLUS(
            WeaponItemRef.BLURITE_BOLTS_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 28, 0, 0),
            0.0,
            WeaponItemRef.BLURITE_BOLTS_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.BOLT),
    BLURITE_BOLTS(
            WeaponItemRef.BLURITE_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 28, 0, 0),
            0.0,
            WeaponItemRef.BLURITE_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    BOLT_RACK(
            WeaponItemRef.BOLT_RACK,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 55, 0, 0),
            0.0,
            WeaponItemRef.BOLT_RACK.getSimilarItems(),
            AmmoType.BOLT_RACK),
    BONE_BOLTS(
            WeaponItemRef.BONE_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 49, 0, 0),
            0.0,
            WeaponItemRef.BONE_BOLTS.getSimilarItems(),
            AmmoType.BONE),
    BROAD_ARROWS(
            WeaponItemRef.BROAD_ARROWS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 28, 0, 0),
            0.0,
            WeaponItemRef.BROAD_ARROWS.getSimilarItems(),
            AmmoType.BROAD_ARROW),
    BROAD_BOLTS(
            WeaponItemRef.BROAD_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 100, 0, 0),
            0.0,
            WeaponItemRef.BROAD_BOLTS.getSimilarItems(),
            AmmoType.BROAD_BOLT),
    BRONZE_ARROW_P_PLUS_PLUS(
            WeaponItemRef.BRONZE_ARROW_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 7, 0, 0),
            0.0,
            WeaponItemRef.BRONZE_ARROW_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.ARROW),
    BRONZE_ARROW(
            WeaponItemRef.BRONZE_ARROW,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 7, 0, 0),
            0.0,
            WeaponItemRef.BRONZE_ARROW.getSimilarItems(),
            AmmoType.ARROW),
    BRONZE_BOLTS_P_PLUS_PLUS(
            WeaponItemRef.BRONZE_BOLTS_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 10, 0, 0),
            0.0,
            WeaponItemRef.BRONZE_BOLTS_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.BOLT),
    BRONZE_BOLTS(
            WeaponItemRef.BRONZE_BOLTS,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 10, 0, 0),
            0.0,
            WeaponItemRef.BRONZE_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    BRONZE_BRUTAL(
            WeaponItemRef.BRONZE_BRUTAL,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 11, 0, 0),
            0.0,
            WeaponItemRef.BRONZE_BRUTAL.getSimilarItems(),
            AmmoType.BRUTAL),
//    BRONZE_FIRE_ARROW_UNLIT(
//            WeaponItemRef.BRONZE_FIRE_ARROW_UNLIT,
//            true,
//            new AttackBonus(0, 0, 0, 0, 0),
//            new DefenceBonus(0, 0, 0, 0, 0),
//            new SkillsBonus(0, 7, 0, 0),
//            0.0,
//            WeaponItemRef.BRONZE_FIRE_ARROW_UNLIT.getSimilarItems(),
//            AmmoType.ARROW),
    BRONZE_JAVELIN_P_PLUS_PLUS(
            WeaponItemRef.BRONZE_JAVELIN_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 25, 0, 0),
            0.0,
            WeaponItemRef.BRONZE_JAVELIN_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.JAVELIN),
    BRONZE_JAVELIN(
            WeaponItemRef.BRONZE_JAVELIN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 25, 0, 0),
            0.0,
            WeaponItemRef.BRONZE_JAVELIN.getSimilarItems(),
            AmmoType.JAVELIN),
    BULLET_ARROW(
            WeaponItemRef.BULLET_ARROW,
            true,
            new AttackBonus(0, 0, 0, 0, 46),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 125, 0, 0),
            0.0,
            WeaponItemRef.BULLET_ARROW.getSimilarItems(),
            AmmoType.ARROW),
    CASTLE_WARS_ARROW(
            WeaponItemRef.CASTLE_WARS_ARROW,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 60, 0, 0),
            0.016,
            WeaponItemRef.CASTLE_WARS_ARROW.getSimilarItems(),
            AmmoType.ARROW),
    CASTLE_WARS_BOLTS(
            WeaponItemRef.CASTLE_WARS_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.018,
            WeaponItemRef.CASTLE_WARS_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    DIAMOND_BOLTS(
            WeaponItemRef.DIAMOND_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 105, 0, 0),
            0.0,
            WeaponItemRef.DIAMOND_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    DIAMOND_BOLTS_E(
            WeaponItemRef.DIAMOND_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 105, 0, 0),
            0.0,
            WeaponItemRef.DIAMOND_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    DIAMOND_DRAGON_BOLTS(
            WeaponItemRef.DIAMOND_DRAGON_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.DIAMOND_DRAGON_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    DIAMOND_DRAGON_BOLTS_E(
            WeaponItemRef.DIAMOND_DRAGON_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.DIAMOND_DRAGON_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    DRAGON_ARROW_P_PLUS_PLUS(
            WeaponItemRef.DRAGON_ARROW_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 60, 0, 0),
            0.0,
            WeaponItemRef.DRAGON_ARROW_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.ARROW),
    DRAGON_ARROW(
            WeaponItemRef.DRAGON_ARROW,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 60, 0, 0),
            0.0,
            WeaponItemRef.DRAGON_ARROW.getSimilarItems(),
            AmmoType.ARROW),
    DRAGON_BOLTS_P_PLUS_PLUS(
            WeaponItemRef.DRAGON_BOLTS_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.DRAGON_BOLTS_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.BOLT),
    DRAGON_BOLTS(
            WeaponItemRef.DRAGON_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.DRAGON_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
//    DRAGON_FIRE_ARROW_UNLIT(
//            WeaponItemRef.DRAGON_FIRE_ARROW_UNLIT,
//            true,
//            new AttackBonus(0, 0, 0, 0, 0),
//            new DefenceBonus(0, 0, 0, 0, 0),
//            new SkillsBonus(0, 60, 0, 0),
//            0.0,
//            WeaponItemRef.DRAGON_FIRE_ARROW_UNLIT.getSimilarItems(),
//            AmmoType.ARROW),
    DRAGON_JAVELIN_P_PLUS_PLUS(
            WeaponItemRef.DRAGON_JAVELIN_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 150, 0, 0),
            0.0,
            WeaponItemRef.DRAGON_JAVELIN_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.JAVELIN),
    DRAGON_JAVELIN(
            WeaponItemRef.DRAGON_JAVELIN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 150, 0, 0),
            0.0,
            WeaponItemRef.DRAGON_JAVELIN.getSimilarItems(),
            AmmoType.JAVELIN),
    DRAGONSTONE_BOLTS(
            WeaponItemRef.DRAGONSTONE_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 117, 0, 0),
            0.0,
            WeaponItemRef.DRAGONSTONE_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    DRAGONSTONE_BOLTS_E(
            WeaponItemRef.DRAGONSTONE_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 117, 0, 0),
            0.0,
            WeaponItemRef.DRAGONSTONE_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    DRAGONSTONE_DRAGON_BOLTS(
            WeaponItemRef.DRAGONSTONE_DRAGON_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.DRAGONSTONE_DRAGON_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    DRAGONSTONE_DRAGON_BOLTS_E(
            WeaponItemRef.DRAGONSTONE_DRAGON_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.DRAGONSTONE_DRAGON_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    EMERALD_BOLTS(
            WeaponItemRef.EMERALD_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 85, 0, 0),
            0.0,
            WeaponItemRef.EMERALD_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    EMERALD_BOLTS_E(
            WeaponItemRef.EMERALD_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 85, 0, 0),
            0.0,
            WeaponItemRef.EMERALD_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    EMERALD_DRAGON_BOLTS(
            WeaponItemRef.EMERALD_DRAGON_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.EMERALD_DRAGON_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    EMERALD_DRAGON_BOLTS_E(
            WeaponItemRef.EMERALD_DRAGON_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.EMERALD_DRAGON_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    FIELD_ARROW(
            WeaponItemRef.FIELD_ARROW,
            true,
            new AttackBonus(0, 0, 0, 0, 46),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 125, 0, 0),
            0.0,
            WeaponItemRef.FIELD_ARROW.getSimilarItems(),
            AmmoType.ARROW),
//    GHOMMALS_LUCKY_PENNY(
//            WeaponItemRef.GHOMMALS_LUCKY_PENNY,
//            true,
//            new AttackBonus(0, 0, 0, 0, 0),
//            new DefenceBonus(0, 0, 0, 0, 0),
//            new SkillsBonus(0, 0, 0, 0),
//            0.05,
//            WeaponItemRef.GHOMMALS_LUCKY_PENNY.getSimilarItems()),
    GUAM_TAR(
            WeaponItemRef.GUAM_TAR,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 16, 0, 0),
            0.0,
            WeaponItemRef.GUAM_TAR.getSimilarItems(),
            AmmoType.TAR),
    HARRALANDER_TAR(
            WeaponItemRef.HARRALANDER_TAR,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 49, 0, 0),
            0.0,
            WeaponItemRef.HARRALANDER_TAR.getSimilarItems(),
            AmmoType.TAR),
    HOLY_BLESSING(
            WeaponItemRef.HOLY_BLESSING,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 1),
            0.51,
            WeaponItemRef.HOLY_BLESSING.getSimilarItems(),
            null),
    HONOURABLE_BLESSING(
            WeaponItemRef.HONOURABLE_BLESSING,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 1),
            0.51,
            WeaponItemRef.HONOURABLE_BLESSING.getSimilarItems(),
            null),
//    ICE_ARROWS(
//            WeaponItemRef.ICE_ARROWS,
//            true,
//            new AttackBonus(0, 0, 0, 0, 0),
//            new DefenceBonus(0, 0, 0, 0, 0),
//            new SkillsBonus(0, 16, 0, 0),
//            0.0,
//            WeaponItemRef.ICE_ARROWS.getSimilarItems(),
//            AmmoType.ARROW),
    IRIT_TAR(
            WeaponItemRef.IRIT_TAR,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 60, 0, 0),
            0.0,
            WeaponItemRef.IRIT_TAR.getSimilarItems(),
            AmmoType.TAR),
    IRON_ARROW_P_PLUS_PLUS(
            WeaponItemRef.IRON_ARROW_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 10, 0, 0),
            0.0,
            WeaponItemRef.IRON_ARROW_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.ARROW),
    IRON_ARROW(
            WeaponItemRef.IRON_ARROW,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 10, 0, 0),
            0.0,
            WeaponItemRef.IRON_ARROW.getSimilarItems(),
            AmmoType.ARROW),
    IRON_BOLTS_P_PLUS_PLUS(
            WeaponItemRef.IRON_BOLTS_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 46, 0, 0),
            0.0,
            WeaponItemRef.IRON_BOLTS_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.BOLT),
    IRON_BOLTS(
            WeaponItemRef.IRON_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 46, 0, 0),
            0.0,
            WeaponItemRef.IRON_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    IRON_BRUTAL(
            WeaponItemRef.IRON_BRUTAL,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 13, 0, 0),
            0.0,
            WeaponItemRef.IRON_BRUTAL.getSimilarItems(),
            AmmoType.BRUTAL),
//    IRON_FIRE_ARROW_UNLIT(
//            WeaponItemRef.IRON_FIRE_ARROW_UNLIT,
//            true,
//            new AttackBonus(0, 0, 0, 0, 0),
//            new DefenceBonus(0, 0, 0, 0, 0),
//            new SkillsBonus(0, 10, 0, 0),
//            0.0,
//            WeaponItemRef.IRON_FIRE_ARROW_UNLIT.getSimilarItems(),
//            AmmoType.ARROW),
    IRON_JAVELIN_P_PLUS_PLUS(
            WeaponItemRef.IRON_JAVELIN_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 42, 0, 0),
            0.0,
            WeaponItemRef.IRON_JAVELIN_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.JAVELIN),
    IRON_JAVELIN(
            WeaponItemRef.IRON_JAVELIN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 42, 0, 0),
            0.0,
            WeaponItemRef.IRON_JAVELIN.getSimilarItems(),
            AmmoType.JAVELIN),
    JADE_BOLTS(
            WeaponItemRef.JADE_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 30, 0, 0),
            0.0,
            WeaponItemRef.JADE_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    JADE_BOLTS_E(
            WeaponItemRef.JADE_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 30, 0, 0),
            0.0,
            WeaponItemRef.JADE_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    JADE_DRAGON_BOLTS(
            WeaponItemRef.JADE_DRAGON_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.JADE_DRAGON_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    JADE_DRAGON_BOLTS_E(
            WeaponItemRef.JADE_DRAGON_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.JADE_DRAGON_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    KEBBIT_BOLTS(
            WeaponItemRef.KEBBIT_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 28, 0, 0),
            0.0,
            WeaponItemRef.KEBBIT_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    LONG_KEBBIT_BOLTS(
            WeaponItemRef.LONG_KEBBIT_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 38, 0, 0),
            0.0,
            WeaponItemRef.LONG_KEBBIT_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    MARRENTILL_TAR(
            WeaponItemRef.MARRENTILL_TAR,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 22, 0, 0),
            0.0,
            WeaponItemRef.MARRENTILL_TAR.getSimilarItems(),
            AmmoType.TAR),
    MITHRIL_ARROW_P_PLUS_PLUS(
            WeaponItemRef.MITHRIL_ARROW_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 22, 0, 0),
            0.0,
            WeaponItemRef.MITHRIL_ARROW_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.ARROW),
    MITHRIL_ARROW(
            WeaponItemRef.MITHRIL_ARROW,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 22, 0, 0),
            0.0,
            WeaponItemRef.MITHRIL_ARROW.getSimilarItems(),
            AmmoType.ARROW),
    MITHRIL_BOLTS_P_PLUS_PLUS(
            WeaponItemRef.MITHRIL_BOLTS_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 82, 0, 0),
            0.0,
            WeaponItemRef.MITHRIL_BOLTS_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.BOLT),
    MITHRIL_BOLTS(
            WeaponItemRef.MITHRIL_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 82, 0, 0),
            0.0,
            WeaponItemRef.MITHRIL_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    MITHRIL_BRUTAL(
            WeaponItemRef.MITHRIL_BRUTAL,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 34, 0, 0),
            0.0,
            WeaponItemRef.MITHRIL_BRUTAL.getSimilarItems(),
            AmmoType.BRUTAL),
//    MITHRIL_FIRE_ARROW_UNLIT(
//            WeaponItemRef.MITHRIL_FIRE_ARROW_UNLIT,
//            true,
//            new AttackBonus(0, 0, 0, 0, 0),
//            new DefenceBonus(0, 0, 0, 0, 0),
//            new SkillsBonus(0, 22, 0, 0),
//            0.0,
//            WeaponItemRef.MITHRIL_FIRE_ARROW_UNLIT.getSimilarItems(),
//            AmmoType.ARROW),
    MITHRIL_JAVELIN_P_PLUS_PLUS(
            WeaponItemRef.MITHRIL_JAVELIN_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 85, 0, 0),
            0.0,
            WeaponItemRef.MITHRIL_JAVELIN_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.JAVELIN),
    MITHRIL_JAVELIN(
            WeaponItemRef.MITHRIL_JAVELIN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 85, 0, 0),
            0.0,
            WeaponItemRef.MITHRIL_JAVELIN.getSimilarItems(),
            AmmoType.JAVELIN),
    MOONLIGHT_ANTLER_BOLTS(
            WeaponItemRef.MOONLIGHT_ANTLER_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 60, 0, 0),
            0.0,
            WeaponItemRef.MOONLIGHT_ANTLER_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    OGRE_ARROW(
            WeaponItemRef.OGRE_ARROW,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 22, 0, 0),
            0.0,
            WeaponItemRef.OGRE_ARROW.getSimilarItems(),
            AmmoType.OGRE_ARROW),
    ONYX_BOLTS(
            WeaponItemRef.ONYX_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 120, 0, 0),
            0.0,
            WeaponItemRef.ONYX_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    ONYX_BOLTS_E(
            WeaponItemRef.ONYX_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 120, 0, 0),
            0.0,
            WeaponItemRef.ONYX_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    ONYX_DRAGON_BOLTS(
            WeaponItemRef.ONYX_DRAGON_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.ONYX_DRAGON_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    ONYX_DRAGON_BOLTS_E(
            WeaponItemRef.ONYX_DRAGON_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.ONYX_DRAGON_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    OPAL_BOLTS(
            WeaponItemRef.OPAL_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 14, 0, 0),
            0.0,
            WeaponItemRef.OPAL_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    OPAL_BOLTS_E(
            WeaponItemRef.OPAL_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 14, 0, 0),
            0.0,
            WeaponItemRef.OPAL_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    OPAL_DRAGON_BOLTS(
            WeaponItemRef.OPAL_DRAGON_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.OPAL_DRAGON_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    OPAL_DRAGON_BOLTS_E(
            WeaponItemRef.OPAL_DRAGON_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.OPAL_DRAGON_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    PEACEFUL_BLESSING(
            WeaponItemRef.PEACEFUL_BLESSING,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 1),
            0.51,
            WeaponItemRef.PEACEFUL_BLESSING.getSimilarItems(),
            null),
    PEARL_BOLTS(
            WeaponItemRef.PEARL_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 48, 0, 0),
            0.0,
            WeaponItemRef.PEARL_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    PEARL_BOLTS_E(
            WeaponItemRef.PEARL_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 48, 0, 0),
            0.0,
            WeaponItemRef.PEARL_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    PEARL_DRAGON_BOLTS(
            WeaponItemRef.PEARL_DRAGON_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.PEARL_DRAGON_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    PEARL_DRAGON_BOLTS_E(
            WeaponItemRef.PEARL_DRAGON_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.PEARL_DRAGON_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    RADAS_BLESSING_1(
            WeaponItemRef.RADAS_BLESSING_1,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            WeaponItemRef.RADAS_BLESSING_1.getSimilarItems(),
            null),
    RADAS_BLESSING_2(
            WeaponItemRef.RADAS_BLESSING_2,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 1),
            0.453,
            WeaponItemRef.RADAS_BLESSING_2.getSimilarItems(),
            null),
    RADAS_BLESSING_3(
            WeaponItemRef.RADAS_BLESSING_3,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 1),
            0.453,
            WeaponItemRef.RADAS_BLESSING_3.getSimilarItems(),
            null),
    RADAS_BLESSING_4(
            WeaponItemRef.RADAS_BLESSING_4,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 2),
            0.453,
            WeaponItemRef.RADAS_BLESSING_4.getSimilarItems(),
            null),
    RUBY_BOLTS(
            WeaponItemRef.RUBY_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 103, 0, 0),
            0.0,
            WeaponItemRef.RUBY_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    RUBY_BOLTS_E(
            WeaponItemRef.RUBY_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 103, 0, 0),
            0.0,
            WeaponItemRef.RUBY_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    RUBY_DRAGON_BOLTS(
            WeaponItemRef.RUBY_DRAGON_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.RUBY_DRAGON_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    RUBY_DRAGON_BOLTS_E(
            WeaponItemRef.RUBY_DRAGON_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.RUBY_DRAGON_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    RUNE_ARROW_P_PLUS_PLUS(
            WeaponItemRef.RUNE_ARROW_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 49, 0, 0),
            0.0,
            WeaponItemRef.RUNE_ARROW_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.ARROW),
    RUNE_ARROW(
            WeaponItemRef.RUNE_ARROW,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 49, 0, 0),
            0.0,
            WeaponItemRef.RUNE_ARROW.getSimilarItems(),
            AmmoType.ARROW),
    RUNE_BRUTAL(
            WeaponItemRef.RUNE_BRUTAL,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 60, 0, 0),
            0.0,
            WeaponItemRef.RUNE_BRUTAL.getSimilarItems(),
            AmmoType.BRUTAL),
//    RUNE_FIRE_ARROW_UNLIT(
//            WeaponItemRef.RUNE_FIRE_ARROW_UNLIT,
//            true,
//            new AttackBonus(0, 0, 0, 0, 0),
//            new DefenceBonus(0, 0, 0, 0, 0),
//            new SkillsBonus(0, 49, 0, 0),
//            0.0,
//            WeaponItemRef.RUNE_FIRE_ARROW_UNLIT.getSimilarItems(),
//            AmmoType.ARROW),
    RUNE_JAVELIN_P_PLUS_PLUS(
            WeaponItemRef.RUNE_JAVELIN_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 124, 0, 0),
            0.0,
            WeaponItemRef.RUNE_JAVELIN_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.JAVELIN),
    RUNE_JAVELIN(
            WeaponItemRef.RUNE_JAVELIN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 124, 0, 0),
            0.0,
            WeaponItemRef.RUNE_JAVELIN.getSimilarItems(),
            AmmoType.JAVELIN),
    RUNITE_BOLTS_P_PLUS_PLUS(
            WeaponItemRef.RUNITE_BOLTS_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 115, 0, 0),
            0.0,
            WeaponItemRef.RUNITE_BOLTS_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.BOLT),
    RUNE_BOLTS(
            WeaponItemRef.RUNE_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 115, 0, 0),
            0.0,
            WeaponItemRef.RUNE_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    SAPPHIRE_BOLTS(
            WeaponItemRef.SAPPHIRE_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 83, 0, 0),
            0.0,
            WeaponItemRef.SAPPHIRE_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    SAPPHIRE_BOLTS_E(
            WeaponItemRef.SAPPHIRE_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 83, 0, 0),
            0.0,
            WeaponItemRef.SAPPHIRE_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    SAPPHIRE_DRAGON_BOLTS(
            WeaponItemRef.SAPPHIRE_DRAGON_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.SAPPHIRE_DRAGON_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    SAPPHIRE_DRAGON_BOLTS_E(
            WeaponItemRef.SAPPHIRE_DRAGON_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.SAPPHIRE_DRAGON_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    SILVER_BOLTS_P_PLUS_PLUS(
            WeaponItemRef.SILVER_BOLTS_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 36, 0, 0),
            0.0,
            WeaponItemRef.SILVER_BOLTS_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.BOLT),
    SILVER_BOLTS(
            WeaponItemRef.SILVER_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 36, 0, 0),
            0.0,
            WeaponItemRef.SILVER_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    STEEL_ARROW_P_PLUS_PLUS(
            WeaponItemRef.STEEL_ARROW_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 16, 0, 0),
            0.0,
            WeaponItemRef.STEEL_ARROW_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.ARROW),
    STEEL_ARROW(
            WeaponItemRef.STEEL_ARROW,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 16, 0, 0),
            0.0,
            WeaponItemRef.STEEL_ARROW.getSimilarItems(),
            AmmoType.ARROW),
    STEEL_BOLTS_P_PLUS_PLUS(
            WeaponItemRef.STEEL_BOLTS_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 64, 0, 0),
            0.0,
            WeaponItemRef.STEEL_BOLTS_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.BOLT),
    STEEL_BOLTS(
            WeaponItemRef.STEEL_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 64, 0, 0),
            0.0,
            WeaponItemRef.STEEL_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    STEEL_BRUTAL(
            WeaponItemRef.STEEL_BRUTAL,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 19, 0, 0),
            0.0,
            WeaponItemRef.STEEL_BRUTAL.getSimilarItems(),
            AmmoType.BRUTAL),
//    STEEL_FIRE_ARROW_UNLIT(
//            WeaponItemRef.STEEL_FIRE_ARROW_UNLIT,
//            true,
//            new AttackBonus(0, 0, 0, 0, 0),
//            new DefenceBonus(0, 0, 0, 0, 0),
//            new SkillsBonus(0, 16, 0, 0),
//            0.0,
//            WeaponItemRef.STEEL_FIRE_ARROW_UNLIT.getSimilarItems(),
//            AmmoType.ARROW),
    STEEL_JAVELIN_P_PLUS_PLUS(
            WeaponItemRef.STEEL_JAVELIN_P_PLUS_PLUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 64, 0, 0),
            0.0,
            WeaponItemRef.STEEL_JAVELIN_P_PLUS_PLUS.getSimilarItems(),
            AmmoType.JAVELIN),
    STEEL_JAVELIN(
            WeaponItemRef.STEEL_JAVELIN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 64, 0, 0),
            0.0,
            WeaponItemRef.STEEL_JAVELIN.getSimilarItems(),
            AmmoType.JAVELIN),
    SUNLIGHT_ANTLER_BOLTS(
            WeaponItemRef.SUNLIGHT_ANTLER_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 55, 0, 0),
            0.0,
            WeaponItemRef.SUNLIGHT_ANTLER_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    TARROMIN_TAR(
            WeaponItemRef.TARROMIN_TAR,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 31, 0, 0),
            0.0,
            WeaponItemRef.TARROMIN_TAR.getSimilarItems(),
            AmmoType.TAR),
    TOPAZ_BOLTS(
            WeaponItemRef.TOPAZ_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 66, 0, 0),
            0.0,
            WeaponItemRef.TOPAZ_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    TOPAZ_BOLTS_E(
            WeaponItemRef.TOPAZ_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 66, 0, 0),
            0.0,
            WeaponItemRef.TOPAZ_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    TOPAZ_DRAGON_BOLTS(
            WeaponItemRef.TOPAZ_DRAGON_BOLTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.TOPAZ_DRAGON_BOLTS.getSimilarItems(),
            AmmoType.BOLT),
    TOPAZ_DRAGON_BOLTS_E(
            WeaponItemRef.TOPAZ_DRAGON_BOLTS_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 122, 0, 0),
            0.0,
            WeaponItemRef.TOPAZ_DRAGON_BOLTS_E.getSimilarItems(),
            AmmoType.BOLT),
    TRAINING_ARROWS(
            WeaponItemRef.TRAINING_ARROWS,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 7, 0, 0),
            0.0,
            WeaponItemRef.TRAINING_ARROWS.getSimilarItems(),
            AmmoType.TRAINING_ARROW),
    UNHOLY_BLESSING(
            WeaponItemRef.UNHOLY_BLESSING,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 1),
            0.51,
            WeaponItemRef.UNHOLY_BLESSING.getSimilarItems(),
            null),
    WAR_BLESSING(
            WeaponItemRef.WAR_BLESSING,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 1),
            0.51,
            WeaponItemRef.WAR_BLESSING.getSimilarItems(),
            null);

    private final EquipmentSlot slot = EquipmentSlot.ARROWS;
    private final GenericItemRef itemRef;
    private final boolean members;
    private final AttackBonus attackBonus;
    private final DefenceBonus defenceBonus;
    private final SkillsBonus skillsBonus;
    private final double weight;
    private final GenericItemRef[] similarItems;
    private final Requirement requirement;
    private final AmmoType ammoType;

    AmmunitionSlotRef(
            GenericItemRef itemRef,
            boolean members,
            AttackBonus attackBonus,
            DefenceBonus defenceBonus,
            SkillsBonus skillsBonus,
            double weight,
            GenericItemRef[] similarItems,
            AmmoType ammoType) {
        this(
                itemRef,
                members,
                attackBonus,
                defenceBonus,
                skillsBonus,
                weight,
                similarItems,
                new RequirementBuilder().build(),
                ammoType);
    }
}
