package org.dreambot.gamedata.items.equipment;

import static org.dreambot.api.methods.skills.Skill.ATTACK;
import static org.dreambot.api.methods.skills.Skill.DEFENCE;
import static org.dreambot.api.methods.skills.Skill.HITPOINTS;
import static org.dreambot.api.methods.skills.Skill.MAGIC;
import static org.dreambot.api.methods.skills.Skill.PRAYER;
import static org.dreambot.api.methods.skills.Skill.RANGED;
import static org.dreambot.api.methods.skills.Skill.STRENGTH;
import static org.dreambot.framework.requirements.LocalRequirementHelper.*;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.dreambot.api.methods.container.impl.equipment.EquipmentSlot;
import org.dreambot.api.methods.quest.book.MiniQuest;
import org.dreambot.api.methods.quest.book.PaidQuest;
import org.dreambot.framework.requirements.LocalRequirement;
import org.dreambot.gamedata.combat.AttackBonus;
import org.dreambot.gamedata.combat.DefenceBonus;
import org.dreambot.gamedata.combat.SkillsBonus;
import org.dreambot.gamedata.items.ArmourItemRef;
import org.dreambot.gamedata.items.GenericItemRef;

@Getter
@AllArgsConstructor
public enum HandsSlotRefs implements EquipmentRefs {
    _3RD_AGE_VAMBRACES(
            ArmourItemRef._3RD_AGE_VAMBRACES,
            true,
            new AttackBonus(0, 0, 0, -10, 11),
            new DefenceBonus(6, 5, 7, 9, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            0,
            ArmourItemRef._3RD_AGE_VAMBRACES.getSimilarItems(),
            levels(RANGED, 65, DEFENCE, 45)),
    ABYSSAL_BRACELET(
            ArmourItemRef.ABYSSAL_BRACELET,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.25,
            0,
            ArmourItemRef.ABYSSAL_BRACELET.getSimilarItems()),
    ADAMANT_GLOVES(
            ArmourItemRef.ADAMANT_GLOVES,
            true,
            new AttackBonus(7, 7, 7, 4, 7),
            new DefenceBonus(7, 7, 7, 4, 7),
            new SkillsBonus(7, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.ADAMANT_GLOVES.getSimilarItems()),
    ANCIENT_BRACERS(
            ArmourItemRef.ANCIENT_BRACERS,
            true,
            new AttackBonus(0, 0, 0, -10, 11),
            new DefenceBonus(6, 5, 7, 8, 0),
            new SkillsBonus(0, 0, 0, 1),
            1.0,
            0,
            ArmourItemRef.ANCIENT_BRACERS.getSimilarItems(),
            levels(RANGED, 70)),
    ANCIENT_CEREMONIAL_GLOVES(
            ArmourItemRef.ANCIENT_CEREMONIAL_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 1),
            0.2,
            0,
            ArmourItemRef.ANCIENT_CEREMONIAL_GLOVES.getSimilarItems()),
    ARMADYL_BRACERS(
            ArmourItemRef.ARMADYL_BRACERS,
            true,
            new AttackBonus(0, 0, 0, -10, 11),
            new DefenceBonus(6, 5, 7, 8, 0),
            new SkillsBonus(0, 0, 0, 1),
            1.0,
            0,
            ArmourItemRef.ARMADYL_BRACERS.getSimilarItems(),
            levels(RANGED, 70)),
    BANDOS_BRACERS(
            ArmourItemRef.BANDOS_BRACERS,
            true,
            new AttackBonus(0, 0, 0, -10, 11),
            new DefenceBonus(6, 5, 7, 8, 0),
            new SkillsBonus(0, 0, 0, 1),
            1.0,
            0,
            ArmourItemRef.BANDOS_BRACERS.getSimilarItems(),
            levels(RANGED, 70)),
    BARROWS_GLOVES(
            ArmourItemRef.BARROWS_GLOVES,
            true,
            new AttackBonus(12, 12, 12, 6, 12),
            new DefenceBonus(12, 12, 12, 6, 12),
            new SkillsBonus(12, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.BARROWS_GLOVES.getSimilarItems(),
            finished(PaidQuest.RECIPE_FOR_DISASTER, DEFENCE, 35)),
    BLACK_DHIDE_VAMBRACES(
            ArmourItemRef.BLACK_DHIDE_VAMBRACES,
            true,
            new AttackBonus(0, 0, 0, -10, 11),
            new DefenceBonus(4, 5, 5, 8, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.283,
            0,
            ArmourItemRef.BLACK_DHIDE_VAMBRACES.getSimilarItems(),
            levels(RANGED, 70)),
    BLACK_GAUNTLETS(
            ArmourItemRef.BLACK_GAUNTLETS,
            true,
            new AttackBonus(5, 5, 5, 3, 5),
            new DefenceBonus(5, 5, 5, 3, 5),
            new SkillsBonus(5, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.BLACK_GAUNTLETS.getSimilarItems()),
    BLACK_SPIKY_VAMBRACES(
            ArmourItemRef.BLACK_SPIKY_VAMBRACES,
            true,
            new AttackBonus(0, 0, 0, -10, 11),
            new DefenceBonus(6, 5, 7, 8, 0),
            new SkillsBonus(2, 0, 0, 0),
            0.283,
            0,
            ArmourItemRef.BLACK_SPIKY_VAMBRACES.getSimilarItems()),
    BLOOD_BARK_GLOVES(
            ArmourItemRef.BLOOD_BARK_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 4, 0),
            new DefenceBonus(5, 4, 6, 5, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            0,
            ArmourItemRef.BLOOD_BARK_GLOVES.getSimilarItems()),
    BLUE_DHIDE_VAMBRACES(
            ArmourItemRef.BLUE_DHIDE_VAMBRACES,
            true,
            new AttackBonus(0, 0, 0, -10, 9),
            new DefenceBonus(2, 3, 3, 4, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.283,
            0,
            ArmourItemRef.BLUE_DHIDE_VAMBRACES.getSimilarItems(),
            levels(RANGED, 50)),
    BLUE_SPIKY_VAMBRACES(
            ArmourItemRef.BLUE_SPIKY_VAMBRACES,
            true,
            new AttackBonus(0, 0, 0, -10, 9),
            new DefenceBonus(4, 3, 5, 4, 0),
            new SkillsBonus(2, 0, 0, 0),
            0.283,
            0,
            ArmourItemRef.BLUE_SPIKY_VAMBRACES.getSimilarItems()),
    BRACELET_OF_ETHEREUM_UNCHARGED(
            ArmourItemRef.BRACELET_OF_ETHEREUM_UNCHARGED,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.25,
            0,
            ArmourItemRef.BRACELET_OF_ETHEREUM_UNCHARGED.getSimilarItems()),
    BRACELET_OF_SLAUGHTER(
            ArmourItemRef.BRACELET_OF_SLAUGHTER,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.25,
            0,
            ArmourItemRef.BRACELET_OF_SLAUGHTER.getSimilarItems()),
    BRONZE_GAUNTLETS(
            ArmourItemRef.BRONZE_GAUNTLETS,
            true,
            new AttackBonus(2, 2, 2, 1, 2),
            new DefenceBonus(2, 2, 2, 1, 2),
            new SkillsBonus(2, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.BRONZE_GAUNTLETS.getSimilarItems()),
    CASTLE_WARS_BRACELET_3(
            ArmourItemRef.CASTLE_WARS_BRACELET_3,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.25,
            0,
            ArmourItemRef.CASTLE_WARS_BRACELET_3.getSimilarItems()),
    CHAOS_GAUNTLETS(
            ArmourItemRef.CHAOS_GAUNTLETS,
            true,
            new AttackBonus(2, 2, 2, 0, 0),
            new DefenceBonus(8, 9, 7, 0, 0),
            new SkillsBonus(2, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.CHAOS_GAUNTLETS.getSimilarItems()),
    COMBAT_BRACELET_4(
            ArmourItemRef.COMBAT_BRACELET_4,
            true,
            new AttackBonus(7, 7, 7, 3, 7),
            new DefenceBonus(5, 5, 5, 3, 5),
            new SkillsBonus(6, 0, 0, 0),
            0.25,
            0,
            ArmourItemRef.COMBAT_BRACELET_4.getSimilarItems()),
    CONFLICTION_GAUNTLETS(
            ArmourItemRef.CONFLICTION_GAUNTLETS,
            true,
            new AttackBonus(0, 0, 0, 20, -4),
            new DefenceBonus(15, 18, 7, 5, 5),
            new SkillsBonus(0, 0, 7, 2),
            0.226,
            0,
            ArmourItemRef.CONFLICTION_GAUNTLETS.getSimilarItems(),
            levels(HITPOINTS, 90)),
    COOKING_GAUNTLETS(
            ArmourItemRef.COOKING_GAUNTLETS,
            true,
            new AttackBonus(2, 2, 2, 0, 0),
            new DefenceBonus(8, 9, 7, 0, 0),
            new SkillsBonus(2, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.COOKING_GAUNTLETS.getSimilarItems()),
    CRAB_CLAW(
            ArmourItemRef.CRAB_CLAW,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(3, 4, 2, 0, 0),
            new SkillsBonus(1, 0, 0, 0),
            0.907,
            0,
            ArmourItemRef.CRAB_CLAW.getSimilarItems()),
    CRABCLAW_HOOK(
            ArmourItemRef.CRABCLAW_HOOK,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(3, 5, 3, 0, 0),
            new SkillsBonus(1, 0, 0, 0),
            1.0,
            0,
            ArmourItemRef.CRABCLAW_HOOK.getSimilarItems()),
    DRAGON_GLOVES(
            ArmourItemRef.DRAGON_GLOVES,
            true,
            new AttackBonus(9, 9, 9, 5, 9),
            new DefenceBonus(9, 9, 9, 5, 9),
            new SkillsBonus(9, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.DRAGON_GLOVES.getSimilarItems()),
    DRAGONSTONE_GAUNTLETS(
            ArmourItemRef.DRAGONSTONE_GAUNTLETS,
            true,
            new AttackBonus(8, 8, 8, -4, -3),
            new DefenceBonus(8, 8, 8, -4, 4),
            new SkillsBonus(4, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.DRAGONSTONE_GAUNTLETS.getSimilarItems()),
    EXPEDITIOUS_BRACELET(
            ArmourItemRef.EXPEDITIOUS_BRACELET,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.25,
            0,
            ArmourItemRef.EXPEDITIOUS_BRACELET.getSimilarItems()),
    FEROCIOUS_GLOVES(
            ArmourItemRef.FEROCIOUS_GLOVES,
            true,
            new AttackBonus(16, 16, 16, -16, -16),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(14, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.FEROCIOUS_GLOVES.getSimilarItems(),
            finished(PaidQuest.DRAGON_SLAYER_II, DEFENCE, 80, ATTACK, 80)),
    FREMENNIK_GLOVES(
            ArmourItemRef.FREMENNIK_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 1, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.FREMENNIK_GLOVES.getSimilarItems()),
    GHOSTLY_GLOVES(
            ArmourItemRef.GHOSTLY_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 2, 0),
            new DefenceBonus(0, 0, 0, 2, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.001,
            0,
            ArmourItemRef.GHOSTLY_GLOVES.getSimilarItems(),
            finished(MiniQuest.CURSE_OF_THE_EMPTY_LORD)),
    GILDED_DHIDE_VAMBRACES(
            ArmourItemRef.GILDED_DHIDE_VAMBRACES,
            false,
            new AttackBonus(0, 0, 0, -10, 8),
            new DefenceBonus(3, 2, 4, 2, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            0,
            ArmourItemRef.GILDED_DHIDE_VAMBRACES.getSimilarItems()),
    GLOVES_OF_DARKNESS(
            ArmourItemRef.GLOVES_OF_DARKNESS,
            true,
            new AttackBonus(0, 0, 0, 3, 0),
            new DefenceBonus(0, 0, 0, 3, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.GLOVES_OF_DARKNESS.getSimilarItems(),
            levels(MAGIC, 40, DEFENCE, 20)),
    GLOVES_OF_SILENCE(
            ArmourItemRef.GLOVES_OF_SILENCE,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 1, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.GLOVES_OF_SILENCE.getSimilarItems()),
    GOLD_SMITH_GAUNTLETS(
            ArmourItemRef.GOLD_SMITH_GAUNTLETS,
            true,
            new AttackBonus(2, 2, 2, 0, 0),
            new DefenceBonus(8, 9, 7, 0, 0),
            new SkillsBonus(2, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.GOLD_SMITH_GAUNTLETS.getSimilarItems()),
    GRACEFUL_GLOVES_ADVENTURER(
            ArmourItemRef.GRACEFUL_GLOVES_ADVENTURER,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -3.0,
            0,
            ArmourItemRef.GRACEFUL_GLOVES_ADVENTURER.getSimilarItems()),
    GRACEFUL_GLOVES_AGILITY_ARENA(
            ArmourItemRef.GRACEFUL_GLOVES_AGILITY_ARENA,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -3.0,
            0,
            ArmourItemRef.GRACEFUL_GLOVES_AGILITY_ARENA.getSimilarItems()),
    GRACEFUL_GLOVES_ARCEUUS_WORN(
            ArmourItemRef.GRACEFUL_GLOVES_ARCEUUS_WORN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -3.0,
            0,
            ArmourItemRef.GRACEFUL_GLOVES_ARCEUUS_WORN.getSimilarItems()),
    GRACEFUL_GLOVES_HALLOWED(
            ArmourItemRef.GRACEFUL_GLOVES_HALLOWED,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -3.0,
            0,
            ArmourItemRef.GRACEFUL_GLOVES_HALLOWED.getSimilarItems()),
    GRACEFUL_GLOVES_HOSIDIUS_WORN(
            ArmourItemRef.GRACEFUL_GLOVES_HOSIDIUS_WORN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -3.0,
            0,
            ArmourItemRef.GRACEFUL_GLOVES_HOSIDIUS_WORN.getSimilarItems()),
    GRACEFUL_GLOVES_KOUREND_WORN(
            ArmourItemRef.GRACEFUL_GLOVES_KOUREND_WORN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -3.0,
            0,
            ArmourItemRef.GRACEFUL_GLOVES_KOUREND_WORN.getSimilarItems()),
    GRACEFUL_GLOVES_LOVAKENGJ_WORN(
            ArmourItemRef.GRACEFUL_GLOVES_LOVAKENGJ_WORN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -3.0,
            0,
            ArmourItemRef.GRACEFUL_GLOVES_LOVAKENGJ_WORN.getSimilarItems()),
    GRACEFUL_GLOVES_PISCARILIUS(
            ArmourItemRef.GRACEFUL_GLOVES_PISCARILIUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -3.0,
            0,
            ArmourItemRef.GRACEFUL_GLOVES_PISCARILIUS.getSimilarItems()),
    GRACEFUL_GLOVES_SHAYZIEN_WORN(
            ArmourItemRef.GRACEFUL_GLOVES_SHAYZIEN_WORN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -3.0,
            0,
            ArmourItemRef.GRACEFUL_GLOVES_SHAYZIEN_WORN.getSimilarItems()),
    GRACEFUL_GLOVES_TRAILBLAZER(
            ArmourItemRef.GRACEFUL_GLOVES_TRAILBLAZER,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -3.0,
            0,
            ArmourItemRef.GRACEFUL_GLOVES_TRAILBLAZER.getSimilarItems()),
    GRACEFUL_GLOVES_VARLAMORE_WORN(
            ArmourItemRef.GRACEFUL_GLOVES_VARLAMORE_WORN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -3.0,
            0,
            ArmourItemRef.GRACEFUL_GLOVES_VARLAMORE_WORN.getSimilarItems()),
    GRACEFUL_GLOVES_EQUIPPED(
            ArmourItemRef.GRACEFUL_GLOVES_EQUIPPED,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -3.0,
            0,
            ArmourItemRef.GRACEFUL_GLOVES_EQUIPPED.getSimilarItems()),
    GRANITE_GLOVES(
            ArmourItemRef.GRANITE_GLOVES,
            true,
            new AttackBonus(5, 5, 9, -3, -1),
            new DefenceBonus(8, 8, 8, -3, 5),
            new SkillsBonus(7, 0, 0, 0),
            1.0,
            0,
            ArmourItemRef.GRANITE_GLOVES.getSimilarItems(),
            levels(DEFENCE, 50, STRENGTH, 50)),
    GREEN_DHIDE_VAMBRACES(
            ArmourItemRef.GREEN_DHIDE_VAMBRACES,
            false,
            new AttackBonus(0, 0, 0, -10, 8),
            new DefenceBonus(1, 2, 2, 2, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.283,
            0,
            ArmourItemRef.GREEN_DHIDE_VAMBRACES.getSimilarItems(),
            levels(RANGED, 40)),
    GREEN_SPIKY_VAMBRACES(
            ArmourItemRef.GREEN_SPIKY_VAMBRACES,
            true,
            new AttackBonus(0, 0, 0, -10, 8),
            new DefenceBonus(3, 2, 4, 2, 0),
            new SkillsBonus(2, 0, 0, 0),
            0.283,
            0,
            ArmourItemRef.GREEN_SPIKY_VAMBRACES.getSimilarItems()),
    GREY_GLOVES(
            ArmourItemRef.GREY_GLOVES,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 1, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.GREY_GLOVES.getSimilarItems()),
    GUTHIX_BRACERS(
            ArmourItemRef.GUTHIX_BRACERS,
            true,
            new AttackBonus(0, 0, 0, -10, 11),
            new DefenceBonus(6, 5, 7, 8, 0),
            new SkillsBonus(0, 0, 0, 1),
            1.0,
            0,
            ArmourItemRef.GUTHIX_BRACERS.getSimilarItems(),
            levels(RANGED, 70)),
    HAM_GLOVES(
            ArmourItemRef.HAM_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 1, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.HAM_GLOVES.getSimilarItems()),
    HARDCORE_GROUP_IRONMAN_BRACERS(
            ArmourItemRef.HARDCORE_GROUP_IRONMAN_BRACERS,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(1, 1, 1, 1, 1),
            new SkillsBonus(0, 0, 0, 0),
            0.2,
            0,
            ArmourItemRef.HARDCORE_GROUP_IRONMAN_BRACERS.getSimilarItems()),
    HARDLEATHER_GLOVES(
            ArmourItemRef.HARDLEATHER_GLOVES,
            true,
            new AttackBonus(1, 1, 1, 1, 1),
            new DefenceBonus(1, 1, 1, 1, 1),
            new SkillsBonus(1, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.HARDLEATHER_GLOVES.getSimilarItems()),
    HOLY_WRAPS(
            ArmourItemRef.HOLY_WRAPS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 3),
            0.5,
            0,
            ArmourItemRef.HOLY_WRAPS.getSimilarItems(),
            levels(PRAYER, 31)),
    HUEYCOATL_HIDE_VAMBRACES(
            ArmourItemRef.HUEYCOATL_HIDE_VAMBRACES,
            true,
            new AttackBonus(0, 0, 0, -10, 11),
            new DefenceBonus(6, 5, 7, 8, 0),
            new SkillsBonus(0, 0, 0, 1),
            0.283,
            0,
            ArmourItemRef.HUEYCOATL_HIDE_VAMBRACES.getSimilarItems(),
            levels(RANGED, 70)),
    ICE_GLOVES(
            ArmourItemRef.ICE_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 3, 4, 0, 2),
            new SkillsBonus(0, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.ICE_GLOVES.getSimilarItems()),
    INFINITY_GLOVES(
            ArmourItemRef.INFINITY_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 5, 0),
            new DefenceBonus(0, 0, 0, 5, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.INFINITY_GLOVES.getSimilarItems(),
            levels(MAGIC, 50, DEFENCE, 25)),
    INOCULATION_BRACELET(
            ArmourItemRef.INOCULATION_BRACELET,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.25,
            0,
            ArmourItemRef.INOCULATION_BRACELET.getSimilarItems()),
    IRON_GAUNTLETS(
            ArmourItemRef.IRON_GAUNTLETS,
            true,
            new AttackBonus(3, 3, 3, 2, 3),
            new DefenceBonus(3, 3, 3, 2, 3),
            new SkillsBonus(3, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.IRON_GAUNTLETS.getSimilarItems()),
    KARAMJA_GLOVES_1(
            ArmourItemRef.KARAMJA_GLOVES_1,
            true,
            new AttackBonus(1, 1, 1, 1, 1),
            new DefenceBonus(1, 1, 1, 1, 1),
            new SkillsBonus(1, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.KARAMJA_GLOVES_1.getSimilarItems()),
    KARAMJA_GLOVES_2(
            ArmourItemRef.KARAMJA_GLOVES_2,
            true,
            new AttackBonus(1, 1, 1, 1, 1),
            new DefenceBonus(1, 1, 1, 1, 1),
            new SkillsBonus(1, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.KARAMJA_GLOVES_2.getSimilarItems()),
    KARAMJA_GLOVES_3(
            ArmourItemRef.KARAMJA_GLOVES_3,
            true,
            new AttackBonus(1, 1, 1, 1, 1),
            new DefenceBonus(1, 1, 1, 1, 1),
            new SkillsBonus(1, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.KARAMJA_GLOVES_3.getSimilarItems()),
    KARAMJA_GLOVES_4(
            ArmourItemRef.KARAMJA_GLOVES_4,
            true,
            new AttackBonus(1, 1, 1, 1, 1),
            new DefenceBonus(1, 1, 1, 1, 1),
            new SkillsBonus(1, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.KARAMJA_GLOVES_4.getSimilarItems()),
    KLANKS_GAUNTLETS(
            ArmourItemRef.KLANKS_GAUNTLETS,
            true,
            new AttackBonus(2, 2, 2, 0, 0),
            new DefenceBonus(8, 9, 7, 0, 0),
            new SkillsBonus(2, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.KLANKS_GAUNTLETS.getSimilarItems()),
    LEATHER_GLOVES(
            ArmourItemRef.LEATHER_GLOVES,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 1, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.LEATHER_GLOVES.getSimilarItems()),
    LEATHER_VAMBRACES(
            ArmourItemRef.LEATHER_VAMBRACES,
            false,
            new AttackBonus(0, 0, 0, 0, 4),
            new DefenceBonus(2, 2, 1, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.LEATHER_VAMBRACES.getSimilarItems()),
    LUNAR_GLOVES(
            ArmourItemRef.LUNAR_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 4, -1),
            new DefenceBonus(2, 1, 1, 2, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            0,
            ArmourItemRef.LUNAR_GLOVES.getSimilarItems(),
            started(PaidQuest.LUNAR_DIPLOMACY, MAGIC, 65, DEFENCE, 40)),
    MITHRIL_GAUNTLETS(
            ArmourItemRef.MITHRIL_GAUNTLETS,
            true,
            new AttackBonus(6, 6, 6, 3, 6),
            new DefenceBonus(6, 6, 6, 3, 6),
            new SkillsBonus(6, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.MITHRIL_GAUNTLETS.getSimilarItems()),
    MOONCLAN_GLOVES(
            ArmourItemRef.MOONCLAN_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 2, -5),
            new DefenceBonus(2, 2, 2, 2, -5),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            0,
            ArmourItemRef.MOONCLAN_GLOVES.getSimilarItems()),
    MOURNER_GLOVES(
            ArmourItemRef.MOURNER_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 1, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.MOURNER_GLOVES.getSimilarItems()),
    MYSTIC_GLOVES(
            ArmourItemRef.MYSTIC_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 3, 0),
            new DefenceBonus(0, 0, 0, 3, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.MYSTIC_GLOVES.getSimilarItems(),
            levels(MAGIC, 40, DEFENCE, 20)),
    PENANCE_GLOVES(
            ArmourItemRef.PENANCE_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 3, 4, 0, 2),
            new SkillsBonus(0, 0, 0, 0),
            -4.535,
            0,
            ArmourItemRef.PENANCE_GLOVES.getSimilarItems()),
    PIRATES_HOOK(
            ArmourItemRef.PIRATES_HOOK,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(1, 5, 3, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.3,
            0,
            ArmourItemRef.PIRATES_HOOK.getSimilarItems()),
    PURPLE_GLOVES(
            ArmourItemRef.PURPLE_GLOVES,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 1, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.PURPLE_GLOVES.getSimilarItems()),
    RANGER_GLOVES(
            ArmourItemRef.RANGER_GLOVES,
            true,
            new AttackBonus(0, 0, 0, -10, 11),
            new DefenceBonus(1, 2, 1, 2, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.RANGER_GLOVES.getSimilarItems()),
    RED_DHIDE_VAMBRACES(
            ArmourItemRef.RED_DHIDE_VAMBRACES,
            true,
            new AttackBonus(0, 0, 0, -10, 10),
            new DefenceBonus(3, 4, 4, 6, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.283,
            0,
            ArmourItemRef.RED_DHIDE_VAMBRACES.getSimilarItems(),
            levels(RANGED, 60)),
    RED_GLOVES(
            ArmourItemRef.RED_GLOVES,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 1, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.RED_GLOVES.getSimilarItems()),
    RED_SPIKY_VAMBRACES(
            ArmourItemRef.RED_SPIKY_VAMBRACES,
            true,
            new AttackBonus(0, 0, 0, -10, 10),
            new DefenceBonus(5, 4, 6, 6, 0),
            new SkillsBonus(2, 0, 0, 0),
            0.283,
            0,
            ArmourItemRef.RED_SPIKY_VAMBRACES.getSimilarItems()),
    REGEN_BRACELET(
            ArmourItemRef.REGEN_BRACELET,
            true,
            new AttackBonus(8, 8, 8, 3, 7),
            new DefenceBonus(6, 6, 6, 3, 6),
            new SkillsBonus(7, 0, 0, 0),
            0.25,
            0,
            ArmourItemRef.REGEN_BRACELET.getSimilarItems()),
    ROCKSHELL_GAUNTLETS(
            ArmourItemRef.ROCKSHELL_GAUNTLETS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 1, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            3.175,
            0,
            ArmourItemRef.ROCKSHELL_GAUNTLETS.getSimilarItems(),
            finished(PaidQuest.THE_FREMENNIK_TRIALS, DEFENCE, 40)),
    ROGUE_GLOVES(
            ArmourItemRef.ROGUE_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(2, 2, 2, 2, 2),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.ROGUE_GLOVES.getSimilarItems()),
    RUNE_GLOVES(
            ArmourItemRef.RUNE_GLOVES,
            true,
            new AttackBonus(8, 8, 8, 4, 8),
            new DefenceBonus(8, 8, 8, 4, 8),
            new SkillsBonus(8, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.RUNE_GLOVES.getSimilarItems()),
    SAMURAI_GLOVES(
            ArmourItemRef.SAMURAI_GLOVES,
            true,
            new AttackBonus(2, 2, 2, 2, 2),
            new DefenceBonus(3, 3, 3, 3, 3),
            new SkillsBonus(0, 0, 0, 0),
            0.4,
            0,
            ArmourItemRef.SAMURAI_GLOVES.getSimilarItems(),
            levels(DEFENCE, 35)),
    SARADOMIN_BRACERS(
            ArmourItemRef.SARADOMIN_BRACERS,
            true,
            new AttackBonus(0, 0, 0, -10, 11),
            new DefenceBonus(6, 5, 7, 8, 0),
            new SkillsBonus(0, 0, 0, 1),
            1.0,
            0,
            ArmourItemRef.SARADOMIN_BRACERS.getSimilarItems(),
            levels(RANGED, 70)),
    SHAYZIEN_GLOVES_1(
            ArmourItemRef.SHAYZIEN_GLOVES_1,
            true,
            new AttackBonus(0, 0, 0, -1, 0),
            new DefenceBonus(0, 0, 1, -1, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.SHAYZIEN_GLOVES_1.getSimilarItems(),
            levels(DEFENCE, 20)),
    SHAYZIEN_GLOVES_2(
            ArmourItemRef.SHAYZIEN_GLOVES_2,
            true,
            new AttackBonus(0, 0, 1, -1, 0),
            new DefenceBonus(0, 0, 1, -1, 0),
            new SkillsBonus(1, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.SHAYZIEN_GLOVES_2.getSimilarItems(),
            levels(DEFENCE, 20)),
    SHAYZIEN_GLOVES_3(
            ArmourItemRef.SHAYZIEN_GLOVES_3,
            true,
            new AttackBonus(0, 0, 2, -1, 0),
            new DefenceBonus(0, 0, 1, -1, 0),
            new SkillsBonus(2, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.SHAYZIEN_GLOVES_3.getSimilarItems(),
            levels(DEFENCE, 20)),
    SHAYZIEN_GLOVES_4(
            ArmourItemRef.SHAYZIEN_GLOVES_4,
            true,
            new AttackBonus(0, 0, 2, -1, 0),
            new DefenceBonus(0, 1, 2, -1, 1),
            new SkillsBonus(2, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.SHAYZIEN_GLOVES_4.getSimilarItems(),
            levels(DEFENCE, 20)),
    SHAYZIEN_GLOVES_5(
            ArmourItemRef.SHAYZIEN_GLOVES_5,
            true,
            new AttackBonus(0, 0, 2, -1, 6),
            new DefenceBonus(0, 2, 3, -1, 2),
            new SkillsBonus(3, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.SHAYZIEN_GLOVES_5.getSimilarItems(),
            levels(DEFENCE, 20)),
    SKELETAL_GLOVES(
            ArmourItemRef.SKELETAL_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 1, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            3.175,
            0,
            ArmourItemRef.SKELETAL_GLOVES.getSimilarItems(),
            finished(PaidQuest.THE_FREMENNIK_TRIALS, MAGIC, 40, DEFENCE, 40)),
    SLAYER_GLOVES(
            ArmourItemRef.SLAYER_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(4, 5, 3, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.SLAYER_GLOVES.getSimilarItems()),
    SNAKESKIN_VAMBRACES(
            ArmourItemRef.SNAKESKIN_VAMBRACES,
            true,
            new AttackBonus(0, 0, 0, -5, 6),
            new DefenceBonus(2, 2, 2, 1, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.283,
            0,
            ArmourItemRef.SNAKESKIN_VAMBRACES.getSimilarItems(),
            levels(RANGED, 30, DEFENCE, 30)),
    SPIKY_VAMBRACES(
            ArmourItemRef.SPIKY_VAMBRACES,
            true,
            new AttackBonus(0, 0, 0, 0, 4),
            new DefenceBonus(2, 2, 1, 0, 0),
            new SkillsBonus(2, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.SPIKY_VAMBRACES.getSimilarItems()),
    SPINED_GLOVES(
            ArmourItemRef.SPINED_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 1, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            3.175,
            0,
            ArmourItemRef.SPINED_GLOVES.getSimilarItems()),
    SPLITBARK_GLOVES(
            ArmourItemRef.SPLITBARK_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 2, -1),
            new DefenceBonus(3, 2, 4, 2, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            0,
            ArmourItemRef.SPLITBARK_GLOVES.getSimilarItems(),
            levels(MAGIC, 40, DEFENCE, 40)),
    STEEL_GAUNTLETS_FAMILY_CREST(
            ArmourItemRef.STEEL_GAUNTLETS_FAMILY_CREST,
            true,
            new AttackBonus(2, 2, 2, 0, 0),
            new DefenceBonus(8, 9, 7, 0, 0),
            new SkillsBonus(2, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.STEEL_GAUNTLETS_FAMILY_CREST.getSimilarItems()),
    STEEL_GAUNTLETS(
            ArmourItemRef.STEEL_GAUNTLETS,
            true,
            new AttackBonus(4, 4, 4, 2, 4),
            new DefenceBonus(4, 4, 4, 2, 4),
            new SkillsBonus(4, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.STEEL_GAUNTLETS.getSimilarItems()),
    SWAMP_BARK_GLOVES(
            ArmourItemRef.SWAMP_BARK_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 3, 0),
            new DefenceBonus(4, 3, 5, 4, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            0,
            ArmourItemRef.SWAMP_BARK_GLOVES.getSimilarItems()),
    TEAL_GLOVES(
            ArmourItemRef.TEAL_GLOVES,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 1, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.TEAL_GLOVES.getSimilarItems()),
    TORMENTED_BRACELET(
            ArmourItemRef.TORMENTED_BRACELET,
            true,
            new AttackBonus(0, 0, 0, 10, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 5, 2),
            0.25,
            0,
            ArmourItemRef.TORMENTED_BRACELET.getSimilarItems(),
            levels(HITPOINTS, 75)),
    TWITCHERS_GLOVES(
            ArmourItemRef.TWITCHERS_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 1, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.0,
            0,
            ArmourItemRef.TWITCHERS_GLOVES.getSimilarItems()),
    VOID_KNIGHT_GLOVES(
            ArmourItemRef.VOID_KNIGHT_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(6, 6, 6, 4, 6),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.VOID_KNIGHT_GLOVES.getSimilarItems(),
            levels(ATTACK, 42, STRENGTH, 42, DEFENCE, 42, HITPOINTS, 42, RANGED, 42, MAGIC, 42, PRAYER, 22)),
    WHITE_GLOVES(
            ArmourItemRef.WHITE_GLOVES,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 1, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 1),
            0.226,
            0,
            ArmourItemRef.WHITE_GLOVES.getSimilarItems(),
            finished(PaidQuest.WANTED, DEFENCE, 10)),
    YELLOW_GLOVES(
            ArmourItemRef.YELLOW_GLOVES,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 1, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.YELLOW_GLOVES.getSimilarItems()),
    ZAMORAK_BRACERS(
            ArmourItemRef.ZAMORAK_BRACERS,
            true,
            new AttackBonus(0, 0, 0, -10, 11),
            new DefenceBonus(6, 5, 7, 8, 0),
            new SkillsBonus(0, 0, 0, 1),
            1.0,
            0,
            ArmourItemRef.ZAMORAK_BRACERS.getSimilarItems(),
            levels(RANGED, 70)),
    ZARYTE_VAMBRACES(
            ArmourItemRef.ZARYTE_VAMBRACES,
            true,
            new AttackBonus(-8, -8, -8, 0, 18),
            new DefenceBonus(8, 8, 8, 5, 8),
            new SkillsBonus(0, 2, 0, 1),
            1.0,
            0,
            ArmourItemRef.ZARYTE_VAMBRACES.getSimilarItems(),
            levels(RANGED, 80, DEFENCE, 45));

    private final EquipmentSlot slot = EquipmentSlot.HANDS;
    private final GenericItemRef itemRef;
    private final boolean members;
    private final AttackBonus attackBonus;
    private final DefenceBonus defenceBonus;
    private final SkillsBonus skillsBonus;
    private final double weight;
    private final int attackSpeed;
    private final GenericItemRef[] similarItems;
    private final LocalRequirement requirement;

    HandsSlotRefs(
            GenericItemRef itemRef,
            boolean members,
            AttackBonus attackBonus,
            DefenceBonus defenceBonus,
            SkillsBonus skillsBonus,
            double weight,
            int attackSpeed,
            GenericItemRef[] similarItems) {
        this(
                itemRef,
                members,
                attackBonus,
                defenceBonus,
                skillsBonus,
                weight,
                attackSpeed,
                similarItems,
                LocalRequirement.none());
    }
}
