package org.dreambot.gamedata.items.equipment;

import static org.dreambot.api.methods.skills.Skill.*;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.dreambot.api.methods.container.impl.equipment.EquipmentSlot;
import org.dreambot.api.methods.quest.book.PaidQuest;
import org.dreambot.framework.requirements.Requirement;
import org.dreambot.framework.requirements.RequirementBuilder;
import org.dreambot.gamedata.combat.AttackBonus;
import org.dreambot.gamedata.combat.DefenceBonus;
import org.dreambot.gamedata.combat.SkillsBonus;
import org.dreambot.gamedata.items.ArmourItemRef;
import org.dreambot.gamedata.items.GenericItemRef;

@Getter
@AllArgsConstructor
public enum NeckSlotRef implements EquipmentRef {
    _3RD_AGE_AMULET(
            ArmourItemRef._3RD_AGE_AMULET,
            true,
            new AttackBonus(0, 0, 0, 15, 0),
            new DefenceBonus(0, 0, 0, 10, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.003,
            ArmourItemRef._3RD_AGE_AMULET.getSimilarItems(),
            new RequirementBuilder().hasLevel(MAGIC, 65).hasLevel(DEFENCE, 30).build()),
    ALCHEMISTS_AMULET_UNCHARGED(
            ArmourItemRef.ALCHEMISTS_AMULET_UNCHARGED,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.007,
            ArmourItemRef.ALCHEMISTS_AMULET_UNCHARGED.getSimilarItems()),
    AMULET_OF_ACCURACY(
            ArmourItemRef.AMULET_OF_ACCURACY,
            false,
            new AttackBonus(4, 4, 4, 4, 4),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.AMULET_OF_ACCURACY.getSimilarItems()),
    AMULET_OF_AVARICE(
            ArmourItemRef.AMULET_OF_AVARICE,
            true,
            new AttackBonus(10, 10, 10, 10, 10),
            new DefenceBonus(3, 3, 3, 3, 3),
            new SkillsBonus(6, 0, 0, 3),
            0.01,
            ArmourItemRef.AMULET_OF_AVARICE.getSimilarItems()),
    AMULET_OF_BLOOD_FURY(
            ArmourItemRef.AMULET_OF_BLOOD_FURY,
            true,
            new AttackBonus(10, 10, 10, 10, 10),
            new DefenceBonus(15, 15, 15, 15, 15),
            new SkillsBonus(8, 0, 0, 5),
            0.02,
            ArmourItemRef.AMULET_OF_BLOOD_FURY.getSimilarItems()),
    AMULET_OF_BOUNTY(
            ArmourItemRef.AMULET_OF_BOUNTY,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.007,
            ArmourItemRef.AMULET_OF_BOUNTY.getSimilarItems()),
    AMULET_OF_CHEMISTRY(
            ArmourItemRef.AMULET_OF_CHEMISTRY,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.007,
            ArmourItemRef.AMULET_OF_CHEMISTRY.getSimilarItems()),
    AMULET_OF_DEFENCE(
            ArmourItemRef.AMULET_OF_DEFENCE,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(7, 7, 7, 7, 7),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.AMULET_OF_DEFENCE.getSimilarItems()),
    AMULET_OF_DEFENCE_T(
            ArmourItemRef.AMULET_OF_DEFENCE_T,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(7, 7, 7, 7, 7),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.AMULET_OF_DEFENCE_T.getSimilarItems()),
    AMULET_OF_ETERNAL_GLORY(
            ArmourItemRef.AMULET_OF_ETERNAL_GLORY,
            true,
            new AttackBonus(10, 10, 10, 10, 10),
            new DefenceBonus(3, 3, 3, 3, 3),
            new SkillsBonus(6, 0, 0, 3),
            0.01,
            ArmourItemRef.AMULET_OF_ETERNAL_GLORY.getSimilarItems()),
    AMULET_OF_FURY(
            ArmourItemRef.AMULET_OF_FURY,
            true,
            new AttackBonus(10, 10, 10, 10, 10),
            new DefenceBonus(15, 15, 15, 15, 15),
            new SkillsBonus(8, 0, 0, 5),
            0.01,
            ArmourItemRef.AMULET_OF_FURY.getSimilarItems()),
    AMULET_OF_FURY_OR(
            ArmourItemRef.AMULET_OF_FURY_OR,
            true,
            new AttackBonus(10, 10, 10, 10, 10),
            new DefenceBonus(15, 15, 15, 15, 15),
            new SkillsBonus(8, 0, 0, 5),
            0.01,
            ArmourItemRef.AMULET_OF_FURY_OR.getSimilarItems()),
    AMULET_OF_GLORY_T_T4(
            ArmourItemRef.AMULET_OF_GLORY_T_T4,
            true,
            new AttackBonus(10, 10, 10, 10, 10),
            new DefenceBonus(3, 3, 3, 3, 3),
            new SkillsBonus(6, 0, 0, 3),
            0.01,
            ArmourItemRef.AMULET_OF_GLORY_T_T4.getSimilarItems()),
    AMULET_OF_GLORY_4(
            ArmourItemRef.AMULET_OF_GLORY_4,
            true,
            new AttackBonus(10, 10, 10, 10, 10),
            new DefenceBonus(3, 3, 3, 3, 3),
            new SkillsBonus(6, 0, 0, 3),
            0.01,
            ArmourItemRef.AMULET_OF_GLORY_4.getSimilarItems()),
    AMULET_OF_MAGIC(
            ArmourItemRef.AMULET_OF_MAGIC,
            false,
            new AttackBonus(0, 0, 0, 10, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.AMULET_OF_MAGIC.getSimilarItems()),
    AMULET_OF_POWER(
            ArmourItemRef.AMULET_OF_POWER,
            false,
            new AttackBonus(6, 6, 6, 6, 6),
            new DefenceBonus(6, 6, 6, 6, 6),
            new SkillsBonus(6, 0, 0, 1),
            0.01,
            ArmourItemRef.AMULET_OF_POWER.getSimilarItems()),
    AMULET_OF_RANCOUR(
            ArmourItemRef.AMULET_OF_RANCOUR,
            true,
            new AttackBonus(25, 25, 25, -6, -8),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(12, 0, 0, 2),
            0.012,
            ArmourItemRef.AMULET_OF_RANCOUR.getSimilarItems(),
            new RequirementBuilder().hasLevel(HITPOINTS, 90).build()),
    AMULET_OF_STRENGTH(
            ArmourItemRef.AMULET_OF_STRENGTH,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(10, 0, 0, 0),
            0.01,
            ArmourItemRef.AMULET_OF_STRENGTH.getSimilarItems()),
    AMULET_OF_THE_DAMNED_FULL(
            ArmourItemRef.AMULET_OF_THE_DAMNED_FULL,
            true,
            new AttackBonus(10, 10, 10, 10, 10),
            new DefenceBonus(3, 3, 3, 3, 3),
            new SkillsBonus(6, 0, 0, 3),
            0.1,
            ArmourItemRef.AMULET_OF_THE_DAMNED_FULL.getSimilarItems()),
    AMULET_OF_THE_EYE_REGULAR(
            ArmourItemRef.AMULET_OF_THE_EYE_REGULAR,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.25,
            ArmourItemRef.AMULET_OF_THE_EYE_REGULAR.getSimilarItems()),
    AMULET_OF_TORTURE(
            ArmourItemRef.AMULET_OF_TORTURE,
            true,
            new AttackBonus(15, 15, 15, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(10, 0, 0, 2),
            0.01,
            ArmourItemRef.AMULET_OF_TORTURE.getSimilarItems(),
            new RequirementBuilder().hasLevel(HITPOINTS, 75).build()),
    ANCIENT_STOLE(
            ArmourItemRef.ANCIENT_STOLE,
            true,
            new AttackBonus(0, 0, 0, 2, 0),
            new DefenceBonus(0, 0, 0, 2, 0),
            new SkillsBonus(0, 0, 0, 10),
            0.002,
            ArmourItemRef.ANCIENT_STOLE.getSimilarItems(),
            new RequirementBuilder().hasLevel(PRAYER, 60).build()),
    ARCEUUS_SCARF(
            ArmourItemRef.ARCEUUS_SCARF,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.5,
            ArmourItemRef.ARCEUUS_SCARF.getSimilarItems()),
    ARMADYL_STOLE(
            ArmourItemRef.ARMADYL_STOLE,
            true,
            new AttackBonus(0, 0, 0, 2, 0),
            new DefenceBonus(0, 0, 0, 2, 0),
            new SkillsBonus(0, 0, 0, 10),
            0.01,
            ArmourItemRef.ARMADYL_STOLE.getSimilarItems(),
            new RequirementBuilder().hasLevel(PRAYER, 60).build()),
    BANDOS_STOLE(
            ArmourItemRef.BANDOS_STOLE,
            true,
            new AttackBonus(0, 0, 0, 2, 0),
            new DefenceBonus(0, 0, 0, 2, 0),
            new SkillsBonus(0, 0, 0, 10),
            0.01,
            ArmourItemRef.BANDOS_STOLE.getSimilarItems(),
            new RequirementBuilder().hasLevel(PRAYER, 60).build()),
    BEADS_OF_THE_DEAD(
            ArmourItemRef.BEADS_OF_THE_DEAD,
            true,
            new AttackBonus(1, 1, 1, 1, 1),
            new DefenceBonus(1, 1, 1, 1, 1),
            new SkillsBonus(1, 0, 0, 1),
            0.01,
            ArmourItemRef.BEADS_OF_THE_DEAD.getSimilarItems()),
    BERSERKER_NECKLACE(
            ArmourItemRef.BERSERKER_NECKLACE,
            true,
            new AttackBonus(-10, -10, -10, 0, 0),
            new DefenceBonus(-20, -20, -20, -20, -20),
            new SkillsBonus(7, 0, 0, 3),
            0.01,
            ArmourItemRef.BERSERKER_NECKLACE.getSimilarItems()),
    BONECRUSHER_NECKLACE(
            ArmourItemRef.BONECRUSHER_NECKLACE,
            true,
            new AttackBonus(10, 10, 10, 10, 10),
            new DefenceBonus(2, 2, 2, 2, 2),
            new SkillsBonus(2, 0, 0, 12),
            0.025,
            ArmourItemRef.BONECRUSHER_NECKLACE.getSimilarItems(),
            new RequirementBuilder().hasLevel(PRAYER, 70).build()),
    BURNING_AMULET(
            ArmourItemRef.BURNING_AMULET,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.007,
            ArmourItemRef.BURNING_AMULET.getSimilarItems()),
    CURSED_AMULET_OF_MAGIC(
            ArmourItemRef.CURSED_AMULET_OF_MAGIC,
            false,
            new AttackBonus(0, 0, 0, -3, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, -80, 0),
            0.01,
            ArmourItemRef.CURSED_AMULET_OF_MAGIC.getSimilarItems()),
    DARK_BOW_TIE(
            ArmourItemRef.DARK_BOW_TIE,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.1,
            ArmourItemRef.DARK_BOW_TIE.getSimilarItems()),
    DESERT_AMULET_1(
            ArmourItemRef.DESERT_AMULET_1,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.DESERT_AMULET_1.getSimilarItems()),
    DESERT_AMULET_2(
            ArmourItemRef.DESERT_AMULET_2,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.DESERT_AMULET_2.getSimilarItems()),
    DESERT_AMULET_3(
            ArmourItemRef.DESERT_AMULET_3,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.DESERT_AMULET_3.getSimilarItems()),
    DESERT_AMULET_4(
            ArmourItemRef.DESERT_AMULET_4,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.DESERT_AMULET_4.getSimilarItems()),
    DIGSITE_PENDANT5(
            ArmourItemRef.DIGSITE_PENDANT5,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.DIGSITE_PENDANT5.getSimilarItems()),
    DODGY_NECKLACE(
            ArmourItemRef.DODGY_NECKLACE,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.DODGY_NECKLACE.getSimilarItems()),
    DRAGONBONE_NECKLACE(
            ArmourItemRef.DRAGONBONE_NECKLACE,
            true,
            new AttackBonus(10, 10, 10, 10, 10),
            new DefenceBonus(2, 2, 2, 2, 2),
            new SkillsBonus(2, 0, 0, 12),
            0.005,
            ArmourItemRef.DRAGONBONE_NECKLACE.getSimilarItems(),
            new RequirementBuilder().hasLevel(PRAYER, 70).build()),
    GAMES_NECKLACE_8(
            ArmourItemRef.GAMES_NECKLACE_8,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.GAMES_NECKLACE_8.getSimilarItems()),
    GHOSTSPEAK_AMULET(
            ArmourItemRef.GHOSTSPEAK_AMULET,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.GHOSTSPEAK_AMULET.getSimilarItems()),
    GIANTSOUL_AMULET_CHARGED(
            ArmourItemRef.GIANTSOUL_AMULET_CHARGED,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.GIANTSOUL_AMULET_CHARGED.getSimilarItems()),
    GNOME_AMULET(
            ArmourItemRef.GNOME_AMULET,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(13, 13, 13, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.GNOME_AMULET.getSimilarItems()),
    GUTHIX_STOLE(
            ArmourItemRef.GUTHIX_STOLE,
            true,
            new AttackBonus(0, 0, 0, 2, 0),
            new DefenceBonus(0, 0, 0, 2, 0),
            new SkillsBonus(0, 0, 0, 10),
            0.01,
            ArmourItemRef.GUTHIX_STOLE.getSimilarItems(),
            new RequirementBuilder().hasLevel(PRAYER, 60).build()),
    HOLY_SYMBOL(
            ArmourItemRef.HOLY_SYMBOL,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(2, 2, 2, 2, 2),
            new SkillsBonus(0, 0, 0, 8),
            0.007,
            ArmourItemRef.HOLY_SYMBOL.getSimilarItems()),
    HOSIDIUS_SCARF(
            ArmourItemRef.HOSIDIUS_SCARF,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.5,
            ArmourItemRef.HOSIDIUS_SCARF.getSimilarItems()),
    LIGHT_BOW_TIE(
            ArmourItemRef.LIGHT_BOW_TIE,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.1,
            ArmourItemRef.LIGHT_BOW_TIE.getSimilarItems()),
    LOVAKENGJ_SCARF(
            ArmourItemRef.LOVAKENGJ_SCARF,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.5,
            ArmourItemRef.LOVAKENGJ_SCARF.getSimilarItems()),
    LUNAR_AMULET(
            ArmourItemRef.LUNAR_AMULET,
            true,
            new AttackBonus(0, 0, 0, 1, 0),
            new DefenceBonus(0, 0, 0, 1, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.LUNAR_AMULET.getSimilarItems(),
            new RequirementBuilder().started(PaidQuest.LUNAR_DIPLOMACY).build()),
    MEDALLION_OF_THE_DEEP(
            ArmourItemRef.MEDALLION_OF_THE_DEEP,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            ArmourItemRef.MEDALLION_OF_THE_DEEP.getSimilarItems()),
    NECKLACE_OF_ANGUISH(
            ArmourItemRef.NECKLACE_OF_ANGUISH,
            true,
            new AttackBonus(0, 0, 0, 0, 15),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 5, 0, 2),
            0.01,
            ArmourItemRef.NECKLACE_OF_ANGUISH.getSimilarItems(),
            new RequirementBuilder().hasLevel(HITPOINTS, 75).build()),
    NECKLACE_OF_FAITH(
            ArmourItemRef.NECKLACE_OF_FAITH,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.NECKLACE_OF_FAITH.getSimilarItems()),
    NECKLACE_OF_PASSAGE_5(
            ArmourItemRef.NECKLACE_OF_PASSAGE_5,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.NECKLACE_OF_PASSAGE_5.getSimilarItems()),
    OCCULT_NECKLACE(
            ArmourItemRef.OCCULT_NECKLACE,
            true,
            new AttackBonus(0, 0, 0, 12, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 5, 2),
            0.005,
            ArmourItemRef.OCCULT_NECKLACE.getSimilarItems(),
            new RequirementBuilder().hasLevel(MAGIC, 70).build()),
    PENDANT_OF_ATES_CHARGED(
            ArmourItemRef.PENDANT_OF_ATES_CHARGED,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 3, 0),
            new SkillsBonus(0, 0, 0, 2),
            0.06,
            ArmourItemRef.PENDANT_OF_ATES_CHARGED.getSimilarItems()),
    PENDANT_OF_ATES_INERT(
            ArmourItemRef.PENDANT_OF_ATES_INERT,
            true,
            new AttackBonus(0, 0, 0, 2, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.06,
            ArmourItemRef.PENDANT_OF_ATES_INERT.getSimilarItems()),
    PENDANT_OF_LUCIEN(
            ArmourItemRef.PENDANT_OF_LUCIEN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.PENDANT_OF_LUCIEN.getSimilarItems()),
    PHOENIX_NECKLACE(
            ArmourItemRef.PHOENIX_NECKLACE,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            ArmourItemRef.PHOENIX_NECKLACE.getSimilarItems()),
    PISCARILIUS_SCARF(
            ArmourItemRef.PISCARILIUS_SCARF,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.5,
            ArmourItemRef.PISCARILIUS_SCARF.getSimilarItems()),
    SAILORS_AMULET_INERT(
            ArmourItemRef.SAILORS_AMULET_INERT,
            true,
            new AttackBonus(0, 0, 0, -3, 0),
            new DefenceBonus(0, 0, 0, -1, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.06,
            ArmourItemRef.SAILORS_AMULET_INERT.getSimilarItems()),
    SALVE_AMULET(
            ArmourItemRef.SALVE_AMULET,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(3, 3, 3, 0, 0),
            new SkillsBonus(0, 0, 0, 3),
            0.007,
            ArmourItemRef.SALVE_AMULET.getSimilarItems()),
    SALVE_AMULET_E(
            ArmourItemRef.SALVE_AMULET_E,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(3, 3, 3, 0, 0),
            new SkillsBonus(0, 0, 0, 3),
            0.007,
            ArmourItemRef.SALVE_AMULET_E.getSimilarItems()),
    SALVE_AMULET_EI_NIGHTMARE_ZONE(
            ArmourItemRef.SALVE_AMULET_EI_NIGHTMARE_ZONE,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(3, 3, 3, 0, 0),
            new SkillsBonus(0, 0, 0, 3),
            0.007,
            ArmourItemRef.SALVE_AMULET_EI_NIGHTMARE_ZONE.getSimilarItems()),
    SALVE_AMULET_I_NIGHTMARE_ZONE(
            ArmourItemRef.SALVE_AMULET_I_NIGHTMARE_ZONE,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(3, 3, 3, 0, 0),
            new SkillsBonus(0, 0, 0, 3),
            0.007,
            ArmourItemRef.SALVE_AMULET_I_NIGHTMARE_ZONE.getSimilarItems()),
    SARADOMIN_STOLE(
            ArmourItemRef.SARADOMIN_STOLE,
            true,
            new AttackBonus(0, 0, 0, 2, 0),
            new DefenceBonus(0, 0, 0, 2, 0),
            new SkillsBonus(0, 0, 0, 10),
            0.01,
            ArmourItemRef.SARADOMIN_STOLE.getSimilarItems(),
            new RequirementBuilder().hasLevel(PRAYER, 60).build()),
    SHAYZIEN_SCARF(
            ArmourItemRef.SHAYZIEN_SCARF,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.5,
            ArmourItemRef.SHAYZIEN_SCARF.getSimilarItems()),
    STRUNG_RABBIT_FOOT(
            ArmourItemRef.STRUNG_RABBIT_FOOT,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.03,
            ArmourItemRef.STRUNG_RABBIT_FOOT.getSimilarItems(),
            new RequirementBuilder().hasLevel(HUNTER, 24).build()),
    UNHOLY_SYMBOL(
            ArmourItemRef.UNHOLY_SYMBOL,
            true,
            new AttackBonus(2, 2, 2, 2, 2),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 8),
            0.007,
            ArmourItemRef.UNHOLY_SYMBOL.getSimilarItems()),
    VOID_SEAL_8(
            ArmourItemRef.VOID_SEAL_8,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(1, 1, 1, 1, 1),
            new SkillsBonus(0, 0, 0, 0),
            0.005,
            ArmourItemRef.VOID_SEAL_8.getSimilarItems(),
            new RequirementBuilder()
                    .hasLevel(ATTACK, 42)
                    .and()
                    .hasLevel(STRENGTH, 42)
                    .and()
                    .hasLevel(DEFENCE, 42)
                    .and()
                    .hasLevel(HITPOINTS, 42)
                    .and()
                    .hasLevel(PRAYER, 22)
                    .and()
                    .build()),
    WITCHWOOD_ICON(
            ArmourItemRef.WITCHWOOD_ICON,
            true,
            new AttackBonus(0, 0, 0, 1, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 1),
            0.007,
            ArmourItemRef.WITCHWOOD_ICON.getSimilarItems(),
            new RequirementBuilder().hasLevel(SLAYER, 35).build()),
    XERICS_TALISMAN_CHARGED(
            ArmourItemRef.XERICS_TALISMAN_CHARGED,
            true,
            new AttackBonus(0, 0, 0, 3, 0),
            new DefenceBonus(0, 0, 0, 1, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.06,
            ArmourItemRef.XERICS_TALISMAN_CHARGED.getSimilarItems()),
    XERICS_TALISMAN_INERT(
            ArmourItemRef.XERICS_TALISMAN_INERT,
            true,
            new AttackBonus(0, 0, 0, 2, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.06,
            ArmourItemRef.XERICS_TALISMAN_INERT.getSimilarItems()),
    ZAMORAK_STOLE(
            ArmourItemRef.ZAMORAK_STOLE,
            true,
            new AttackBonus(0, 0, 0, 2, 0),
            new DefenceBonus(0, 0, 0, 2, 0),
            new SkillsBonus(0, 0, 0, 10),
            0.01,
            ArmourItemRef.ZAMORAK_STOLE.getSimilarItems(),
            new RequirementBuilder().hasLevel(PRAYER, 60).build());

    private final EquipmentSlot slot = EquipmentSlot.AMULET;
    private final GenericItemRef itemRef;
    private final boolean members;
    private final AttackBonus attackBonus;
    private final DefenceBonus defenceBonus;
    private final SkillsBonus skillsBonus;
    private final double weight;
    private final GenericItemRef[] similarItems;
    private final Requirement requirement;

    NeckSlotRef(
            GenericItemRef itemRef,
            boolean members,
            AttackBonus attackBonus,
            DefenceBonus defenceBonus,
            SkillsBonus skillsBonus,
            double weight,
            GenericItemRef[] similarItems) {
        this(
                itemRef,
                members,
                attackBonus,
                defenceBonus,
                skillsBonus,
                weight,
                similarItems,
                new RequirementBuilder().build());
    }
}
