package org.dreambot.gamedata.items.equipment;

import static org.dreambot.api.methods.skills.Skill.AGILITY;
import static org.dreambot.api.methods.skills.Skill.DEFENCE;
import static org.dreambot.api.methods.skills.Skill.HITPOINTS;
import static org.dreambot.api.methods.skills.Skill.STRENGTH;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.dreambot.api.methods.container.impl.equipment.EquipmentSlot;
import org.dreambot.api.methods.quest.book.PaidQuest;
import org.dreambot.framework.requirements.Requirement;
import org.dreambot.framework.requirements.RequirementBuilder;
import org.dreambot.gamedata.combat.AttackBonus;
import org.dreambot.gamedata.combat.DefenceBonus;
import org.dreambot.gamedata.combat.SkillsBonus;
import org.dreambot.gamedata.items.ArmourItemRef;
import org.dreambot.gamedata.items.GenericItemRef;

@Getter
@AllArgsConstructor
public enum RingSlotRef implements EquipmentRef {
    ARCHERS_RING(
            ArmourItemRef.ARCHERS_RING,
            true,
            new AttackBonus(0, 0, 0, 0, 4),
            new DefenceBonus(0, 0, 0, 0, 4),
            new SkillsBonus(0, 0, 0, 0),
            0.004,
            0,
            ArmourItemRef.ARCHERS_RING.getSimilarItems()),
    ARCHERS_RING_I_NIGHTMARE_ZONE(
            ArmourItemRef.ARCHERS_RING_I_NIGHTMARE_ZONE,
            true,
            new AttackBonus(0, 0, 0, 0, 8),
            new DefenceBonus(0, 0, 0, 0, 8),
            new SkillsBonus(0, 0, 0, 0),
            0.004,
            0,
            ArmourItemRef.ARCHERS_RING_I_NIGHTMARE_ZONE.getSimilarItems()),
    BEACON_RING(
            ArmourItemRef.BEACON_RING,
            true,
            new AttackBonus(0, 0, 0, 2, 0),
            new DefenceBonus(0, 0, 0, 1, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.006,
            0,
            ArmourItemRef.BEACON_RING.getSimilarItems(),
            new RequirementBuilder().finished(PaidQuest.WHAT_LIES_BELOW).build()),
    BELLATOR_RING(
            ArmourItemRef.BELLATOR_RING,
            true,
            new AttackBonus(0, 20, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(6, 0, 0, 0),
            0.012,
            0,
            ArmourItemRef.BELLATOR_RING.getSimilarItems(),
            new RequirementBuilder()
                    .finished(PaidQuest.DESERT_TREASURE_II_THE_FALLEN_EMPIRE)
                    .build()),
    BESERKER_RING(
            ArmourItemRef.BESERKER_RING,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 4, 0, 0),
            new SkillsBonus(4, 0, 0, 0),
            0.004,
            0,
            ArmourItemRef.BESERKER_RING.getSimilarItems()),
    BESERKER_RING_I_NIGHTMARE(
            ArmourItemRef.BESERKER_RING_I_NIGHTMARE,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 8, 0, 0),
            new SkillsBonus(8, 0, 0, 0),
            0.004,
            0,
            ArmourItemRef.BESERKER_RING_I_NIGHTMARE.getSimilarItems()),
    BRIMSTONE_RING(
            ArmourItemRef.BRIMSTONE_RING,
            true,
            new AttackBonus(4, 4, 4, 6, 4),
            new DefenceBonus(4, 4, 4, 6, 4),
            new SkillsBonus(4, 0, 0, 0),
            0.004,
            0,
            ArmourItemRef.BRIMSTONE_RING.getSimilarItems()),
    CELESTIAL_RING(
            ArmourItemRef.CELESTIAL_RING,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.006,
            0,
            ArmourItemRef.CELESTIAL_RING.getSimilarItems()),
    CELESTIAL_SIGNET_UNCHARGED(
            ArmourItemRef.CELESTIAL_SIGNET_UNCHARGED,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.006,
            0,
            ArmourItemRef.CELESTIAL_SIGNET_UNCHARGED.getSimilarItems()),
    EFARITAYS_AID(
            ArmourItemRef.EFARITAYS_AID,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.006,
            0,
            ArmourItemRef.EFARITAYS_AID.getSimilarItems()),
    ELVEN_SIGNET(
            ArmourItemRef.ELVEN_SIGNET,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.006,
            0,
            ArmourItemRef.ELVEN_SIGNET.getSimilarItems()),
    ESCAPE_CRYSTAL(
            ArmourItemRef.ESCAPE_CRYSTAL,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.0,
            0,
            ArmourItemRef.ESCAPE_CRYSTAL.getSimilarItems()),
    EXPLORERS_RING_1(
            ArmourItemRef.EXPLORERS_RING_1,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 1),
            0.006,
            0,
            ArmourItemRef.EXPLORERS_RING_1.getSimilarItems()),
    EXPLORERS_RING_2(
            ArmourItemRef.EXPLORERS_RING_2,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 1),
            0.006,
            0,
            ArmourItemRef.EXPLORERS_RING_2.getSimilarItems()),
    EXPLORERS_RING_3(
            ArmourItemRef.EXPLORERS_RING_3,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 1),
            0.006,
            0,
            ArmourItemRef.EXPLORERS_RING_3.getSimilarItems()),
    EXPLORERS_RING_4(
            ArmourItemRef.EXPLORERS_RING_4,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 1),
            0.006,
            0,
            ArmourItemRef.EXPLORERS_RING_4.getSimilarItems()),
    GRANITE_RING(
            ArmourItemRef.GRANITE_RING,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(2, 2, 2, -2, 12),
            new SkillsBonus(0, 0, 0, 0),
            3.0,
            0,
            ArmourItemRef.GRANITE_RING.getSimilarItems(),
            new RequirementBuilder()
                    .hasLevel(DEFENCE, 50)
                    .and()
                    .hasLevel(STRENGTH, 50)
                    .build()),
    GRANITE_RING_I_NIGHTMARE_ZONE(
            ArmourItemRef.GRANITE_RING_I_NIGHTMARE_ZONE,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(4, 4, 4, -4, 24),
            new SkillsBonus(0, 0, 0, 0),
            3.0,
            0,
            ArmourItemRef.GRANITE_RING_I_NIGHTMARE_ZONE.getSimilarItems(),
            new RequirementBuilder()
                    .hasLevel(DEFENCE, 50)
                    .and()
                    .hasLevel(STRENGTH, 50)
                    .build()),
    LIGHTBEARER(
            ArmourItemRef.LIGHTBEARER,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.05,
            0,
            ArmourItemRef.LIGHTBEARER.getSimilarItems()),
    LUNAR_RING(
            ArmourItemRef.LUNAR_RING,
            true,
            new AttackBonus(0, 0, 0, 2, 0),
            new DefenceBonus(0, 0, 0, 2, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.006,
            0,
            ArmourItemRef.LUNAR_RING.getSimilarItems(),
            new RequirementBuilder().started(PaidQuest.LUNAR_DIPLOMACY).build()),
    MAGUS_RING(
            ArmourItemRef.MAGUS_RING,
            true,
            new AttackBonus(0, 0, 0, 15, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 2, 0),
            0.012,
            0,
            ArmourItemRef.MAGUS_RING.getSimilarItems(),
            new RequirementBuilder()
                    .finished(PaidQuest.DESERT_TREASURE_II_THE_FALLEN_EMPIRE)
                    .build()),
    RING_OF_3RD_AGE(
            ArmourItemRef.RING_OF_3RD_AGE,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.005,
            0,
            ArmourItemRef.RING_OF_3RD_AGE.getSimilarItems()),
    RING_OF_CHAROS_NORMAL(
            ArmourItemRef.RING_OF_CHAROS_NORMAL,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.005,
            0,
            ArmourItemRef.RING_OF_CHAROS_NORMAL.getSimilarItems()),
    RING_OF_COINS(
            ArmourItemRef.RING_OF_COINS,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.004,
            0,
            ArmourItemRef.RING_OF_COINS.getSimilarItems()),
    RING_OF_DUELING_8(
            ArmourItemRef.RING_OF_DUELING_8,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.006,
            0,
            ArmourItemRef.RING_OF_DUELING_8.getSimilarItems()),
    RING_OF_ENDURANCE_UNCHARGED(
            ArmourItemRef.RING_OF_ENDURANCE_UNCHARGED,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.006,
            0,
            ArmourItemRef.RING_OF_ENDURANCE_UNCHARGED.getSimilarItems(),
            new RequirementBuilder().hasLevel(AGILITY, 70).build()),
    RING_OF_FORGING(
            ArmourItemRef.RING_OF_FORGING,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.006,
            0,
            ArmourItemRef.RING_OF_FORGING.getSimilarItems()),
    RING_OF_LIFE(
            ArmourItemRef.RING_OF_LIFE,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.006,
            0,
            ArmourItemRef.RING_OF_LIFE.getSimilarItems()),
    RING_OF_NATURE(
            ArmourItemRef.RING_OF_NATURE,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.004,
            0,
            ArmourItemRef.RING_OF_NATURE.getSimilarItems()),
    RING_OF_PURSUIT(
            ArmourItemRef.RING_OF_PURSUIT,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.006,
            0,
            ArmourItemRef.RING_OF_PURSUIT.getSimilarItems()),
    RING_OF_RECOIL(
            ArmourItemRef.RING_OF_RECOIL,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.006,
            0,
            ArmourItemRef.RING_OF_RECOIL.getSimilarItems()),
    RING_OF_RETURNING_6(
            ArmourItemRef.RING_OF_RETURNING_6,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.006,
            0,
            ArmourItemRef.RING_OF_RETURNING_6.getSimilarItems()),
    RING_OF_SHADOWS(
            ArmourItemRef.RING_OF_SHADOWS,
            true,
            new AttackBonus(4, 4, 4, 5, 4),
            new DefenceBonus(0, 0, 0, 5, 0),
            new SkillsBonus(2, 0, 0, 2),
            0.004,
            0,
            ArmourItemRef.RING_OF_SHADOWS.getSimilarItems(),
            new RequirementBuilder()
                    .finished(PaidQuest.DESERT_TREASURE_II_THE_FALLEN_EMPIRE)
                    .build()),
    RING_OF_STONE(
            ArmourItemRef.RING_OF_STONE,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.006,
            0,
            ArmourItemRef.RING_OF_STONE.getSimilarItems()),
    RING_OF_SUFFERING_I_UNCHARGED_SOUL_WARS(
            ArmourItemRef.RING_OF_SUFFERING_I_UNCHARGED_SOUL_WARS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(20, 20, 20, 20, 20),
            new SkillsBonus(0, 0, 0, 4),
            0.006,
            0,
            ArmourItemRef.RING_OF_SUFFERING_I_UNCHARGED_SOUL_WARS.getSimilarItems(),
            new RequirementBuilder().hasLevel(HITPOINTS, 75).build()),
    RING_OF_SUFFERING_I_UNCHARGED_NMZ(
            ArmourItemRef.RING_OF_SUFFERING_I_UNCHARGED_NMZ,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(20, 20, 20, 20, 20),
            new SkillsBonus(0, 0, 0, 4),
            0.006,
            0,
            ArmourItemRef.RING_OF_SUFFERING_I_UNCHARGED_NMZ.getSimilarItems(),
            new RequirementBuilder().hasLevel(HITPOINTS, 75).build()),
    RING_OF_SUFFERING_I_UNCHARGED_EMIR(
            ArmourItemRef.RING_OF_SUFFERING_I_UNCHARGED_EMIR,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(20, 20, 20, 20, 20),
            new SkillsBonus(0, 0, 0, 4),
            0.006,
            0,
            ArmourItemRef.RING_OF_SUFFERING_I_UNCHARGED_EMIR.getSimilarItems(),
            new RequirementBuilder().hasLevel(HITPOINTS, 75).build()),
    RING_OF_SUFFERING(
            ArmourItemRef.RING_OF_SUFFERING,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(10, 10, 10, 10, 10),
            new SkillsBonus(0, 0, 0, 2),
            0.006,
            0,
            ArmourItemRef.RING_OF_SUFFERING.getSimilarItems(),
            new RequirementBuilder().hasLevel(HITPOINTS, 75).build()),
    RING_OF_THE_ELEMENTS_UNCHARGED(
            ArmourItemRef.RING_OF_THE_ELEMENTS_UNCHARGED,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            0,
            ArmourItemRef.RING_OF_THE_ELEMENTS_UNCHARGED.getSimilarItems()),
    RING_OF_THE_GODS(
            ArmourItemRef.RING_OF_THE_GODS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(1, 1, 1, 1, 1),
            new SkillsBonus(0, 0, 0, 4),
            0.3,
            0,
            ArmourItemRef.RING_OF_THE_GODS.getSimilarItems()),
    RING_OF_THE_GODS_I(
            ArmourItemRef.RING_OF_THE_GODS_I,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(1, 1, 1, 1, 1),
            new SkillsBonus(0, 0, 0, 8),
            0.3,
            0,
            ArmourItemRef.RING_OF_THE_GODS_I.getSimilarItems()),
    RING_OF_VISIBILITY(
            ArmourItemRef.RING_OF_VISIBILITY,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.004,
            0,
            ArmourItemRef.RING_OF_VISIBILITY.getSimilarItems()),
    RING_OF_WEALTH_I_I5(
            ArmourItemRef.RING_OF_WEALTH_I_I5,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.006,
            0,
            ArmourItemRef.RING_OF_WEALTH_I_I5.getSimilarItems()),
    RING_OF_WEALTH_5(
            ArmourItemRef.RING_OF_WEALTH_5,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.006,
            0,
            ArmourItemRef.RING_OF_WEALTH_5.getSimilarItems()),
    SEERS_RING(
            ArmourItemRef.SEERS_RING,
            true,
            new AttackBonus(0, 0, 0, 6, 0),
            new DefenceBonus(0, 0, 0, 6, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.004,
            0,
            ArmourItemRef.SEERS_RING.getSimilarItems()),
    SEERS_RING_I_NIGHTMARE_ZONE(
            ArmourItemRef.SEERS_RING_I_NIGHTMARE_ZONE,
            true,
            new AttackBonus(0, 0, 0, 12, 0),
            new DefenceBonus(0, 0, 0, 12, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.004,
            0,
            ArmourItemRef.SEERS_RING_I_NIGHTMARE_ZONE.getSimilarItems()),
    SLAYER_RING_ETERNAL(
            ArmourItemRef.SLAYER_RING_ETERNAL,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.013,
            0,
            ArmourItemRef.SLAYER_RING_ETERNAL.getSimilarItems()),
    SLAYER_RING_8(
            ArmourItemRef.SLAYER_RING_8,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.01,
            0,
            ArmourItemRef.SLAYER_RING_8.getSimilarItems()),
    STEEL_RING(
            ArmourItemRef.STEEL_RING,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(24, 24, 24, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            3.0,
            0,
            ArmourItemRef.STEEL_RING.getSimilarItems()),
    TREASONOUS_RING(
            ArmourItemRef.TREASONOUS_RING,
            true,
            new AttackBonus(4, 0, 0, 0, 0),
            new DefenceBonus(4, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.4,
            0,
            ArmourItemRef.TREASONOUS_RING.getSimilarItems()),
    TREASONOUS_RING_I_NIGHTMARE_ZONE(
            ArmourItemRef.TREASONOUS_RING_I_NIGHTMARE_ZONE,
            true,
            new AttackBonus(8, 0, 0, 0, 0),
            new DefenceBonus(8, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.4,
            0,
            ArmourItemRef.TREASONOUS_RING_I_NIGHTMARE_ZONE.getSimilarItems()),
    TYRANNICAL_RING(
            ArmourItemRef.TYRANNICAL_RING,
            true,
            new AttackBonus(0, 0, 4, 0, 0),
            new DefenceBonus(0, 0, 4, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            0,
            ArmourItemRef.TYRANNICAL_RING.getSimilarItems()),
    TYRANNICAL_RING_I_NIGHTMARE_ZONE(
            ArmourItemRef.TYRANNICAL_RING_I_NIGHTMARE_ZONE,
            true,
            new AttackBonus(0, 0, 8, 0, 0),
            new DefenceBonus(0, 0, 8, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            0,
            ArmourItemRef.TYRANNICAL_RING_I_NIGHTMARE_ZONE.getSimilarItems()),
    ULTOR_RING(
            ArmourItemRef.ULTOR_RING,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(12, 0, 0, 0),
            0.012,
            0,
            ArmourItemRef.ULTOR_RING.getSimilarItems(),
            new RequirementBuilder()
                    .finished(PaidQuest.DESERT_TREASURE_II_THE_FALLEN_EMPIRE)
                    .build()),
    VENATOR_RING(
            ArmourItemRef.VENATOR_RING,
            true,
            new AttackBonus(0, 0, 0, 0, 10),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 2, 0, 0),
            0.012,
            0,
            ArmourItemRef.VENATOR_RING.getSimilarItems(),
            new RequirementBuilder()
                    .finished(PaidQuest.DESERT_TREASURE_II_THE_FALLEN_EMPIRE)
                    .build()),
    WARRIOR_RING(
            ArmourItemRef.WARRIOR_RING,
            true,
            new AttackBonus(0, 4, 0, 0, 0),
            new DefenceBonus(0, 4, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.004,
            0,
            ArmourItemRef.WARRIOR_RING.getSimilarItems()),
    WARRIOR_RING_I_NIGHTMARE_ZONE(
            ArmourItemRef.WARRIOR_RING_I_NIGHTMARE_ZONE,
            true,
            new AttackBonus(0, 8, 0, 0, 0),
            new DefenceBonus(0, 8, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.004,
            0,
            ArmourItemRef.WARRIOR_RING_I_NIGHTMARE_ZONE.getSimilarItems());

    private final EquipmentSlot slot = EquipmentSlot.RING;
    private final GenericItemRef itemRef;
    private final boolean members;
    private final AttackBonus attackBonus;
    private final DefenceBonus defenceBonus;
    private final SkillsBonus skillsBonus;
    private final double weight;
    private final int attackSpeed;
    private final GenericItemRef[] similarItems;
    private final Requirement requirement;

    RingSlotRef(
            GenericItemRef itemRef,
            boolean members,
            AttackBonus attackBonus,
            DefenceBonus defenceBonus,
            SkillsBonus skillsBonus,
            double weight,
            int attackSpeed,
            GenericItemRef[] similarItems) {
        this(
                itemRef,
                members,
                attackBonus,
                defenceBonus,
                skillsBonus,
                weight,
                attackSpeed,
                similarItems,
                new RequirementBuilder().build());
    }
}
