package org.dreambot.gamedata.items.equipment;

import static org.dreambot.api.methods.skills.Skill.AGILITY;
import static org.dreambot.api.methods.skills.Skill.ATTACK;
import static org.dreambot.api.methods.skills.Skill.DEFENCE;
import static org.dreambot.api.methods.skills.Skill.MAGIC;
import static org.dreambot.api.methods.skills.Skill.PRAYER;
import static org.dreambot.api.methods.skills.Skill.RANGED;
import static org.dreambot.api.methods.skills.Skill.STRENGTH;
import static org.dreambot.framework.requirements.LocalRequirementHelper.*;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.dreambot.api.methods.container.impl.equipment.EquipmentSlot;
import org.dreambot.api.methods.quest.book.FreeQuest;
import org.dreambot.api.methods.quest.book.PaidQuest;
import org.dreambot.framework.requirements.LocalRequirement;
import org.dreambot.gamedata.combat.AttackBonus;
import org.dreambot.gamedata.combat.DefenceBonus;
import org.dreambot.gamedata.combat.SkillsBonus;
import org.dreambot.gamedata.items.ArmourItemRef;
import org.dreambot.gamedata.items.GenericItemRef;

@Getter
@AllArgsConstructor
public enum ShieldSlotRefs implements EquipmentRefs {
    _3RD_AGE_KITESHIELD(
            ArmourItemRef._3RD_AGE_KITESHIELD,
            true,
            new AttackBonus(0, 0, 0, -10, -4),
            new DefenceBonus(63, 65, 61, -3, 63),
            new SkillsBonus(0, 0, 0, 0),
            2.721,
            0,
            ArmourItemRef._3RD_AGE_KITESHIELD.getSimilarItems()),
    ADAMANT_DEFENDER(
            ArmourItemRef.ADAMANT_DEFENDER,
            true,
            new AttackBonus(13, 12, 11, -3, -2),
            new DefenceBonus(13, 12, 11, -3, -2),
            new SkillsBonus(4, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.ADAMANT_DEFENDER.getSimilarItems()),
    ADAMANT_KITESHIELD(
            ArmourItemRef.ADAMANT_KITESHIELD,
            false,
            new AttackBonus(0, 0, 0, -8, -3),
            new DefenceBonus(27, 31, 29, -1, 29),
            new SkillsBonus(0, 0, 0, 0),
            5.896,
            0,
            ArmourItemRef.ADAMANT_KITESHIELD.getSimilarItems(),
            levels(DEFENCE, 30)),
    ADAMANT_KITESHIELD_G(
            ArmourItemRef.ADAMANT_KITESHIELD_G,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(27, 31, 29, -1, 29),
            new SkillsBonus(0, 0, 0, 0),
            5.896,
            0,
            ArmourItemRef.ADAMANT_KITESHIELD_G.getSimilarItems(),
            levels(DEFENCE, 30)),
    ADAMANT_KITESHIELD_T(
            ArmourItemRef.ADAMANT_KITESHIELD_T,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(27, 31, 29, -1, 29),
            new SkillsBonus(0, 0, 0, 0),
            5.896,
            0,
            ArmourItemRef.ADAMANT_KITESHIELD_T.getSimilarItems(),
            levels(DEFENCE, 30)),
    ADAMANT_SQ_SHIELD(
            ArmourItemRef.ADAMANT_SQ_SHIELD,
            false,
            new AttackBonus(0, 0, 0, -6, 0),
            new DefenceBonus(24, 26, 22, 0, 24),
            new SkillsBonus(0, 0, 0, 0),
            4.082,
            0,
            ArmourItemRef.ADAMANT_SQ_SHIELD.getSimilarItems(),
            levels(DEFENCE, 30)),
    AMYS_SAW_OFF_HAND(
            ArmourItemRef.AMYS_SAW_OFF_HAND,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.8,
            0,
            ArmourItemRef.AMYS_SAW_OFF_HAND.getSimilarItems()),
    ANCIENT_DHIDE_SHIELD(
            ArmourItemRef.ANCIENT_DHIDE_SHIELD,
            true,
            new AttackBonus(-15, -15, -11, -10, 7),
            new DefenceBonus(21, 18, 16, 15, 14),
            new SkillsBonus(0, 0, 0, 1),
            8.0,
            0,
            ArmourItemRef.ANCIENT_DHIDE_SHIELD.getSimilarItems(),
            levels(RANGED, 70, DEFENCE, 40)),
    ANCIENT_KITESHIELD(
            ArmourItemRef.ANCIENT_KITESHIELD,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(44, 48, 46, -1, 46),
            new SkillsBonus(0, 0, 0, 1),
            5.443,
            0,
            ArmourItemRef.ANCIENT_KITESHIELD.getSimilarItems()),
    ANCIENT_WYVERN_SHIELD(
            ArmourItemRef.ANCIENT_WYVERN_SHIELD,
            true,
            new AttackBonus(-10, -10, -10, 15, -10),
            new DefenceBonus(72, 80, 75, 15, -5),
            new SkillsBonus(-2, 0, 2, 0),
            4.535,
            0,
            ArmourItemRef.ANCIENT_WYVERN_SHIELD.getSimilarItems(),
            started(FreeQuest.DRAGON_SLAYER_I, MAGIC, 70, DEFENCE, 75)),
    ANTI_DRAGON_SHIELD(
            ArmourItemRef.ANTI_DRAGON_SHIELD,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(7, 9, 8, 2, 8),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.ANTI_DRAGON_SHIELD.getSimilarItems()),
    ANTLER_GUARD(
            ArmourItemRef.ANTLER_GUARD,
            true,
            new AttackBonus(15, 15, 15, 9, 9),
            new DefenceBonus(-15, -15, -15, -15, -15),
            new SkillsBonus(5, 2, 0, 5),
            0.453,
            0,
            ArmourItemRef.ANTLER_GUARD.getSimilarItems(),
            levels(PRAYER, 50)),
    AQUANITE_HOPPER(
            ArmourItemRef.AQUANITE_HOPPER,
            true,
            new AttackBonus(-5, -5, -3, -13, 12),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 1, 0, 0),
            0.01,
            0,
            ArmourItemRef.AQUANITE_HOPPER.getSimilarItems()),
    ARCANE_SPIRIT_SHIELD(
            ArmourItemRef.ARCANE_SPIRIT_SHIELD,
            true,
            new AttackBonus(0, 0, 0, 20, 0),
            new DefenceBonus(53, 55, 73, 2, 52),
            new SkillsBonus(0, 0, 3, 3),
            2.0,
            0,
            ArmourItemRef.ARCANE_SPIRIT_SHIELD.getSimilarItems(),
            levels(MAGIC, 65, DEFENCE, 75, PRAYER, 70)),
    ARMADYL_DHIDE_SHIELD(
            ArmourItemRef.ARMADYL_DHIDE_SHIELD,
            true,
            new AttackBonus(-15, -15, -11, -10, 7),
            new DefenceBonus(21, 18, 16, 15, 14),
            new SkillsBonus(0, 0, 0, 1),
            8.0,
            0,
            ArmourItemRef.ARMADYL_DHIDE_SHIELD.getSimilarItems(),
            levels(RANGED, 70, DEFENCE, 40)),
    ARMADYL_KITESHIELD(
            ArmourItemRef.ARMADYL_KITESHIELD,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(44, 48, 46, -1, 46),
            new SkillsBonus(0, 0, 0, 1),
            5.443,
            0,
            ArmourItemRef.ARMADYL_KITESHIELD.getSimilarItems()),
    AVERNIC_DEFENDER(
            ArmourItemRef.AVERNIC_DEFENDER,
            true,
            new AttackBonus(30, 29, 28, -5, -4),
            new DefenceBonus(30, 29, 28, -5, -4),
            new SkillsBonus(8, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.AVERNIC_DEFENDER.getSimilarItems(),
            levels(ATTACK, 70, DEFENCE, 70)),
    BANDOS_DHIDE_SHIELD(
            ArmourItemRef.BANDOS_DHIDE_SHIELD,
            true,
            new AttackBonus(-15, -15, -11, -10, 7),
            new DefenceBonus(21, 18, 16, 15, 14),
            new SkillsBonus(0, 0, 0, 1),
            8.0,
            0,
            ArmourItemRef.BANDOS_DHIDE_SHIELD.getSimilarItems(),
            levels(RANGED, 70, DEFENCE, 40)),
    BANDOS_KITESHIELD(
            ArmourItemRef.BANDOS_KITESHIELD,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(44, 48, 46, -1, 46),
            new SkillsBonus(0, 0, 0, 1),
            5.443,
            0,
            ArmourItemRef.BANDOS_KITESHIELD.getSimilarItems()),
    BLACK_DHIDE_SHIELD(
            ArmourItemRef.BLACK_DHIDE_SHIELD,
            true,
            new AttackBonus(-15, -15, -11, -10, 7),
            new DefenceBonus(21, 18, 16, 15, 14),
            new SkillsBonus(0, 0, 0, 0),
            8.0,
            0,
            ArmourItemRef.BLACK_DHIDE_SHIELD.getSimilarItems(),
            levels(RANGED, 70, DEFENCE, 40)),
    BLACK_DEFENDER(
            ArmourItemRef.BLACK_DEFENDER,
            true,
            new AttackBonus(9, 8, 7, -3, -2),
            new DefenceBonus(9, 8, 7, -3, -2),
            new SkillsBonus(2, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.BLACK_DEFENDER.getSimilarItems()),
    BLACK_KITESHIELD(
            ArmourItemRef.BLACK_KITESHIELD,
            false,
            new AttackBonus(0, 0, 0, -8, -3),
            new DefenceBonus(17, 19, 18, -1, 18),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.BLACK_KITESHIELD.getSimilarItems(),
            levels(DEFENCE, 10)),
    BLACK_KITESHIELD_G(
            ArmourItemRef.BLACK_KITESHIELD_G,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(17, 19, 18, -1, 18),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.BLACK_KITESHIELD_G.getSimilarItems(),
            levels(DEFENCE, 10)),
    BLACK_KITESHIELD_T(
            ArmourItemRef.BLACK_KITESHIELD_T,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(17, 19, 18, -1, 18),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.BLACK_KITESHIELD_T.getSimilarItems(),
            levels(DEFENCE, 10)),
    BLACK_SQ_SHIELD(
            ArmourItemRef.BLACK_SQ_SHIELD,
            false,
            new AttackBonus(0, 0, 0, -6, 0),
            new DefenceBonus(15, 16, 14, 0, 15),
            new SkillsBonus(0, 0, 0, 0),
            3.628,
            0,
            ArmourItemRef.BLACK_SQ_SHIELD.getSimilarItems(),
            levels(DEFENCE, 10)),
    BLESSED_SPIRIT_SHIELD(
            ArmourItemRef.BLESSED_SPIRIT_SHIELD,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(53, 55, 73, 2, 52),
            new SkillsBonus(0, 0, 0, 3),
            2.0,
            0,
            ArmourItemRef.BLESSED_SPIRIT_SHIELD.getSimilarItems(),
            levels(PRAYER, 60, DEFENCE, 70)),
    BLUE_DHIDE_SHIELD(
            ArmourItemRef.BLUE_DHIDE_SHIELD,
            true,
            new AttackBonus(-15, -15, -11, -10, 5),
            new DefenceBonus(16, 14, 12, 12, 12),
            new SkillsBonus(0, 0, 0, 0),
            8.0,
            0,
            ArmourItemRef.BLUE_DHIDE_SHIELD.getSimilarItems(),
            levels(RANGED, 50, DEFENCE, 40)),
    BOOK_OF_BALANCE(
            ArmourItemRef.BOOK_OF_BALANCE,
            true,
            new AttackBonus(4, 4, 4, 4, 4),
            new DefenceBonus(4, 4, 4, 4, 4),
            new SkillsBonus(0, 0, 0, 5),
            1.0,
            0,
            ArmourItemRef.BOOK_OF_BALANCE.getSimilarItems(),
            finished(PaidQuest.HORROR_FROM_THE_DEEP)),
    BOOK_OF_BALANCE_OR(
            ArmourItemRef.BOOK_OF_BALANCE_OR,
            true,
            new AttackBonus(4, 4, 4, 4, 4),
            new DefenceBonus(4, 4, 4, 4, 4),
            new SkillsBonus(0, 0, 0, 5),
            1.0,
            0,
            new GenericItemRef[] {ArmourItemRef.BOOK_OF_BALANCE_OR},
            finished(PaidQuest.HORROR_FROM_THE_DEEP)),
    BOOK_OF_DARKNESS(
            ArmourItemRef.BOOK_OF_DARKNESS,
            true,
            new AttackBonus(0, 0, 0, 10, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 5),
            1.0,
            0,
            ArmourItemRef.BOOK_OF_DARKNESS.getSimilarItems(),
            finished(PaidQuest.HORROR_FROM_THE_DEEP)),
    BOOK_OF_LAW(
            ArmourItemRef.BOOK_OF_LAW,
            true,
            new AttackBonus(0, 0, 0, 0, 10),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 5),
            1.0,
            0,
            ArmourItemRef.BOOK_OF_LAW.getSimilarItems(),
            finished(PaidQuest.HORROR_FROM_THE_DEEP)),
    BOOK_OF_LAW_OR(
            ArmourItemRef.BOOK_OF_LAW_OR,
            true,
            new AttackBonus(0, 0, 0, 0, 10),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 5),
            1.0,
            0,
            new GenericItemRef[] {ArmourItemRef.BOOK_OF_LAW_OR},
            finished(PaidQuest.HORROR_FROM_THE_DEEP)),
    BOOK_OF_THE_DEAD(
            ArmourItemRef.BOOK_OF_THE_DEAD,
            true,
            new AttackBonus(0, 0, 0, 6, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 3),
            0.2,
            0,
            ArmourItemRef.BOOK_OF_THE_DEAD.getSimilarItems(),
            finished(PaidQuest.A_KINGDOM_DIVIDED)),
    BOOK_OF_WAR(
            ArmourItemRef.BOOK_OF_WAR,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(2, 0, 0, 5),
            1.0,
            0,
            ArmourItemRef.BOOK_OF_WAR.getSimilarItems(),
            finished(PaidQuest.HORROR_FROM_THE_DEEP)),
    BRIEFCASE(
            ArmourItemRef.BRIEFCASE,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.005,
            0,
            ArmourItemRef.BRIEFCASE.getSimilarItems()),
    BRONZE_DEFENDER(
            ArmourItemRef.BRONZE_DEFENDER,
            true,
            new AttackBonus(3, 2, 1, -3, -2),
            new DefenceBonus(3, 2, 1, -3, -2),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.BRONZE_DEFENDER.getSimilarItems()),
    BRONZE_KITESHIELD(
            ArmourItemRef.BRONZE_KITESHIELD,
            false,
            new AttackBonus(0, 0, 0, -8, -3),
            new DefenceBonus(5, 7, 6, -1, 6),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.BRONZE_KITESHIELD.getSimilarItems()),
    BRONZE_KITESHIELD_G(
            ArmourItemRef.BRONZE_KITESHIELD_G,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(5, 7, 6, -1, 6),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.BRONZE_KITESHIELD_G.getSimilarItems()),
    BRONZE_KITESHIELD_T(
            ArmourItemRef.BRONZE_KITESHIELD_T,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(5, 7, 6, -1, 6),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.BRONZE_KITESHIELD_T.getSimilarItems()),
    BRONZE_SQ_SHIELD(
            ArmourItemRef.BRONZE_SQ_SHIELD,
            false,
            new AttackBonus(0, 0, 0, -6, 0),
            new DefenceBonus(5, 6, 4, 0, 5),
            new SkillsBonus(0, 0, 0, 0),
            3.628,
            0,
            ArmourItemRef.BRONZE_SQ_SHIELD.getSimilarItems()),
    BROODOO_SHIELD_COMBAT_UNCHARGED(
            ArmourItemRef.BROODOO_SHIELD_COMBAT_UNCHARGED,
            true,
            new AttackBonus(0, 0, 0, 3, -7),
            new DefenceBonus(10, 10, 15, 5, 0),
            new SkillsBonus(0, 0, 0, 5),
            5.443,
            0,
            ArmourItemRef.BROODOO_SHIELD_COMBAT_UNCHARGED.getSimilarItems(),
            levels(MAGIC, 25, DEFENCE, 25)),
    BROODOO_SHIELD_DISEASE_UNCHARGED(
            ArmourItemRef.BROODOO_SHIELD_DISEASE_UNCHARGED,
            true,
            new AttackBonus(0, 0, 0, 3, -7),
            new DefenceBonus(10, 10, 15, 5, 0),
            new SkillsBonus(0, 0, 0, 5),
            5.443,
            0,
            ArmourItemRef.BROODOO_SHIELD_DISEASE_UNCHARGED.getSimilarItems(),
            levels(MAGIC, 25, DEFENCE, 25)),
    BROODOO_SHIELD_POISON_UNCHARGED(
            ArmourItemRef.BROODOO_SHIELD_POISON_UNCHARGED,
            true,
            new AttackBonus(0, 0, 0, 3, -7),
            new DefenceBonus(10, 10, 15, 5, 0),
            new SkillsBonus(0, 0, 0, 5),
            5.443,
            0,
            ArmourItemRef.BROODOO_SHIELD_POISON_UNCHARGED.getSimilarItems(),
            levels(MAGIC, 25, DEFENCE, 25)),
    CABBAGE_ROUND_SHIELD(
            ArmourItemRef.CABBAGE_ROUND_SHIELD,
            true,
            new AttackBonus(0, 0, 0, -6, -2),
            new DefenceBonus(24, 26, 22, 0, 24),
            new SkillsBonus(0, 0, 0, 0),
            4.535,
            0,
            ArmourItemRef.CABBAGE_ROUND_SHIELD.getSimilarItems()),
    COLLECTION_LOG(
            ArmourItemRef.COLLECTION_LOG,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.51,
            0,
            ArmourItemRef.COLLECTION_LOG.getSimilarItems()),
    CRYSTAL_SHIELD_ACTIVE(
            ArmourItemRef.CRYSTAL_SHIELD_ACTIVE,
            true,
            new AttackBonus(0, 0, 0, -10, -10),
            new DefenceBonus(51, 54, 53, 0, 80),
            new SkillsBonus(0, 0, 0, 0),
            2.721,
            0,
            ArmourItemRef.CRYSTAL_SHIELD_ACTIVE.getSimilarItems(),
            finished(PaidQuest.ROVING_ELVES, DEFENCE, 70, AGILITY, 50)),
    DECORATIVE_SHIELD_GOLD(
            ArmourItemRef.DECORATIVE_SHIELD_GOLD,
            false,
            new AttackBonus(0, 0, 0, -8, -3),
            new DefenceBonus(27, 31, 29, -1, 29),
            new SkillsBonus(0, 0, 0, 0),
            4.535,
            0,
            ArmourItemRef.DECORATIVE_SHIELD_GOLD.getSimilarItems()),
    DECORATIVE_SHIELD_RED(
            ArmourItemRef.DECORATIVE_SHIELD_RED,
            false,
            new AttackBonus(0, 0, 0, -8, -3),
            new DefenceBonus(13, 15, 14, -1, 14),
            new SkillsBonus(0, 0, 0, 0),
            4.535,
            0,
            ArmourItemRef.DECORATIVE_SHIELD_RED.getSimilarItems()),
    DECORATIVE_SHIELD_WHITE(
            ArmourItemRef.DECORATIVE_SHIELD_WHITE,
            false,
            new AttackBonus(0, 0, 0, -8, -3),
            new DefenceBonus(18, 22, 20, -1, 20),
            new SkillsBonus(0, 0, 0, 0),
            4.535,
            0,
            ArmourItemRef.DECORATIVE_SHIELD_WHITE.getSimilarItems()),
    DEFENSIVE_SHIELD(
            ArmourItemRef.DEFENSIVE_SHIELD,
            true,
            new AttackBonus(0, 0, 0, -6, -2),
            new DefenceBonus(8, 9, 7, 0, 7),
            new SkillsBonus(0, 0, 0, 0),
            3.628,
            0,
            ArmourItemRef.DEFENSIVE_SHIELD.getSimilarItems()),
    DRAGON_DEFENDER(
            ArmourItemRef.DRAGON_DEFENDER,
            true,
            new AttackBonus(25, 24, 23, -3, -2),
            new DefenceBonus(25, 24, 23, -3, -2),
            new SkillsBonus(6, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.DRAGON_DEFENDER.getSimilarItems()),
    DRAGON_KITESHIELD(
            ArmourItemRef.DRAGON_KITESHIELD,
            true,
            new AttackBonus(0, 0, 0, -8, -3),
            new DefenceBonus(56, 60, 58, -1, 58),
            new SkillsBonus(0, 0, 0, 0),
            6.803,
            0,
            ArmourItemRef.DRAGON_KITESHIELD.getSimilarItems(),
            levels(DEFENCE, 60)),
    DRAGON_KITESHIELD_G(
            ArmourItemRef.DRAGON_KITESHIELD_G,
            true,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(56, 60, 58, -1, 58),
            new SkillsBonus(0, 0, 0, 0),
            6.803,
            0,
            ArmourItemRef.DRAGON_KITESHIELD_G.getSimilarItems(),
            levels(DEFENCE, 60)),
    DRAGON_SQ_SHIELD(
            ArmourItemRef.DRAGON_SQ_SHIELD,
            true,
            new AttackBonus(0, 0, 0, -6, 0),
            new DefenceBonus(50, 52, 48, 0, 50),
            new SkillsBonus(0, 0, 0, 0),
            3.175,
            0,
            ArmourItemRef.DRAGON_SQ_SHIELD.getSimilarItems(),
            finished(PaidQuest.LEGENDS_QUEST, DEFENCE, 60)),
    DRAGON_SQ_SHIELD_G(
            ArmourItemRef.DRAGON_SQ_SHIELD_G,
            true,
            new AttackBonus(0, 0, 0, -6, 0),
            new DefenceBonus(50, 52, 48, 0, 50),
            new SkillsBonus(0, 0, 0, 0),
            3.175,
            0,
            ArmourItemRef.DRAGON_SQ_SHIELD_G.getSimilarItems(),
            finished(PaidQuest.LEGENDS_QUEST, DEFENCE, 60)),
    DRAGONFIRE_SHIELD_CHARGED(
            ArmourItemRef.DRAGONFIRE_SHIELD_CHARGED,
            true,
            new AttackBonus(0, 0, 0, -10, -5),
            new DefenceBonus(70, 75, 72, 10, 72),
            new SkillsBonus(7, 0, 0, 0),
            7.257,
            0,
            ArmourItemRef.DRAGONFIRE_SHIELD_CHARGED.getSimilarItems(),
            started(FreeQuest.DRAGON_SLAYER_I, DEFENCE, 75)),
    DRAGONFIRE_WARD_CHARGED(
            ArmourItemRef.DRAGONFIRE_WARD_CHARGED,
            true,
            new AttackBonus(-10, -10, -10, -10, 15),
            new DefenceBonus(25, 30, 28, 28, 68),
            new SkillsBonus(-2, 8, 0, 0),
            4.082,
            0,
            ArmourItemRef.DRAGONFIRE_WARD_CHARGED.getSimilarItems(),
            finished(FreeQuest.DRAGON_SLAYER_I, RANGED, 70, DEFENCE, 75)),
    ELEMENTAL_SHIELD(
            ArmourItemRef.ELEMENTAL_SHIELD,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 6, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.ELEMENTAL_SHIELD.getSimilarItems(),
            finished(PaidQuest.ELEMENTAL_WORKSHOP_I)),
    ELIDINIS_WARD(
            ArmourItemRef.ELIDINIS_WARD,
            true,
            new AttackBonus(0, 0, 0, 5, 0),
            new DefenceBonus(5, 3, 9, 0, 6),
            new SkillsBonus(0, 0, 3, 1),
            0.708,
            0,
            ArmourItemRef.ELIDINIS_WARD.getSimilarItems(),
            levels(MAGIC, 80, DEFENCE, 80, PRAYER, 80)),
    ELIDINIS_WARD_F(
            ArmourItemRef.ELIDINIS_WARD_F,
            true,
            new AttackBonus(0, 0, 0, 25, 0),
            new DefenceBonus(53, 55, 73, 2, 52),
            new SkillsBonus(0, 0, 5, 4),
            3.708,
            0,
            ArmourItemRef.ELIDINIS_WARD_F.getSimilarItems(),
            levels(MAGIC, 80, DEFENCE, 80, PRAYER, 80)),
    ELYSIAN_SPIRIT_SHIELD(
            ArmourItemRef.ELYSIAN_SPIRIT_SHIELD,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(63, 65, 75, 2, 57),
            new SkillsBonus(0, 0, 0, 3),
            2.0,
            0,
            ArmourItemRef.ELYSIAN_SPIRIT_SHIELD.getSimilarItems(),
            levels(PRAYER, 75, DEFENCE, 75)),
    FALADOR_SHIELD_1(
            ArmourItemRef.FALADOR_SHIELD_1,
            true,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(8, 10, 9, -1, 9),
            new SkillsBonus(0, 0, 0, 1),
            5.443,
            0,
            ArmourItemRef.FALADOR_SHIELD_1.getSimilarItems()),
    FALADOR_SHIELD_2(
            ArmourItemRef.FALADOR_SHIELD_2,
            true,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(13, 15, 14, -1, 14),
            new SkillsBonus(0, 0, 0, 3),
            5.443,
            0,
            ArmourItemRef.FALADOR_SHIELD_2.getSimilarItems()),
    FALADOR_SHIELD_3(
            ArmourItemRef.FALADOR_SHIELD_3,
            true,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(18, 22, 20, -1, 20),
            new SkillsBonus(0, 0, 0, 4),
            5.443,
            0,
            ArmourItemRef.FALADOR_SHIELD_3.getSimilarItems()),
    FALADOR_SHIELD_4(
            ArmourItemRef.FALADOR_SHIELD_4,
            true,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(27, 31, 29, -1, 29),
            new SkillsBonus(0, 0, 0, 5),
            5.443,
            0,
            ArmourItemRef.FALADOR_SHIELD_4.getSimilarItems()),
    FLETCHING_KNIFE(
            ArmourItemRef.FLETCHING_KNIFE,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.FLETCHING_KNIFE.getSimilarItems()),
    FREMENNIK_SHIELD(
            ArmourItemRef.FREMENNIK_SHIELD,
            true,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(27, 31, 29, -1, 29),
            new SkillsBonus(0, 0, 0, 0),
            2.267,
            0,
            ArmourItemRef.FREMENNIK_SHIELD.getSimilarItems(),
            finished(PaidQuest.THE_FREMENNIK_TRIALS, DEFENCE, 30)),
    GHOMMALS_AVERNIC_DEFENDER_5(
            ArmourItemRef.GHOMMALS_AVERNIC_DEFENDER_5,
            true,
            new AttackBonus(30, 29, 28, -5, -4),
            new DefenceBonus(30, 29, 28, -5, -4),
            new SkillsBonus(8, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.GHOMMALS_AVERNIC_DEFENDER_5.getSimilarItems(),
            levels(ATTACK, 70, DEFENCE, 70)),
    GHOMMALS_AVERNIC_DEFENDER_6(
            ArmourItemRef.GHOMMALS_AVERNIC_DEFENDER_6,
            true,
            new AttackBonus(30, 29, 28, -5, -4),
            new DefenceBonus(30, 29, 28, -5, -4),
            new SkillsBonus(8, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.GHOMMALS_AVERNIC_DEFENDER_6.getSimilarItems(),
            levels(ATTACK, 70, DEFENCE, 70)),
    GILDED_KITESHIELD(
            ArmourItemRef.GILDED_KITESHIELD,
            false,
            new AttackBonus(0, 0, 0, -8, -3),
            new DefenceBonus(44, 48, 46, -1, 46),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.GILDED_KITESHIELD.getSimilarItems()),
    GILDED_SQ_SHIELD(
            ArmourItemRef.GILDED_SQ_SHIELD,
            false,
            new AttackBonus(0, 0, 0, -6, 0),
            new DefenceBonus(38, 40, 36, 0, 38),
            new SkillsBonus(0, 0, 0, 0),
            3.628,
            0,
            ArmourItemRef.GILDED_SQ_SHIELD.getSimilarItems()),
    GRANITE_SHIELD(
            ArmourItemRef.GRANITE_SHIELD,
            true,
            new AttackBonus(0, 0, 0, -12, -8),
            new DefenceBonus(40, 42, 38, 0, 65),
            new SkillsBonus(0, 0, 0, 0),
            6.803,
            0,
            ArmourItemRef.GRANITE_SHIELD.getSimilarItems(),
            levels(DEFENCE, 50, STRENGTH, 50)),
    GREEN_DHIDE_SHIELD(
            ArmourItemRef.GREEN_DHIDE_SHIELD,
            true,
            new AttackBonus(-15, -15, -11, -10, 4),
            new DefenceBonus(14, 12, 11, 9, 11),
            new SkillsBonus(0, 0, 0, 0),
            8.0,
            0,
            ArmourItemRef.GREEN_DHIDE_SHIELD.getSimilarItems(),
            levels(RANGED, 40, DEFENCE, 40)),
    GUTHIX_DHIDE_SHIELD(
            ArmourItemRef.GUTHIX_DHIDE_SHIELD,
            true,
            new AttackBonus(-15, -15, -11, -10, 7),
            new DefenceBonus(21, 18, 16, 15, 14),
            new SkillsBonus(0, 0, 0, 1),
            8.0,
            0,
            ArmourItemRef.GUTHIX_DHIDE_SHIELD.getSimilarItems(),
            levels(RANGED, 70, DEFENCE, 40)),
    GUTHIX_KITESHIELD(
            ArmourItemRef.GUTHIX_KITESHIELD,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(44, 48, 46, -1, 46),
            new SkillsBonus(0, 0, 0, 1),
            5.443,
            0,
            ArmourItemRef.GUTHIX_KITESHIELD.getSimilarItems()),
    HARD_LEATHER_SHIELD(
            ArmourItemRef.HARD_LEATHER_SHIELD,
            true,
            new AttackBonus(-15, -15, -11, -10, 2),
            new DefenceBonus(8, 7, 7, 5, 9),
            new SkillsBonus(0, 0, 0, 0),
            7.0,
            0,
            ArmourItemRef.HARD_LEATHER_SHIELD.getSimilarItems(),
            levels(RANGED, 20, DEFENCE, 10)),
    HOLY_BOOK(
            ArmourItemRef.HOLY_BOOK,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(8, 8, 8, 8, 8),
            new SkillsBonus(0, 0, 0, 5),
            1.0,
            0,
            ArmourItemRef.HOLY_BOOK.getSimilarItems(),
            finished(PaidQuest.HORROR_FROM_THE_DEEP)),
    IMCANDO_HAMMER_OFF_HAND(
            ArmourItemRef.IMCANDO_HAMMER_OFF_HAND,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            2.0,
            0,
            ArmourItemRef.IMCANDO_HAMMER_OFF_HAND.getSimilarItems()),
    IRON_DEFENDER(
            ArmourItemRef.IRON_DEFENDER,
            true,
            new AttackBonus(5, 4, 3, -3, -2),
            new DefenceBonus(5, 4, 3, -3, -2),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.IRON_DEFENDER.getSimilarItems()),
    IRON_KITESHIELD(
            ArmourItemRef.IRON_KITESHIELD,
            false,
            new AttackBonus(0, 0, 0, -8, -3),
            new DefenceBonus(8, 10, 9, -1, 9),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.IRON_KITESHIELD.getSimilarItems()),
    IRON_KITESHIELD_G(
            ArmourItemRef.IRON_KITESHIELD_G,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(8, 10, 9, -1, 9),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.IRON_KITESHIELD_G.getSimilarItems()),
    IRON_KITESHIELD_T(
            ArmourItemRef.IRON_KITESHIELD_T,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(8, 10, 9, -1, 9),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.IRON_KITESHIELD_T.getSimilarItems()),
    IRON_SQ_SHIELD(
            ArmourItemRef.IRON_SQ_SHIELD,
            false,
            new AttackBonus(0, 0, 0, -6, 0),
            new DefenceBonus(8, 9, 7, 0, 8),
            new SkillsBonus(0, 0, 0, 0),
            3.628,
            0,
            ArmourItemRef.IRON_SQ_SHIELD.getSimilarItems()),
    KHAREDSTS_MEMOIRS(
            ArmourItemRef.KHAREDSTS_MEMOIRS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 1),
            0.2,
            0,
            ArmourItemRef.KHAREDSTS_MEMOIRS.getSimilarItems()),
    MAGES_BOOK(
            ArmourItemRef.MAGES_BOOK,
            true,
            new AttackBonus(0, 0, 0, 15, 0),
            new DefenceBonus(0, 0, 0, 15, 0),
            new SkillsBonus(0, 0, 2, 0),
            1.0,
            0,
            ArmourItemRef.MAGES_BOOK.getSimilarItems(),
            levels(MAGIC, 60)),
    MAGIC_SHIELD(
            ArmourItemRef.MAGIC_SHIELD,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(10, 13, 9, 3, 9),
            new SkillsBonus(0, 0, 0, 0),
            3.175,
            0,
            ArmourItemRef.MAGIC_SHIELD.getSimilarItems()),
    MALEDICTION_WARD(
            ArmourItemRef.MALEDICTION_WARD,
            true,
            new AttackBonus(-8, -8, -8, 12, -12),
            new DefenceBonus(50, 52, 48, 15, 0),
            new SkillsBonus(0, 0, 2, 0),
            3.628,
            0,
            ArmourItemRef.MALEDICTION_WARD.getSimilarItems(),
            levels(DEFENCE, 60)),
    MAPLE_SHIELD(
            ArmourItemRef.MAPLE_SHIELD,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(7, 8, 6, 2, 7),
            new SkillsBonus(0, 0, 0, 0),
            3.175,
            0,
            ArmourItemRef.MAPLE_SHIELD.getSimilarItems()),
    MIND_SHIELD(
            ArmourItemRef.MIND_SHIELD,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 9, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.226,
            0,
            ArmourItemRef.MIND_SHIELD.getSimilarItems(),
            finished(PaidQuest.ELEMENTAL_WORKSHOP_II)),
    MIRROR_SHEILD(
            ArmourItemRef.MIRROR_SHEILD,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(10, 15, 5, 5, 10),
            new SkillsBonus(0, 0, 0, 0),
            2.267,
            0,
            ArmourItemRef.MIRROR_SHEILD.getSimilarItems()),
    MITHRIL_DEFENDER(
            ArmourItemRef.MITHRIL_DEFENDER,
            true,
            new AttackBonus(10, 9, 8, -3, -2),
            new DefenceBonus(10, 9, 8, -3, -2),
            new SkillsBonus(3, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.MITHRIL_DEFENDER.getSimilarItems()),
    MITHRIL_KITESHIELD(
            ArmourItemRef.MITHRIL_KITESHIELD,
            false,
            new AttackBonus(0, 0, 0, -8, -3),
            new DefenceBonus(18, 22, 20, -1, 20),
            new SkillsBonus(0, 0, 0, 0),
            4.535,
            0,
            ArmourItemRef.MITHRIL_KITESHIELD.getSimilarItems(),
            levels(DEFENCE, 20)),
    MITHRIL_KITESHIELD_G(
            ArmourItemRef.MITHRIL_KITESHIELD_G,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(18, 22, 20, -1, 20),
            new SkillsBonus(0, 0, 0, 0),
            4.535,
            0,
            ArmourItemRef.MITHRIL_KITESHIELD_G.getSimilarItems(),
            levels(DEFENCE, 20)),
    MITHRIL_KITESHIELD_T(
            ArmourItemRef.MITHRIL_KITESHIELD_T,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(18, 22, 20, -1, 20),
            new SkillsBonus(0, 0, 0, 0),
            4.535,
            0,
            ArmourItemRef.MITHRIL_KITESHIELD_T.getSimilarItems(),
            levels(DEFENCE, 20)),
    MITHRIL_SQ_SHIELD(
            ArmourItemRef.MITHRIL_SQ_SHIELD,
            false,
            new AttackBonus(0, 0, 0, -6, 0),
            new DefenceBonus(17, 19, 15, 0, 17),
            new SkillsBonus(0, 0, 0, 0),
            3.175,
            0,
            ArmourItemRef.MITHRIL_SQ_SHIELD.getSimilarItems(),
            levels(DEFENCE, 20)),
    MOOLETA(
            ArmourItemRef.MOOLETA,
            false,
            new AttackBonus(5, 7, 7, -1, -1),
            new DefenceBonus(4, 8, 8, -2, -1),
            new SkillsBonus(1, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.MOOLETA.getSimilarItems()),
    NEITIZNOT_SHIELD(
            ArmourItemRef.NEITIZNOT_SHIELD,
            true,
            new AttackBonus(0, 0, 0, -10, -10),
            new DefenceBonus(17, 17, 31, -4, 33),
            new SkillsBonus(0, 0, 0, 0),
            3.628,
            0,
            ArmourItemRef.NEITIZNOT_SHIELD.getSimilarItems(),
            levels(DEFENCE, 25)),
    OAK_SHIELD(
            ArmourItemRef.OAK_SHIELD,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(5, 6, 4, 1, 5),
            new SkillsBonus(0, 0, 0, 0),
            3.175,
            0,
            ArmourItemRef.OAK_SHIELD.getSimilarItems()),
    ODIUM_WARD(
            ArmourItemRef.ODIUM_WARD,
            true,
            new AttackBonus(-12, -12, -12, -8, 12),
            new DefenceBonus(0, 0, 0, 24, 52),
            new SkillsBonus(0, 4, 0, 0),
            3.628,
            0,
            ArmourItemRef.ODIUM_WARD.getSimilarItems(),
            levels(DEFENCE, 60)),
    ODIUM_WARD_OR(
            ArmourItemRef.ODIUM_WARD_OR,
            true,
            new AttackBonus(-12, -12, -12, -8, 12),
            new DefenceBonus(0, 0, 0, 24, 52),
            new SkillsBonus(0, 4, 0, 0),
            3.628,
            0,
            new GenericItemRef[] {ArmourItemRef.ODIUM_WARD_OR},
            levels(DEFENCE, 60)),
    RED_DHIDE_SHIELD(
            ArmourItemRef.RED_DHIDE_SHIELD,
            true,
            new AttackBonus(-15, -15, -11, -10, 6),
            new DefenceBonus(18, 16, 14, 13, 13),
            new SkillsBonus(0, 0, 0, 0),
            8.0,
            0,
            ArmourItemRef.RED_DHIDE_SHIELD.getSimilarItems(),
            levels(RANGED, 60, DEFENCE, 40)),
    REDWOOD_SHIELD(
            ArmourItemRef.REDWOOD_SHIELD,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(12, 15, 11, 4, 10),
            new SkillsBonus(0, 0, 0, 0),
            3.175,
            0,
            ArmourItemRef.REDWOOD_SHIELD.getSimilarItems()),
    RUNE_DEFENDER_T(
            ArmourItemRef.RUNE_DEFENDER_T,
            true,
            new AttackBonus(20, 19, 18, -3, -2),
            new DefenceBonus(20, 19, 18, -3, -2),
            new SkillsBonus(5, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.RUNE_DEFENDER_T.getSimilarItems()),
    RUNE_DEFENDER(
            ArmourItemRef.RUNE_DEFENDER,
            true,
            new AttackBonus(20, 19, 18, -3, -2),
            new DefenceBonus(20, 19, 18, -3, -2),
            new SkillsBonus(5, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.RUNE_DEFENDER.getSimilarItems()),
    RUNE_KITESHIELD(
            ArmourItemRef.RUNE_KITESHIELD,
            false,
            new AttackBonus(0, 0, 0, -8, -3),
            new DefenceBonus(44, 48, 46, -1, 46),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.RUNE_KITESHIELD.getSimilarItems(),
            levels(DEFENCE, 40)),
    RUNE_KITESHIELD_G(
            ArmourItemRef.RUNE_KITESHIELD_G,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(44, 48, 46, -1, 46),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.RUNE_KITESHIELD_G.getSimilarItems(),
            levels(DEFENCE, 40)),
    RUNE_KITESHIELD_T(
            ArmourItemRef.RUNE_KITESHIELD_T,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(44, 48, 46, -1, 46),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.RUNE_KITESHIELD_T.getSimilarItems(),
            levels(DEFENCE, 40)),
    RUNE_SQ_SHIELD(
            ArmourItemRef.RUNE_SQ_SHIELD,
            false,
            new AttackBonus(0, 0, 0, -6, 0),
            new DefenceBonus(38, 40, 36, 0, 38),
            new SkillsBonus(0, 0, 0, 0),
            3.628,
            0,
            ArmourItemRef.RUNE_SQ_SHIELD.getSimilarItems(),
            levels(DEFENCE, 40)),
    RUNEFEST_SHIELD(
            ArmourItemRef.RUNEFEST_SHIELD,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.RUNEFEST_SHIELD.getSimilarItems()),
    SARADOMIN_DHIDE_SHIELD(
            ArmourItemRef.SARADOMIN_DHIDE_SHIELD,
            true,
            new AttackBonus(-15, -15, -11, -10, 7),
            new DefenceBonus(21, 18, 16, 15, 14),
            new SkillsBonus(0, 0, 0, 1),
            8.0,
            0,
            ArmourItemRef.SARADOMIN_DHIDE_SHIELD.getSimilarItems(),
            levels(RANGED, 70, DEFENCE, 40)),
    SARADOMIN_KITESHIELD(
            ArmourItemRef.SARADOMIN_KITESHIELD,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(44, 48, 46, -1, 46),
            new SkillsBonus(0, 0, 0, 1),
            5.443,
            0,
            ArmourItemRef.SARADOMIN_KITESHIELD.getSimilarItems()),
    SNAKESKIN_SHIELD(
            ArmourItemRef.SNAKESKIN_SHIELD,
            true,
            new AttackBonus(-15, -15, -11, -10, 3),
            new DefenceBonus(10, 9, 8, 7, 10),
            new SkillsBonus(0, 0, 0, 0),
            8.0,
            0,
            ArmourItemRef.SNAKESKIN_SHIELD.getSimilarItems(),
            levels(RANGED, 30, DEFENCE, 30)),
    SPECTRAL_SPIRIT_SHIELD(
            ArmourItemRef.SPECTRAL_SPIRIT_SHIELD,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(53, 55, 73, 30, 52),
            new SkillsBonus(0, 0, 0, 3),
            2.0,
            0,
            ArmourItemRef.SPECTRAL_SPIRIT_SHIELD.getSimilarItems(),
            levels(MAGIC, 65, DEFENCE, 75, PRAYER, 70)),
    SPIRIT_SHIELD(
            ArmourItemRef.SPIRIT_SHIELD,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(39, 41, 50, 1, 45),
            new SkillsBonus(0, 0, 0, 1),
            2.0,
            0,
            ArmourItemRef.SPIRIT_SHIELD.getSimilarItems(),
            levels(PRAYER, 55, DEFENCE, 45)),
    STEEL_DEFENDER(
            ArmourItemRef.STEEL_DEFENDER,
            true,
            new AttackBonus(7, 6, 5, -3, -2),
            new DefenceBonus(7, 6, 5, -3, -2),
            new SkillsBonus(1, 0, 0, 0),
            0.453,
            0,
            ArmourItemRef.STEEL_DEFENDER.getSimilarItems()),
    STEEL_KITESHIELD(
            ArmourItemRef.STEEL_KITESHIELD,
            false,
            new AttackBonus(0, 0, 0, -8, -3),
            new DefenceBonus(13, 15, 14, -1, 14),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.STEEL_KITESHIELD.getSimilarItems(),
            levels(DEFENCE, 5)),
    STEEL_KITESHIELD_G(
            ArmourItemRef.STEEL_KITESHIELD_G,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(13, 15, 14, -1, 14),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.STEEL_KITESHIELD_G.getSimilarItems(),
            levels(DEFENCE, 5)),
    STEEL_KITESHIELD_T(
            ArmourItemRef.STEEL_KITESHIELD_T,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(13, 15, 14, -1, 14),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.STEEL_KITESHIELD_T.getSimilarItems(),
            levels(DEFENCE, 5)),
    STEEL_SQ_SHIELD(
            ArmourItemRef.STEEL_SQ_SHIELD,
            false,
            new AttackBonus(0, 0, 0, -6, 0),
            new DefenceBonus(12, 13, 11, 0, 12),
            new SkillsBonus(0, 0, 0, 0),
            3.628,
            0,
            ArmourItemRef.STEEL_SQ_SHIELD.getSimilarItems(),
            levels(DEFENCE, 5)),
    TOKTZ_KET_XIL(
            ArmourItemRef.TOKTZ_KET_XIL,
            true,
            new AttackBonus(0, 0, 0, -12, -8),
            new DefenceBonus(40, 42, 38, 0, 65),
            new SkillsBonus(5, 0, 0, 0),
            3.628,
            0,
            ArmourItemRef.TOKTZ_KET_XIL.getSimilarItems(),
            levels(DEFENCE, 60)),
    TOME_OF_EARTH_CHARGED(
            ArmourItemRef.TOME_OF_EARTH_CHARGED,
            true,
            new AttackBonus(0, 0, 0, 8, 0),
            new DefenceBonus(0, 0, 0, 8, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            0,
            ArmourItemRef.TOME_OF_EARTH_CHARGED.getSimilarItems(),
            levels(MAGIC, 50)),
    TOME_OF_FIRE_CHARGED(
            ArmourItemRef.TOME_OF_FIRE_CHARGED,
            true,
            new AttackBonus(0, 0, 0, 8, 0),
            new DefenceBonus(0, 0, 0, 8, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            0,
            ArmourItemRef.TOME_OF_FIRE_CHARGED.getSimilarItems(),
            levels(MAGIC, 50)),
    TOME_OF_WATER_CHARGED(
            ArmourItemRef.TOME_OF_WATER_CHARGED,
            true,
            new AttackBonus(0, 0, 0, 8, 0),
            new DefenceBonus(0, 0, 0, 8, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            0,
            ArmourItemRef.TOME_OF_WATER_CHARGED.getSimilarItems(),
            levels(MAGIC, 50)),
    TRAINING_SHIELD(
            ArmourItemRef.TRAINING_SHIELD,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(4, 5, 3, 1, 4),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            0,
            ArmourItemRef.TRAINING_SHIELD.getSimilarItems()),
    TWISTED_BUCKLER(
            ArmourItemRef.TWISTED_BUCKLER,
            true,
            new AttackBonus(-7, -8, -7, -10, 18),
            new DefenceBonus(22, 24, 22, 26, 58),
            new SkillsBonus(0, 10, 0, 0),
            5.443,
            0,
            ArmourItemRef.TWISTED_BUCKLER.getSimilarItems(),
            levels(RANGED, 75, DEFENCE, 75)),
    UNHOLY_BOOK(
            ArmourItemRef.UNHOLY_BOOK,
            true,
            new AttackBonus(8, 8, 8, 8, 8),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 5),
            1.0,
            0,
            ArmourItemRef.UNHOLY_BOOK.getSimilarItems(),
            finished(PaidQuest.HORROR_FROM_THE_DEEP)),
    UNHOLY_BOOK_OR(
            ArmourItemRef.UNHOLY_BOOK_OR,
            true,
            new AttackBonus(8, 8, 8, 8, 8),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 5),
            1.0,
            0,
            new GenericItemRef[] {ArmourItemRef.UNHOLY_BOOK_OR},
            finished(PaidQuest.HORROR_FROM_THE_DEEP)),
    UNHOLY_BOOK_27191(
            ArmourItemRef.UNHOLY_BOOK_27191,
            true,
            new AttackBonus(8, 8, 8, 8, 8),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 5),
            1.0,
            0,
            new GenericItemRef[] {ArmourItemRef.UNHOLY_BOOK_27191},
            finished(PaidQuest.HORROR_FROM_THE_DEEP)),
    VS_SHIELD(
            ArmourItemRef.VS_SHIELD,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(27, 31, 29, 5, 29),
            new SkillsBonus(0, 0, 0, 0),
            2.267,
            0,
            ArmourItemRef.VS_SHIELD.getSimilarItems()),
    WHITE_KITESHIELD(
            ArmourItemRef.WHITE_KITESHIELD,
            true,
            new AttackBonus(0, 0, 0, -8, -3),
            new DefenceBonus(17, 19, 18, -1, 18),
            new SkillsBonus(0, 0, 0, 1),
            5.443,
            0,
            ArmourItemRef.WHITE_KITESHIELD.getSimilarItems(),
            finished(PaidQuest.WANTED, DEFENCE, 10)),
    WHITE_SQ_SHIELD(
            ArmourItemRef.WHITE_SQ_SHIELD,
            true,
            new AttackBonus(0, 0, 0, -6, 0),
            new DefenceBonus(15, 16, 14, 0, 15),
            new SkillsBonus(0, 0, 0, 1),
            3.628,
            0,
            ArmourItemRef.WHITE_SQ_SHIELD.getSimilarItems(),
            finished(PaidQuest.WANTED, DEFENCE, 10)),
    WILLOW_SHIELD(
            ArmourItemRef.WILLOW_SHIELD,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(6, 7, 5, 2, 6),
            new SkillsBonus(0, 0, 0, 0),
            3.175,
            0,
            ArmourItemRef.WILLOW_SHIELD.getSimilarItems()),
    WOODEN_SHIELD(
            ArmourItemRef.WOODEN_SHIELD,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(4, 5, 3, 1, 4),
            new SkillsBonus(0, 0, 0, 0),
            2.267,
            0,
            ArmourItemRef.WOODEN_SHIELD.getSimilarItems()),
    WOODEN_SHIELD_G(
            ArmourItemRef.WOODEN_SHIELD_G,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(4, 5, 3, 1, 4),
            new SkillsBonus(0, 0, 0, 0),
            2.267,
            0,
            ArmourItemRef.WOODEN_SHIELD_G.getSimilarItems()),
    YEW_SHIELD(
            ArmourItemRef.YEW_SHIELD,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(8, 9, 7, 3, 8),
            new SkillsBonus(0, 0, 0, 0),
            3.175,
            0,
            ArmourItemRef.YEW_SHIELD.getSimilarItems()),
    ZAMORAK_DHIDE_SHIELD(
            ArmourItemRef.ZAMORAK_DHIDE_SHIELD,
            true,
            new AttackBonus(-15, -15, -11, -10, 7),
            new DefenceBonus(21, 18, 16, 15, 14),
            new SkillsBonus(0, 0, 0, 1),
            8.0,
            0,
            ArmourItemRef.ZAMORAK_DHIDE_SHIELD.getSimilarItems(),
            levels(RANGED, 70, DEFENCE, 40)),
    ZAMORAK_KITESHIELD(
            ArmourItemRef.ZAMORAK_KITESHIELD,
            false,
            new AttackBonus(0, 0, 0, -8, -2),
            new DefenceBonus(44, 48, 46, -1, 46),
            new SkillsBonus(0, 0, 0, 1),
            5.443,
            0,
            ArmourItemRef.ZAMORAK_KITESHIELD.getSimilarItems());

    private final EquipmentSlot slot = EquipmentSlot.SHIELD;
    private final GenericItemRef itemRef;
    private final boolean members;
    private final AttackBonus attackBonus;
    private final DefenceBonus defenceBonus;
    private final SkillsBonus skillsBonus;
    private final double weight;
    private final int attackSpeed;
    private final GenericItemRef[] similarItems;
    private final LocalRequirement requirement;

    ShieldSlotRefs(
            GenericItemRef itemRef,
            boolean members,
            AttackBonus attackBonus,
            DefenceBonus defenceBonus,
            SkillsBonus skillsBonus,
            double weight,
            int attackSpeed,
            GenericItemRef[] similarItems) {
        this(
                itemRef,
                members,
                attackBonus,
                defenceBonus,
                skillsBonus,
                weight,
                attackSpeed,
                similarItems,
                LocalRequirement.none());
    }
}
