package org.dreambot.gamedata.items.equipment;

import static org.dreambot.api.methods.skills.Skill.AGILITY;
import static org.dreambot.api.methods.skills.Skill.ATTACK;
import static org.dreambot.api.methods.skills.Skill.DEFENCE;
import static org.dreambot.api.methods.skills.Skill.MAGIC;
import static org.dreambot.api.methods.skills.Skill.RANGED;
import static org.dreambot.api.methods.skills.Skill.SLAYER;
import static org.dreambot.api.methods.skills.Skill.STRENGTH;
import static org.dreambot.framework.requirements.LocalRequirementHelper.*;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.dreambot.api.methods.container.impl.equipment.EquipmentSlot;
import org.dreambot.api.methods.diary.WesternProvincesDiary;
import org.dreambot.api.methods.quest.book.PaidQuest;
import org.dreambot.framework.requirements.LocalDiaryRequirement.Tier;
import org.dreambot.framework.requirements.LocalRequirement;
import org.dreambot.gamedata.combat.AttackBonus;
import org.dreambot.gamedata.combat.DefenceBonus;
import org.dreambot.gamedata.combat.SkillsBonus;
import org.dreambot.gamedata.items.GenericItemRef;
import org.dreambot.gamedata.items.WeaponItemRef;

@Getter
@AllArgsConstructor
public enum TwoHandedSlotRefs implements EquipmentRefs {
    THIRD_AGE_BOW(
            WeaponItemRef.THIRD_AGE_BOW,
            true,
            new AttackBonus(0, 0, 0, 0, 80),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            3.175,
            4,
            WeaponItemRef.THIRD_AGE_BOW.getSimilarItems()),
    _3RD_AGE_FELLING_AXE(
            WeaponItemRef._3RD_AGE_FELLING_AXE,
            true,
            new AttackBonus(-3, 60, 51, 0, 0),
            new DefenceBonus(0, 1, 0, 0, 0),
            new SkillsBonus(67, 0, 0, 0),
            1.814,
            7,
            WeaponItemRef._3RD_AGE_FELLING_AXE.getSimilarItems()),
    ABYSSAL_BLUDGEON(
            WeaponItemRef.ABYSSAL_BLUDGEON,
            true,
            new AttackBonus(0, 0, 102, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(85, 0, 0, 0),
            6.0,
            4,
            WeaponItemRef.ABYSSAL_BLUDGEON.getSimilarItems(),
            levels(ATTACK, 70, STRENGTH, 70)),
    ADAMANT_2H_SWORD(
            WeaponItemRef.ADAMANT_2H_SWORD,
            false,
            new AttackBonus(-4, 43, 30, -4, 0),
            new DefenceBonus(0, 0, 0, 0, -1),
            new SkillsBonus(44, 0, 0, 0),
            4.082,
            7,
            WeaponItemRef.ADAMANT_2H_SWORD.getSimilarItems(),
            levels(ATTACK, 30)),
    ADAMANT_CLAWS(
            WeaponItemRef.ADAMANT_CLAWS,
            true,
            new AttackBonus(18, 23, -4, 0, 0),
            new DefenceBonus(6, 12, 3, 0, 0),
            new SkillsBonus(24, 0, 0, 0),
            0.907,
            4,
            WeaponItemRef.ADAMANT_CLAWS.getSimilarItems(),
            levels(ATTACK, 30)),
    ADAMANT_FELLING_AXE(
            WeaponItemRef.ADAMANT_FELLING_AXE,
            true,
            new AttackBonus(-3, 27, 24, 0, 0),
            new DefenceBonus(0, 1, 0, 0, 0),
            new SkillsBonus(30, 0, 0, 0),
            1.814,
            7,
            WeaponItemRef.ADAMANT_FELLING_AXE.getSimilarItems()),
    ADAMANT_HALBERD(
            WeaponItemRef.ADAMANT_HALBERD,
            true,
            new AttackBonus(28, 41, 0, -4, 0),
            new DefenceBonus(-1, 3, 4, 0, 0),
            new SkillsBonus(42, 0, 0, 0),
            3.628,
            7,
            WeaponItemRef.ADAMANT_HALBERD.getSimilarItems(),
            levels(ATTACK, 30, STRENGTH, 15)),
    ADAMANT_SPEAR_P_PLUS_PLUS(
            WeaponItemRef.ADAMANT_SPEAR_P_PLUS_PLUS,
            true,
            new AttackBonus(24, 24, 24, 0, 0),
            new DefenceBonus(1, 1, 0, 0, 0),
            new SkillsBonus(28, 0, 0, 0),
            2.721,
            4,
            WeaponItemRef.ADAMANT_SPEAR_P_PLUS_PLUS.getSimilarItems(),
            levels(ATTACK, 30)),
    ADAMANT_SPEAR(
            WeaponItemRef.ADAMANT_SPEAR,
            true,
            new AttackBonus(24, 24, 24, 0, 0),
            new DefenceBonus(1, 1, 0, 0, 0),
            new SkillsBonus(28, 0, 0, 0),
            2.721,
            4,
            WeaponItemRef.ADAMANT_SPEAR.getSimilarItems(),
            levels(ATTACK, 30)),
    ANCIENT_GODSWORD(
            WeaponItemRef.ANCIENT_GODSWORD,
            true,
            new AttackBonus(0, 132, 80, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(132, 0, 0, 8),
            10.0,
            6,
            WeaponItemRef.ANCIENT_GODSWORD.getSimilarItems(),
            levels(ATTACK, 75)),
    ARMADYL_GODSWORD(
            WeaponItemRef.ARMADYL_GODSWORD,
            true,
            new AttackBonus(0, 132, 80, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(132, 0, 0, 8),
            10.0,
            6,
            WeaponItemRef.ARMADYL_GODSWORD.getSimilarItems(),
            levels(ATTACK, 75)),
    BANDOS_GODSWORD(
            WeaponItemRef.BANDOS_GODSWORD,
            true,
            new AttackBonus(0, 132, 80, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(132, 0, 0, 8),
            10.0,
            6,
            WeaponItemRef.BANDOS_GODSWORD.getSimilarItems(),
            levels(ATTACK, 75)),
    BARRELCHEST_ANCHOR(
            WeaponItemRef.BARRELCHEST_ANCHOR,
            true,
            new AttackBonus(-2, 10, 92, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(100, 0, 0, 0),
            30.0,
            6,
            WeaponItemRef.BARRELCHEST_ANCHOR.getSimilarItems(),
            finished(PaidQuest.THE_GREAT_BRAIN_ROBBERY, ATTACK, 60, STRENGTH, 40)),
    BLACK_2H_SWORD(
            WeaponItemRef.BLACK_2H_SWORD,
            false,
            new AttackBonus(-4, 27, 21, -4, 0),
            new DefenceBonus(0, 0, 0, 0, -1),
            new SkillsBonus(26, 0, 0, 0),
            3.628,
            7,
            WeaponItemRef.BLACK_2H_SWORD.getSimilarItems(),
            levels(ATTACK, 10)),
    BLACK_CLAWS(
            WeaponItemRef.BLACK_CLAWS,
            true,
            new AttackBonus(10, 14, -4, 0, 0),
            new DefenceBonus(4, 7, 2, 0, 0),
            new SkillsBonus(14, 0, 0, 0),
            0.907,
            4,
            WeaponItemRef.BLACK_CLAWS.getSimilarItems(),
            levels(ATTACK, 10)),
    BLACK_FELLING_AXE(
            WeaponItemRef.BLACK_FELLING_AXE,
            true,
            new AttackBonus(-2, 10, 8, 0, 0),
            new DefenceBonus(0, 1, 0, 0, 0),
            new SkillsBonus(12, 0, 0, 0),
            1.814,
            7,
            WeaponItemRef.BLACK_FELLING_AXE.getSimilarItems()),
    BLACK_HALBERD(
            WeaponItemRef.BLACK_HALBERD,
            true,
            new AttackBonus(19, 25, 0, -4, 0),
            new DefenceBonus(-1, 2, 3, 0, 0),
            new SkillsBonus(20, 0, 0, 0),
            3.175,
            7,
            WeaponItemRef.BLACK_HALBERD.getSimilarItems(),
            levels(ATTACK, 10, STRENGTH, 5)),
    BLACK_SALAMANDER(
            WeaponItemRef.BLACK_SALAMANDER,
            true,
            new AttackBonus(0, 59, 0, 0, 69),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(71, 0, 0, 0),
            4.0,
            5,
            WeaponItemRef.BLACK_SALAMANDER.getSimilarItems(),
            levels(ATTACK, 70, RANGED, 70, MAGIC, 70)),
    BLACK_SPEAR_P_PLUS_PLUS(
            WeaponItemRef.BLACK_SPEAR_P_PLUS_PLUS,
            true,
            new AttackBonus(15, 15, 15, 0, 0),
            new DefenceBonus(1, 1, 0, 0, 0),
            new SkillsBonus(16, 0, 0, 0),
            2.267,
            4,
            WeaponItemRef.BLACK_SPEAR_P_PLUS_PLUS.getSimilarItems(),
            levels(ATTACK, 10)),
    BLACK_SPEAR(
            WeaponItemRef.BLACK_SPEAR,
            true,
            new AttackBonus(15, 15, 15, 0, 0),
            new DefenceBonus(1, 1, 0, 0, 0),
            new SkillsBonus(16, 0, 0, 0),
            2.267,
            4,
            WeaponItemRef.BLACK_SPEAR.getSimilarItems(),
            levels(ATTACK, 10)),
    BLUE_MOON_SPEAR(
            WeaponItemRef.BLUE_MOON_SPEAR,
            true,
            new AttackBonus(70, 62, 62, 30, 0),
            new DefenceBonus(2, 3, 1, 15, 0),
            new SkillsBonus(71, 0, 5, 0),
            3.0,
            5,
            WeaponItemRef.BLUE_MOON_SPEAR.getSimilarItems(),
            levels(MAGIC, 75, ATTACK, 70)),
    BONE_SHORTBOW(
            WeaponItemRef.BONE_SHORTBOW,
            true,
            new AttackBonus(0, 0, 0, 0, 69),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.36,
            4,
            WeaponItemRef.BONE_SHORTBOW.getSimilarItems()),
    BOW_OF_FAERDHINEN_C(
            WeaponItemRef.BOW_OF_FAERDHINEN_C,
            true,
            new AttackBonus(0, 0, 0, 0, 128),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 106, 0, 0),
            1.5,
            5,
            WeaponItemRef.BOW_OF_FAERDHINEN_C.getSimilarItems(),
            finished(PaidQuest.SONG_OF_THE_ELVES, RANGED, 80, AGILITY, 70)),
    BOW_OF_FAERDHINEN(
            WeaponItemRef.BOW_OF_FAERDHINEN,
            true,
            new AttackBonus(0, 0, 0, 0, 128),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 106, 0, 0),
            1.5,
            5,
            WeaponItemRef.BOW_OF_FAERDHINEN.getSimilarItems(),
            finished(PaidQuest.SONG_OF_THE_ELVES, RANGED, 80, AGILITY, 70)),
    BRONZE_2H_SWORD(
            WeaponItemRef.BRONZE_2H_SWORD,
            false,
            new AttackBonus(-4, 9, 8, -4, 0),
            new DefenceBonus(0, 0, 0, 0, -1),
            new SkillsBonus(10, 0, 0, 0),
            3.628,
            7,
            WeaponItemRef.BRONZE_2H_SWORD.getSimilarItems()),
    BRONZE_CLAWS(
            WeaponItemRef.BRONZE_CLAWS,
            true,
            new AttackBonus(3, 4, -4, 0, 0),
            new DefenceBonus(1, 2, 1, 0, 0),
            new SkillsBonus(5, 0, 0, 0),
            0.907,
            4,
            WeaponItemRef.BRONZE_CLAWS.getSimilarItems()),
    BRONZE_FELLING_AXE(
            WeaponItemRef.BRONZE_FELLING_AXE,
            true,
            new AttackBonus(-3, 6, 3, 0, 0),
            new DefenceBonus(0, 1, 0, 0, 0),
            new SkillsBonus(8, 0, 0, 0),
            1.814,
            7,
            WeaponItemRef.BRONZE_FELLING_AXE.getSimilarItems()),
    BRONZE_HALBERD(
            WeaponItemRef.BRONZE_HALBERD,
            true,
            new AttackBonus(7, 8, 0, -4, 0),
            new DefenceBonus(-1, 1, 2, 0, 0),
            new SkillsBonus(8, 0, 0, 0),
            3.175,
            7,
            WeaponItemRef.BRONZE_HALBERD.getSimilarItems()),
    BRONZE_SPEAR_P_PLUS_PLUS(
            WeaponItemRef.BRONZE_SPEAR_P_PLUS_PLUS,
            true,
            new AttackBonus(5, 5, 5, 0, 0),
            new DefenceBonus(1, 1, 0, 0, 0),
            new SkillsBonus(6, 0, 0, 0),
            2.267,
            4,
            WeaponItemRef.BRONZE_SPEAR_P_PLUS_PLUS.getSimilarItems()),
    BRONZE_SPEAR(
            WeaponItemRef.BRONZE_SPEAR,
            true,
            new AttackBonus(5, 5, 5, 0, 0),
            new DefenceBonus(1, 1, 0, 0, 0),
            new SkillsBonus(6, 0, 0, 0),
            2.267,
            4,
            WeaponItemRef.BRONZE_SPEAR.getSimilarItems()),
    BURNING_CLAWS(
            WeaponItemRef.BURNING_CLAWS,
            true,
            new AttackBonus(43, 54, 0, 0, 0),
            new DefenceBonus(3, 6, 1, 0, 0),
            new SkillsBonus(32, 0, 0, 0),
            0.907,
            4,
            WeaponItemRef.BURNING_CLAWS.getSimilarItems(),
            levels(ATTACK, 60)),
    CAMPHOR_BLOWPIPE_CHARGED(
            WeaponItemRef.CAMPHOR_BLOWPIPE_CHARGED,
            true,
            new AttackBonus(0, 0, 0, 0, 12),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 2, 0, 0),
            0.5,
            3,
            WeaponItemRef.CAMPHOR_BLOWPIPE_CHARGED.getSimilarItems()),
    CLAN_VEXILLUM_BLACK(
            WeaponItemRef.CLAN_VEXILLUM_BLACK,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.814,
            4,
            WeaponItemRef.CLAN_VEXILLUM_BLACK.getSimilarItems()),
    CLUELESS_SCROLL(
            WeaponItemRef.CLUELESS_SCROLL,
            true,
            new AttackBonus(-100, -100, -50, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(-10, 0, 0, 0),
            1.0,
            4,
            WeaponItemRef.CLUELESS_SCROLL.getSimilarItems()),
    COLOSSAL_BLADE(
            WeaponItemRef.COLOSSAL_BLADE,
            true,
            new AttackBonus(-4, 98, 65, -4, 0),
            new DefenceBonus(0, 0, 0, 0, -1),
            new SkillsBonus(100, 0, 0, 0),
            30.0,
            6,
            WeaponItemRef.COLOSSAL_BLADE.getSimilarItems(),
            finished(PaidQuest.SLEEPING_GIANTS, ATTACK, 60)),
    COMP_OGRE_BOW(
            WeaponItemRef.COMP_OGRE_BOW,
            true,
            new AttackBonus(0, 0, 0, 0, 38),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.814,
            5,
            WeaponItemRef.COMP_OGRE_BOW.getSimilarItems()),
    CRAWS_BOW_UNCHARGED(
            WeaponItemRef.CRAWS_BOW_UNCHARGED,
            true,
            new AttackBonus(0, 0, 0, 0, 75),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 60, 0, 0),
            3.175,
            4,
            WeaponItemRef.CRAWS_BOW_UNCHARGED.getSimilarItems()),
    CRYSTAL_BOW(
            WeaponItemRef.CRYSTAL_BOW,
            true,
            new AttackBonus(0, 0, 0, 0, 100),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 78, 0, 0),
            1.814,
            5,
            WeaponItemRef.CRYSTAL_BOW.getSimilarItems()),
    CRYSTAL_FELLING_AXE_ACTIVE(
            WeaponItemRef.CRYSTAL_FELLING_AXE_ACTIVE,
            true,
            new AttackBonus(-3, 60, 51, 0, 0),
            new DefenceBonus(0, 1, 0, 0, 0),
            new SkillsBonus(67, 0, 0, 0),
            1.36,
            7,
            WeaponItemRef.CRYSTAL_FELLING_AXE_ACTIVE.getSimilarItems()),
    CRYSTAL_HALBERD(
            WeaponItemRef.CRYSTAL_HALBERD,
            true,
            new AttackBonus(85, 110, 5, -4, 0),
            new DefenceBonus(-1, 4, 5, 0, 0),
            new SkillsBonus(118, 0, 0, 0),
            1.814,
            7,
            WeaponItemRef.CRYSTAL_HALBERD.getSimilarItems(),
            diary(new WesternProvincesDiary(), Tier.HARD, ATTACK, 70, STRENGTH, 35, AGILITY, 50)),
    CURSED_GOBLIN_BOW(
            WeaponItemRef.CURSED_GOBLIN_BOW,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.814,
            6,
            WeaponItemRef.CURSED_GOBLIN_BOW.getSimilarItems()),
    DARK_BOW(
            WeaponItemRef.DARK_BOW,
            true,
            new AttackBonus(0, 0, 0, 0, 95),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.814,
            9,
            WeaponItemRef.DARK_BOW.getSimilarItems()),
    DHAROKS_GREATAXE(
            WeaponItemRef.DHAROKS_GREATAXE,
            true,
            new AttackBonus(-4, 103, 95, -4, 0),
            new DefenceBonus(0, 0, 0, 0, -1),
            new SkillsBonus(105, 0, 0, 0),
            3.175,
            7,
            WeaponItemRef.DHAROKS_GREATAXE.getSimilarItems(),
            levels(ATTACK, 70, STRENGTH, 70)),
    DINHS_BULWARK(
            WeaponItemRef.DINHS_BULWARK,
            true,
            new AttackBonus(0, 0, 124, 0, 0),
            new DefenceBonus(106, 109, 109, -10, 148),
            new SkillsBonus(38, 0, 0, 0),
            30.0,
            5,
            WeaponItemRef.DINHS_BULWARK.getSimilarItems(),
            levels(ATTACK, 75, DEFENCE, 75)),
    DRAGON_2H_SWORD(
            WeaponItemRef.DRAGON_2H_SWORD,
            true,
            new AttackBonus(-4, 92, 80, -4, 0),
            new DefenceBonus(0, 0, 0, 0, -1),
            new SkillsBonus(93, 0, 0, 0),
            3.628,
            7,
            WeaponItemRef.DRAGON_2H_SWORD.getSimilarItems(),
            levels(ATTACK, 60)),
    DRAGON_CLAWS(
            WeaponItemRef.DRAGON_CLAWS,
            true,
            new AttackBonus(41, 57, -4, 0, 0),
            new DefenceBonus(13, 26, 7, 0, 0),
            new SkillsBonus(56, 0, 0, 0),
            0.907,
            4,
            WeaponItemRef.DRAGON_CLAWS.getSimilarItems(),
            levels(ATTACK, 60)),
    DRAGON_FELLING_AXE(
            WeaponItemRef.DRAGON_FELLING_AXE,
            true,
            new AttackBonus(-3, 60, 51, 0, 0),
            new DefenceBonus(0, 1, 0, 0, 0),
            new SkillsBonus(67, 0, 0, 0),
            1.814,
            7,
            WeaponItemRef.DRAGON_FELLING_AXE.getSimilarItems()),
    DRAGON_HALBERD(
            WeaponItemRef.DRAGON_HALBERD,
            true,
            new AttackBonus(70, 95, 0, -4, 0),
            new DefenceBonus(-1, 4, 5, 0, 0),
            new SkillsBonus(89, 0, 0, 0),
            3.175,
            7,
            WeaponItemRef.DRAGON_HALBERD.getSimilarItems(),
            finished(PaidQuest.REGICIDE, ATTACK, 60, STRENGTH, 30)),
    DRAGON_SPEAR_P_PLUS_PLUS(
            WeaponItemRef.DRAGON_SPEAR_P_PLUS_PLUS,
            true,
            new AttackBonus(55, 55, 55, 0, 0),
            new DefenceBonus(5, 5, 5, 5, 5),
            new SkillsBonus(60, 0, 0, 0),
            2.267,
            4,
            WeaponItemRef.DRAGON_SPEAR_P_PLUS_PLUS.getSimilarItems(),
            levels(ATTACK, 60)),
    DRAGON_SPEAR(
            WeaponItemRef.DRAGON_SPEAR,
            true,
            new AttackBonus(55, 55, 55, 0, 0),
            new DefenceBonus(5, 5, 5, 5, 5),
            new SkillsBonus(60, 0, 0, 0),
            2.267,
            4,
            WeaponItemRef.DRAGON_SPEAR.getSimilarItems(),
            levels(ATTACK, 60)),
    DUAL_MACUAHUITL(
            WeaponItemRef.DUAL_MACUAHUITL,
            true,
            new AttackBonus(115, -4, 121, -4, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(81, 0, 0, 0),
            3.628,
            4,
            WeaponItemRef.DUAL_MACUAHUITL.getSimilarItems(),
            levels(ATTACK, 70, STRENGTH, 75)),
    DUAL_SAI(
            WeaponItemRef.DUAL_SAI,
            true,
            new AttackBonus(11, 8, -4, -4, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(14, 0, 0, 0),
            1.36,
            5,
            WeaponItemRef.DUAL_SAI.getSimilarItems()),
    EARTHBOUND_TECPATL(
            WeaponItemRef.EARTHBOUND_TECPATL,
            true,
            new AttackBonus(72, 11, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(64, 0, 0, 2),
            1.814,
            4,
            WeaponItemRef.EARTHBOUND_TECPATL.getSimilarItems()),
    ECLIPSE_ATLATL(
            WeaponItemRef.ECLIPSE_ATLATL,
            true,
            new AttackBonus(0, 0, 0, 0, 87),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(40, 0, 0, 0),
            3.628,
            4,
            WeaponItemRef.ECLIPSE_ATLATL.getSimilarItems()),
    ELDER_MAUL(
            WeaponItemRef.ELDER_MAUL,
            true,
            new AttackBonus(0, 0, 135, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(147, 0, 0, 0),
            5.443,
            6,
            WeaponItemRef.ELDER_MAUL.getSimilarItems(),
            levels(ATTACK, 75, STRENGTH, 75)),
    GADDERHAMMER(
            WeaponItemRef.GADDERHAMMER,
            true,
            new AttackBonus(-4, -4, 35, -4, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(35, 0, 0, 0),
            1.814,
            5,
            WeaponItemRef.GADDERHAMMER.getSimilarItems()),
    GILDED_2H_SWORD(
            WeaponItemRef.GILDED_2H_SWORD,
            false,
            new AttackBonus(-4, 69, 50, -4, 0),
            new DefenceBonus(0, 0, 0, 0, -1),
            new SkillsBonus(70, 0, 0, 0),
            3.628,
            7,
            WeaponItemRef.GILDED_2H_SWORD.getSimilarItems()),
    GILDED_SPADE(
            WeaponItemRef.GILDED_SPADE,
            false,
            new AttackBonus(-100, -100, -50, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(-10, 0, 0, 0),
            3.0,
            4,
            WeaponItemRef.GILDED_SPADE.getSimilarItems()),
    GILDED_SPEAR(
            WeaponItemRef.GILDED_SPEAR,
            true,
            new AttackBonus(36, 36, 36, 0, 0),
            new DefenceBonus(1, 1, 0, 0, 0),
            new SkillsBonus(42, 0, 0, 0),
            2.267,
            4,
            WeaponItemRef.GILDED_SPEAR.getSimilarItems()),
    GLACIAL_TEMOTLI(
            WeaponItemRef.GLACIAL_TEMOTLI,
            true,
            new AttackBonus(11, 0, 72, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(64, 0, 0, 2),
            1.814,
            4,
            WeaponItemRef.GLACIAL_TEMOTLI.getSimilarItems()),
    GOBLIN_PAINT_CANNON(
            WeaponItemRef.GOBLIN_PAINT_CANNON,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            3,
            WeaponItemRef.GOBLIN_PAINT_CANNON.getSimilarItems()),
    GRANITE_MAUL(
            WeaponItemRef.GRANITE_MAUL,
            true,
            new AttackBonus(0, 0, 81, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(79, 0, 0, 0),
            4.535,
            7,
            WeaponItemRef.GRANITE_MAUL.getSimilarItems(),
            levels(DEFENCE, 50, STRENGTH, 50)),
    GUTHANS_WARSPEAR(
            WeaponItemRef.GUTHANS_WARSPEAR,
            true,
            new AttackBonus(75, 75, 75, 0, 0),
            new DefenceBonus(7, 7, 7, 0, 0),
            new SkillsBonus(75, 0, 0, 0),
            2.267,
            5,
            WeaponItemRef.GUTHANS_WARSPEAR.getSimilarItems(),
            levels(ATTACK, 70)),
    GUTHIX_MJOLNIR(
            WeaponItemRef.GUTHIX_MJOLNIR,
            true,
            new AttackBonus(0, 0, 11, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(14, 0, 0, 0),
            2.267,
            6,
            WeaponItemRef.GUTHIX_MJOLNIR.getSimilarItems()),
    HEAVY_BALLISTA(
            WeaponItemRef.HEAVY_BALLISTA,
            true,
            new AttackBonus(0, 0, 0, 0, 125),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 15, 0, 0),
            6.0,
            7,
            WeaponItemRef.HEAVY_BALLISTA.getSimilarItems()),
    HEAVY_CASKET(
            WeaponItemRef.HEAVY_CASKET,
            true,
            new AttackBonus(-4, -4, 11, -4, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(9, 0, 0, 0),
            15.0,
            6,
            WeaponItemRef.HEAVY_CASKET.getSimilarItems()),
    HILL_GIANT_CLUB(
            WeaponItemRef.HILL_GIANT_CLUB,
            false,
            new AttackBonus(-4, 50, 65, -4, 0),
            new DefenceBonus(0, 0, 0, 0, -1),
            new SkillsBonus(70, 0, 0, 0),
            3.628,
            7,
            WeaponItemRef.HILL_GIANT_CLUB.getSimilarItems()),
    IRON_2H_SWORD(
            WeaponItemRef.IRON_2H_SWORD,
            false,
            new AttackBonus(-4, 13, 10, -4, 0),
            new DefenceBonus(0, 0, 0, 0, -1),
            new SkillsBonus(14, 0, 0, 0),
            3.628,
            7,
            WeaponItemRef.IRON_2H_SWORD.getSimilarItems()),
    IRON_CLAWS(
            WeaponItemRef.IRON_CLAWS,
            true,
            new AttackBonus(4, 6, -4, 0, 0),
            new DefenceBonus(2, 3, 1, 0, 0),
            new SkillsBonus(7, 0, 0, 0),
            0.907,
            4,
            WeaponItemRef.IRON_CLAWS.getSimilarItems()),
    IRON_FELLING_AXE(
            WeaponItemRef.IRON_FELLING_AXE,
            true,
            new AttackBonus(-3, 8, 4, 0, 0),
            new DefenceBonus(0, 1, 0, 0, 0),
            new SkillsBonus(11, 0, 0, 0),
            1.814,
            7,
            WeaponItemRef.IRON_FELLING_AXE.getSimilarItems()),
    IRON_HALBERD(
            WeaponItemRef.IRON_HALBERD,
            true,
            new AttackBonus(9, 12, 0, -4, 0),
            new DefenceBonus(-1, 1, 2, 0, 0),
            new SkillsBonus(12, 0, 0, 0),
            3.175,
            7,
            WeaponItemRef.IRON_HALBERD.getSimilarItems()),
    IRON_SPEAR_P_PLUS_PLUS(
            WeaponItemRef.IRON_SPEAR_P_PLUS_PLUS,
            true,
            new AttackBonus(8, 8, 8, 0, 0),
            new DefenceBonus(1, 1, 0, 0, 0),
            new SkillsBonus(10, 0, 0, 0),
            2.267,
            4,
            WeaponItemRef.IRON_SPEAR_P_PLUS_PLUS.getSimilarItems()),
    IRON_SPEAR(
            WeaponItemRef.IRON_SPEAR,
            true,
            new AttackBonus(8, 8, 8, 0, 0),
            new DefenceBonus(1, 1, 0, 0, 0),
            new SkillsBonus(10, 0, 0, 0),
            2.267,
            4,
            WeaponItemRef.IRON_SPEAR.getSimilarItems()),
    IRONWOOD_BLOWPIPE_CHARGED(
            WeaponItemRef.IRONWOOD_BLOWPIPE_CHARGED,
            true,
            new AttackBonus(0, 0, 0, 0, 16),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 4, 0, 0),
            0.5,
            3,
            WeaponItemRef.IRONWOOD_BLOWPIPE_CHARGED.getSimilarItems()),
    KARILS_CROSSBOW(
            WeaponItemRef.KARILS_CROSSBOW,
            true,
            new AttackBonus(0, 0, 0, 0, 84),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            3.628,
            4,
            WeaponItemRef.KARILS_CROSSBOW.getSimilarItems(),
            levels(RANGED, 70)),
    KATANA(
            WeaponItemRef.KATANA,
            true,
            new AttackBonus(7, 45, 0, 0, 0),
            new DefenceBonus(3, 7, 7, 0, -3),
            new SkillsBonus(40, 0, 0, 0),
            0.453,
            4,
            WeaponItemRef.KATANA.getSimilarItems()),
    LARGE_SPADE(
            WeaponItemRef.LARGE_SPADE,
            true,
            new AttackBonus(-100, -100, -50, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(-10, 0, 0, 0),
            3.0,
            4,
            WeaponItemRef.LARGE_SPADE.getSimilarItems()),
    LEAF_BLADED_SPEAR(
            WeaponItemRef.LEAF_BLADED_SPEAR,
            true,
            new AttackBonus(47, 42, 36, 0, 0),
            new DefenceBonus(1, 1, 0, 0, 0),
            new SkillsBonus(50, 0, 0, 0),
            2.267,
            5,
            WeaponItemRef.LEAF_BLADED_SPEAR.getSimilarItems(),
            levels(ATTACK, 50, SLAYER, 55)),
    LIGHT_BALLISTA(
            WeaponItemRef.LIGHT_BALLISTA,
            true,
            new AttackBonus(0, 0, 0, 0, 110),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            3.0,
            7,
            WeaponItemRef.LIGHT_BALLISTA.getSimilarItems()),
    LONGBOW(
            WeaponItemRef.LONGBOW,
            false,
            new AttackBonus(0, 0, 0, 0, 8),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.814,
            6,
            WeaponItemRef.LONGBOW.getSimilarItems()),
    MAGIC_COMP_BOW(
            WeaponItemRef.MAGIC_COMP_BOW,
            true,
            new AttackBonus(0, 0, 0, 0, 71),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.8,
            5,
            WeaponItemRef.MAGIC_COMP_BOW.getSimilarItems()),
    MAGIC_LONGBOW(
            WeaponItemRef.MAGIC_LONGBOW,
            true,
            new AttackBonus(0, 0, 0, 0, 69),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.814,
            6,
            WeaponItemRef.MAGIC_LONGBOW.getSimilarItems()),
    MAGIC_SHORTBOW(
            WeaponItemRef.MAGIC_SHORTBOW,
            true,
            new AttackBonus(0, 0, 0, 0, 69),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.36,
            4,
            WeaponItemRef.MAGIC_SHORTBOW.getSimilarItems()),
    MAGIC_SHORTBOW_I(
            WeaponItemRef.MAGIC_SHORTBOW_I,
            true,
            new AttackBonus(0, 0, 0, 0, 75),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.36,
            4,
            WeaponItemRef.MAGIC_SHORTBOW_I.getSimilarItems()),
    MAPLE_LONGBOW(
            WeaponItemRef.MAPLE_LONGBOW,
            false,
            new AttackBonus(0, 0, 0, 0, 29),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.814,
            6,
            WeaponItemRef.MAPLE_LONGBOW.getSimilarItems()),
    MAPLE_SHORTBOW(
            WeaponItemRef.MAPLE_SHORTBOW,
            false,
            new AttackBonus(0, 0, 0, 0, 29),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.36,
            4,
            WeaponItemRef.MAPLE_SHORTBOW.getSimilarItems()),
    MERFOLK_TRIDENT(
            WeaponItemRef.MERFOLK_TRIDENT,
            true,
            new AttackBonus(8, 8, 8, 0, 0),
            new DefenceBonus(1, 1, 0, 0, 0),
            new SkillsBonus(4, 0, 0, 0),
            0.907,
            5,
            WeaponItemRef.MERFOLK_TRIDENT.getSimilarItems()),
    MITHRIL_2H_SWORD(
            WeaponItemRef.MITHRIL_2H_SWORD,
            false,
            new AttackBonus(-4, 30, 24, -4, 0),
            new DefenceBonus(0, 0, 0, 0, -1),
            new SkillsBonus(31, 0, 0, 0),
            3.175,
            7,
            WeaponItemRef.MITHRIL_2H_SWORD.getSimilarItems(),
            levels(ATTACK, 20)),
    MITHRIL_CLAWS(
            WeaponItemRef.MITHRIL_CLAWS,
            true,
            new AttackBonus(11, 16, -4, 0, 0),
            new DefenceBonus(4, 8, 2, 0, 0),
            new SkillsBonus(17, 0, 0, 0),
            0.907,
            4,
            WeaponItemRef.MITHRIL_CLAWS.getSimilarItems(),
            levels(ATTACK, 20)),
    MITHRIL_FELLING_AXE(
            WeaponItemRef.MITHRIL_FELLING_AXE,
            true,
            new AttackBonus(-3, 19, 16, 0, 0),
            new DefenceBonus(0, 1, 0, 0, 0),
            new SkillsBonus(20, 0, 0, 0),
            1.814,
            7,
            WeaponItemRef.MITHRIL_FELLING_AXE.getSimilarItems()),
    MITHRIL_HALBERD(
            WeaponItemRef.MITHRIL_HALBERD,
            true,
            new AttackBonus(22, 28, 0, -4, 0),
            new DefenceBonus(-1, 2, 4, 0, 0),
            new SkillsBonus(29, 0, 0, 0),
            2.721,
            7,
            WeaponItemRef.MITHRIL_HALBERD.getSimilarItems(),
            levels(ATTACK, 20, STRENGTH, 10)),
    MITHRIL_SPEAR_P_PLUS_PLUS(
            WeaponItemRef.MITHRIL_SPEAR_P_PLUS_PLUS,
            true,
            new AttackBonus(17, 17, 17, 0, 0),
            new DefenceBonus(1, 1, 0, 0, 0),
            new SkillsBonus(18, 0, 0, 0),
            1.814,
            4,
            WeaponItemRef.MITHRIL_SPEAR_P_PLUS_PLUS.getSimilarItems(),
            levels(ATTACK, 20)),
    MITHRIL_SPEAR(
            WeaponItemRef.MITHRIL_SPEAR,
            true,
            new AttackBonus(17, 17, 17, 0, 0),
            new DefenceBonus(1, 1, 0, 0, 0),
            new SkillsBonus(18, 0, 0, 0),
            1.814,
            4,
            WeaponItemRef.MITHRIL_SPEAR.getSimilarItems(),
            levels(ATTACK, 20)),
    NOXIOUS_HALBERD(
            WeaponItemRef.NOXIOUS_HALBERD,
            true,
            new AttackBonus(80, 132, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(142, 0, 0, 0),
            2.721,
            5,
            WeaponItemRef.NOXIOUS_HALBERD.getSimilarItems(),
            levels(ATTACK, 80)),
    NUNCHAKU(
            WeaponItemRef.NUNCHAKU,
            true,
            new AttackBonus(-4, -4, 11, -4, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(14, 0, 0, 0),
            1.36,
            5,
            WeaponItemRef.NUNCHAKU.getSimilarItems()),
    OAK_LONGBOW(
            WeaponItemRef.OAK_LONGBOW,
            false,
            new AttackBonus(0, 0, 0, 0, 14),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            2.267,
            6,
            WeaponItemRef.OAK_LONGBOW.getSimilarItems()),
    OAK_SHORTBOW(
            WeaponItemRef.OAK_SHORTBOW,
            false,
            new AttackBonus(0, 0, 0, 0, 14),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.814,
            4,
            WeaponItemRef.OAK_SHORTBOW.getSimilarItems()),
    OGRE_BOW(
            WeaponItemRef.OGRE_BOW,
            true,
            new AttackBonus(0, 0, 0, 0, 38),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.814,
            8,
            WeaponItemRef.OGRE_BOW.getSimilarItems()),
    ORANGE_SALAMANDER(
            WeaponItemRef.ORANGE_SALAMANDER,
            true,
            new AttackBonus(0, 19, 0, 0, 29),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(31, 0, 0, 0),
            4.0,
            5,
            WeaponItemRef.ORANGE_SALAMANDER.getSimilarItems(),
            levels(ATTACK, 50, RANGED, 50, MAGIC, 50)),
    RAIN_BOW(
            WeaponItemRef.RAIN_BOW,
            true,
            new AttackBonus(0, 0, 0, 0, 8),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.36,
            4,
            WeaponItemRef.RAIN_BOW.getSimilarItems()),
    RAT_POLE_EMPTY(
            WeaponItemRef.RAT_POLE_EMPTY,
            true,
            new AttackBonus(0, -1, 7, 4, 0),
            new DefenceBonus(2, 3, 1, 4, 0),
            new SkillsBonus(3, 0, 0, 0),
            2.267,
            5,
            WeaponItemRef.RAT_POLE_EMPTY.getSimilarItems()),
    RED_SALAMANDER(
            WeaponItemRef.RED_SALAMANDER,
            true,
            new AttackBonus(0, 37, 0, 0, 47),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(49, 0, 0, 0),
            4.0,
            5,
            WeaponItemRef.RED_SALAMANDER.getSimilarItems(),
            levels(ATTACK, 60, RANGED, 60, MAGIC, 60)),
    ROSEWOOD_BLOWPIPE(
            WeaponItemRef.ROSEWOOD_BLOWPIPE,
            true,
            new AttackBonus(0, 0, 0, 0, 22),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 6, 0, 0),
            0.5,
            3,
            WeaponItemRef.ROSEWOOD_BLOWPIPE.getSimilarItems()),
    RUNE_2H_SWORD(
            WeaponItemRef.RUNE_2H_SWORD,
            false,
            new AttackBonus(-4, 69, 50, -4, 0),
            new DefenceBonus(0, 0, 0, 0, -1),
            new SkillsBonus(70, 0, 0, 0),
            3.628,
            7,
            WeaponItemRef.RUNE_2H_SWORD.getSimilarItems(),
            levels(ATTACK, 40)),
    RUNE_CLAWS(
            WeaponItemRef.RUNE_CLAWS,
            true,
            new AttackBonus(26, 38, -4, 0, 0),
            new DefenceBonus(10, 19, 5, 0, 0),
            new SkillsBonus(39, 0, 0, 0),
            0.907,
            4,
            WeaponItemRef.RUNE_CLAWS.getSimilarItems(),
            levels(ATTACK, 40)),
    RUNE_FELLING_AXE(
            WeaponItemRef.RUNE_FELLING_AXE,
            true,
            new AttackBonus(-3, 41, 38, 0, 0),
            new DefenceBonus(0, 1, 0, 0, 0),
            new SkillsBonus(46, 0, 0, 0),
            1.814,
            7,
            WeaponItemRef.RUNE_FELLING_AXE.getSimilarItems()),
    RUNE_HALBERD(
            WeaponItemRef.RUNE_HALBERD,
            true,
            new AttackBonus(48, 67, 0, -4, 0),
            new DefenceBonus(-1, 4, 5, 0, 0),
            new SkillsBonus(68, 0, 0, 0),
            3.175,
            7,
            WeaponItemRef.RUNE_HALBERD.getSimilarItems(),
            levels(ATTACK, 40, STRENGTH, 20)),
    RUNE_SPEAR_P_PLUS_PLUS(
            WeaponItemRef.RUNE_SPEAR_P_PLUS_PLUS,
            true,
            new AttackBonus(36, 36, 36, 0, 0),
            new DefenceBonus(1, 1, 0, 0, 0),
            new SkillsBonus(42, 0, 0, 0),
            2.267,
            4,
            WeaponItemRef.RUNE_SPEAR_P_PLUS_PLUS.getSimilarItems(),
            levels(ATTACK, 40)),
    RUNE_SPEAR(
            WeaponItemRef.RUNE_SPEAR,
            true,
            new AttackBonus(36, 36, 36, 0, 0),
            new DefenceBonus(1, 1, 0, 0, 0),
            new SkillsBonus(42, 0, 0, 0),
            2.267,
            4,
            WeaponItemRef.RUNE_SPEAR.getSimilarItems(),
            levels(ATTACK, 40)),
    SANGUINE_SCYTHE_OF_VITUR_CHARGED(
            WeaponItemRef.SANGUINE_SCYTHE_OF_VITUR_CHARGED,
            true,
            new AttackBonus(70, 125, 30, -6, 0),
            new DefenceBonus(-2, 8, 10, 0, 0),
            new SkillsBonus(75, 0, 0, 0),
            3.175,
            5,
            WeaponItemRef.SANGUINE_SCYTHE_OF_VITUR_CHARGED.getSimilarItems(),
            levels(ATTACK, 80, STRENGTH, 90)),
    SARADOMIN_GODSWORD(
            WeaponItemRef.SARADOMIN_GODSWORD,
            true,
            new AttackBonus(0, 132, 80, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(132, 0, 0, 8),
            10.0,
            6,
            WeaponItemRef.SARADOMIN_GODSWORD.getSimilarItems(),
            levels(ATTACK, 75)),
    SARADOMIN_MJOLNIR(
            WeaponItemRef.SARADOMIN_MJOLNIR,
            true,
            new AttackBonus(0, 0, 11, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(14, 0, 0, 0),
            2.267,
            6,
            WeaponItemRef.SARADOMIN_MJOLNIR.getSimilarItems()),
    SARADOMIN_SWORD(
            WeaponItemRef.SARADOMIN_SWORD,
            true,
            new AttackBonus(0, 82, 60, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(82, 0, 0, 2),
            3.0,
            4,
            WeaponItemRef.SARADOMIN_SWORD.getSimilarItems(),
            levels(ATTACK, 70)),
    SARADOMINS_BLESSED_SWORD(
            WeaponItemRef.SARADOMINS_BLESSED_SWORD,
            true,
            new AttackBonus(0, 100, 60, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(88, 0, 0, 2),
            3.0,
            4,
            WeaponItemRef.SARADOMINS_BLESSED_SWORD.getSimilarItems(),
            levels(ATTACK, 75)),
    SCORCHING_BOW(
            WeaponItemRef.SCORCHING_BOW,
            true,
            new AttackBonus(0, 0, 0, 0, 124),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 40, 0, 0),
            1.814,
            5,
            WeaponItemRef.SCORCHING_BOW.getSimilarItems()),
    SCYTHE_OF_VITUR_CHARGED(
            WeaponItemRef.SCYTHE_OF_VITUR_CHARGED,
            true,
            new AttackBonus(70, 125, 30, -6, 0),
            new DefenceBonus(-2, 8, 10, 0, 0),
            new SkillsBonus(75, 0, 0, 0),
            3.175,
            5,
            WeaponItemRef.SCYTHE_OF_VITUR_CHARGED.getSimilarItems(),
            levels(ATTACK, 80, STRENGTH, 90)),
    SEERCULL(
            WeaponItemRef.SEERCULL,
            true,
            new AttackBonus(0, 0, 0, 0, 69),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.36,
            5,
            WeaponItemRef.SEERCULL.getSimilarItems()),
    SHADOW_SWORD(
            WeaponItemRef.SHADOW_SWORD,
            true,
            new AttackBonus(-4, 27, 21, 4, 0),
            new DefenceBonus(0, 0, 0, 4, -1),
            new SkillsBonus(26, 0, 0, 0),
            3.628,
            6,
            WeaponItemRef.SHADOW_SWORD.getSimilarItems()),
    SHORTBOW(
            WeaponItemRef.SHORTBOW,
            false,
            new AttackBonus(0, 0, 0, 0, 8),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.36,
            4,
            WeaponItemRef.SHORTBOW.getSimilarItems()),
    SIGNED_OAK_BOW(
            WeaponItemRef.SIGNED_OAK_BOW,
            true,
            new AttackBonus(0, 0, 0, 0, 14),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            2.267,
            6,
            WeaponItemRef.SIGNED_OAK_BOW.getSimilarItems()),
    SOULREAPER_AXE(
            WeaponItemRef.SOULREAPER_AXE,
            true,
            new AttackBonus(28, 134, 66, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(121, 0, 0, 0),
            2.825,
            5,
            WeaponItemRef.SOULREAPER_AXE.getSimilarItems(),
            levels(ATTACK, 80, STRENGTH, 80)),
    SPATULA(
            WeaponItemRef.SPATULA,
            true,
            new AttackBonus(-4, 27, 21, -4, 0),
            new DefenceBonus(0, 0, 0, 0, -1),
            new SkillsBonus(26, 0, 0, 0),
            3.628,
            7,
            WeaponItemRef.SPATULA.getSimilarItems()),
    STEEL_2H_SWORD(
            WeaponItemRef.STEEL_2H_SWORD,
            false,
            new AttackBonus(-4, 21, 16, -4, 0),
            new DefenceBonus(0, 0, 0, 0, -1),
            new SkillsBonus(22, 0, 0, 0),
            3.628,
            7,
            WeaponItemRef.STEEL_2H_SWORD.getSimilarItems(),
            levels(ATTACK, 5)),
    STEEL_CLAWS(
            WeaponItemRef.STEEL_CLAWS,
            true,
            new AttackBonus(8, 11, -4, 0, 0),
            new DefenceBonus(3, 6, 2, 0, 0),
            new SkillsBonus(12, 0, 0, 0),
            0.907,
            4,
            WeaponItemRef.STEEL_CLAWS.getSimilarItems(),
            levels(ATTACK, 5)),
    STEEL_FELLING_AXE(
            WeaponItemRef.STEEL_FELLING_AXE,
            true,
            new AttackBonus(-3, 12, 9, 0, 0),
            new DefenceBonus(0, 1, 0, 0, 0),
            new SkillsBonus(14, 0, 0, 0),
            1.814,
            7,
            WeaponItemRef.STEEL_FELLING_AXE.getSimilarItems()),
    STEEL_HALBERD(
            WeaponItemRef.STEEL_HALBERD,
            true,
            new AttackBonus(14, 19, 0, -4, 0),
            new DefenceBonus(-1, 1, 2, 0, 0),
            new SkillsBonus(20, 0, 0, 0),
            3.175,
            7,
            WeaponItemRef.STEEL_HALBERD.getSimilarItems(),
            levels(ATTACK, 5, STRENGTH, 2)),
    STEEL_SPEAR_P_PLUS_PLUS(
            WeaponItemRef.STEEL_SPEAR_P_PLUS_PLUS,
            true,
            new AttackBonus(12, 12, 12, 0, 0),
            new DefenceBonus(1, 1, 0, 0, 0),
            new SkillsBonus(12, 0, 0, 0),
            2.267,
            4,
            WeaponItemRef.STEEL_SPEAR_P_PLUS_PLUS.getSimilarItems(),
            levels(ATTACK, 5)),
    STEEL_SPEAR(
            WeaponItemRef.STEEL_SPEAR,
            true,
            new AttackBonus(12, 12, 12, 0, 0),
            new DefenceBonus(1, 1, 0, 0, 0),
            new SkillsBonus(12, 0, 0, 0),
            2.267,
            4,
            WeaponItemRef.STEEL_SPEAR.getSimilarItems(),
            levels(ATTACK, 5)),
    SULPHUR_BLADES(
            WeaponItemRef.SULPHUR_BLADES,
            true,
            new AttackBonus(11, 72, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(64, 0, 0, 0),
            1.814,
            4,
            WeaponItemRef.SULPHUR_BLADES.getSimilarItems(),
            levels(ATTACK, 55)),
    SWAMP_LIZARD(
            WeaponItemRef.SWAMP_LIZARD,
            true,
            new AttackBonus(0, 10, 0, 0, 20),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(22, 0, 0, 0),
            4.0,
            5,
            WeaponItemRef.SWAMP_LIZARD.getSimilarItems(),
            levels(ATTACK, 30, RANGED, 30, MAGIC, 30)),
    TECU_SALAMANDER(
            WeaponItemRef.TECU_SALAMANDER,
            true,
            new AttackBonus(0, 77, 0, 0, 87),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(91, 0, 0, 0),
            6.0,
            5,
            WeaponItemRef.TECU_SALAMANDER.getSimilarItems(),
            levels(ATTACK, 80, RANGED, 80, MAGIC, 80)),
    TOKTZ_MEJ_TAL(
            WeaponItemRef.TOKTZ_MEJ_TAL,
            true,
            new AttackBonus(15, -1, 55, 15, 0),
            new DefenceBonus(10, 15, 5, 15, 0),
            new SkillsBonus(55, 0, 0, 5),
            1.814,
            6,
            WeaponItemRef.TOKTZ_MEJ_TAL.getSimilarItems(),
            levels(ATTACK, 60, MAGIC, 60)),
    TORAGS_HAMMERS(
            WeaponItemRef.TORAGS_HAMMERS,
            true,
            new AttackBonus(-4, -4, 85, -4, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(72, 0, 0, 0),
            3.628,
            5,
            WeaponItemRef.TORAGS_HAMMERS.getSimilarItems(),
            levels(ATTACK, 70, STRENGTH, 70)),
    TOXIC_BLOWPIPE(
            WeaponItemRef.TOXIC_BLOWPIPE,
            true,
            new AttackBonus(0, 0, 0, 0, 30),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 20, 0, 0),
            0.5,
            3,
            WeaponItemRef.TOXIC_BLOWPIPE.getSimilarItems()),
    TRAINING_BOW(
            WeaponItemRef.TRAINING_BOW,
            false,
            new AttackBonus(0, 0, 0, 0, 8),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.36,
            4,
            WeaponItemRef.TRAINING_BOW.getSimilarItems()),
    TUMEKENS_SHADOW_CHARGED(
            WeaponItemRef.TUMEKENS_SHADOW_CHARGED,
            true,
            new AttackBonus(0, 0, 0, 35, 0),
            new DefenceBonus(0, 0, 0, 20, 0),
            new SkillsBonus(0, 0, 0, 1),
            5.0,
            5,
            WeaponItemRef.TUMEKENS_SHADOW_CHARGED.getSimilarItems(),
            levels(MAGIC, 85)),
    TWISTED_BOW(
            WeaponItemRef.TWISTED_BOW,
            true,
            new AttackBonus(0, 0, 0, 0, 70),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 20, 0, 0),
            1.814,
            6,
            WeaponItemRef.TWISTED_BOW.getSimilarItems()),
    TZHAAR_KET_OM(
            WeaponItemRef.TZHAAR_KET_OM,
            true,
            new AttackBonus(0, 0, 80, -4, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(85, 0, 0, 0),
            3.628,
            7,
            WeaponItemRef.TZHAAR_KET_OM.getSimilarItems(),
            levels(STRENGTH, 60)),
    TZHAAR_KET_OM_T(
            WeaponItemRef.TZHAAR_KET_OM_T,
            true,
            new AttackBonus(0, 0, 80, -4, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(85, 0, 0, 0),
            3.628,
            7,
            WeaponItemRef.TZHAAR_KET_OM_T.getSimilarItems(),
            levels(STRENGTH, 60)),
    VENATOR_BOW(
            WeaponItemRef.VENATOR_BOW,
            true,
            new AttackBonus(0, 0, 0, 0, 90),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 25, 0, 0),
            4.5,
            5,
            WeaponItemRef.VENATOR_BOW.getSimilarItems()),
    VERACS_FLAIL_UNDAMAGED(
            WeaponItemRef.VERACS_FLAIL_UNDAMAGED,
            true,
            new AttackBonus(68, -2, 82, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(72, 0, 0, 6),
            2.267,
            5,
            WeaponItemRef.VERACS_FLAIL_UNDAMAGED.getSimilarItems(),
            levels(ATTACK, 70)),
    WEBWEAVER_BOW(
            WeaponItemRef.WEBWEAVER_BOW,
            true,
            new AttackBonus(0, 0, 0, 0, 85),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 65, 0, 0),
            3.175,
            4,
            WeaponItemRef.WEBWEAVER_BOW.getSimilarItems()),
    WHITE_2H_SWORD(
            WeaponItemRef.WHITE_2H_SWORD,
            true,
            new AttackBonus(-4, 27, 21, -4, 0),
            new DefenceBonus(0, 0, 0, 0, -1),
            new SkillsBonus(26, 0, 0, 1),
            3.628,
            7,
            WeaponItemRef.WHITE_2H_SWORD.getSimilarItems(),
            finished(PaidQuest.WANTED, ATTACK, 10)),
    WHITE_CLAWS(
            WeaponItemRef.WHITE_CLAWS,
            true,
            new AttackBonus(10, 14, -4, 0, 0),
            new DefenceBonus(4, 7, 2, 0, 0),
            new SkillsBonus(14, 0, 0, 1),
            0.907,
            4,
            WeaponItemRef.WHITE_CLAWS.getSimilarItems(),
            finished(PaidQuest.WANTED, ATTACK, 10)),
    WHITE_HALBERD(
            WeaponItemRef.WHITE_HALBERD,
            true,
            new AttackBonus(19, 25, 0, -4, 0),
            new DefenceBonus(-1, 2, 3, 0, 0),
            new SkillsBonus(20, 0, 0, 1),
            3.175,
            7,
            WeaponItemRef.WHITE_HALBERD.getSimilarItems(),
            finished(PaidQuest.WANTED, ATTACK, 10)),
    WILLOW_COMP_BOW(
            WeaponItemRef.WILLOW_COMP_BOW,
            false,
            new AttackBonus(0, 0, 0, 0, 22),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.8,
            5,
            WeaponItemRef.WILLOW_COMP_BOW.getSimilarItems()),
    WILLOW_LONGBOW(
            WeaponItemRef.WILLOW_LONGBOW,
            false,
            new AttackBonus(0, 0, 0, 0, 20),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.814,
            6,
            WeaponItemRef.WILLOW_LONGBOW.getSimilarItems()),
    WILLOW_SHORTBOW(
            WeaponItemRef.WILLOW_SHORTBOW,
            false,
            new AttackBonus(0, 0, 0, 0, 20),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.36,
            4,
            WeaponItemRef.WILLOW_SHORTBOW.getSimilarItems()),
    YEW_COMP_BOW(
            WeaponItemRef.YEW_COMP_BOW,
            true,
            new AttackBonus(0, 0, 0, 0, 49),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.8,
            5,
            WeaponItemRef.YEW_COMP_BOW.getSimilarItems()),
    YEW_LONGBOW(
            WeaponItemRef.YEW_LONGBOW,
            true,
            new AttackBonus(0, 0, 0, 0, 47),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.814,
            6,
            WeaponItemRef.YEW_LONGBOW.getSimilarItems()),
    YEW_SHORTBOW(
            WeaponItemRef.YEW_SHORTBOW,
            true,
            new AttackBonus(0, 0, 0, 0, 47),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.36,
            4,
            WeaponItemRef.YEW_SHORTBOW.getSimilarItems()),
    ZAMORAK_GODSWORD(
            WeaponItemRef.ZAMORAK_GODSWORD,
            true,
            new AttackBonus(0, 132, 80, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(132, 0, 0, 8),
            10.0,
            6,
            WeaponItemRef.ZAMORAK_GODSWORD.getSimilarItems(),
            levels(ATTACK, 75)),
    ZAMORAK_MJOLNIR(
            WeaponItemRef.ZAMORAK_MJOLNIR,
            true,
            new AttackBonus(0, 0, 11, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(14, 0, 0, 0),
            2.267,
            6,
            WeaponItemRef.ZAMORAK_MJOLNIR.getSimilarItems()),
    ZAMORAKIAN_SPEAR(
            WeaponItemRef.ZAMORAKIAN_SPEAR,
            true,
            new AttackBonus(85, 65, 65, 0, 0),
            new DefenceBonus(13, 13, 12, 0, 13),
            new SkillsBonus(75, 0, 0, 2),
            3.0,
            4,
            WeaponItemRef.ZAMORAKIAN_SPEAR.getSimilarItems(),
            levels(ATTACK, 70));

    private final EquipmentSlot slot = EquipmentSlot.WEAPON;
    private final GenericItemRef itemRef;
    private final boolean members;
    private final AttackBonus attackBonus;
    private final DefenceBonus defenceBonus;
    private final SkillsBonus skillsBonus;
    private final double weight;
    private final int attackSpeed;
    private final GenericItemRef[] similarItems;
    private final LocalRequirement requirement;

    TwoHandedSlotRefs(
            GenericItemRef itemRef,
            boolean members,
            AttackBonus attackBonus,
            DefenceBonus defenceBonus,
            SkillsBonus skillsBonus,
            double weight,
            int attackSpeed,
            GenericItemRef[] similarItems) {
        this(
                itemRef,
                members,
                attackBonus,
                defenceBonus,
                skillsBonus,
                weight,
                attackSpeed,
                similarItems,
                LocalRequirement.none());
    }
}
