package com.idlescape.gamedata.items.equipment;

import static org.dreambot.api.methods.skills.Skill.AGILITY;
import static org.dreambot.api.methods.skills.Skill.ATTACK;
import static org.dreambot.api.methods.skills.Skill.DEFENCE;
import static org.dreambot.api.methods.skills.Skill.HITPOINTS;
import static org.dreambot.api.methods.skills.Skill.HUNTER;
import static org.dreambot.api.methods.skills.Skill.MAGIC;
import static org.dreambot.api.methods.skills.Skill.PRAYER;
import static org.dreambot.api.methods.skills.Skill.RANGED;
import static org.dreambot.api.methods.skills.Skill.STRENGTH;

import com.idlescape.framework.requirements.Requirement;
import com.idlescape.framework.requirements.RequirementBuilder;
import com.idlescape.gamedata.combat.AttackBonus;
import com.idlescape.gamedata.combat.DefenceBonus;
import com.idlescape.gamedata.combat.SkillsBonus;
import com.idlescape.gamedata.diary.DiaryDifficulty;
import com.idlescape.gamedata.items.ArmourItemRef;
import com.idlescape.gamedata.items.GenericItemRef;
import lombok.AllArgsConstructor;
import lombok.Getter;
import org.dreambot.api.methods.container.impl.equipment.EquipmentSlot;
import org.dreambot.api.methods.diary.WesternProvincesDiary;
import org.dreambot.api.methods.quest.book.MiniQuest;
import org.dreambot.api.methods.quest.book.PaidQuest;

@Getter
@AllArgsConstructor
public enum LegsSlotRef implements EquipmentRef {
    _3RD_AGE_DRUIDIC_ROBE_BOTTOMS(
            ArmourItemRef._3RD_AGE_DRUIDIC_ROBE_BOTTOMS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 6),
            1.5,
            ArmourItemRef._3RD_AGE_DRUIDIC_ROBE_BOTTOMS.getSimilarItems(),
            new RequirementBuilder().hasLevel(PRAYER, 65).build()),
    _3RD_AGE_PLATELEGS(
            ArmourItemRef._3RD_AGE_PLATELEGS,
            true,
            new AttackBonus(0, 0, 0, -25, -2),
            new DefenceBonus(78, 76, 83, -5, 75),
            new SkillsBonus(0, 0, 0, 0),
            2.721,
            ArmourItemRef._3RD_AGE_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 65).build()),
    _3RD_AGE_PLATESKIRT(
            ArmourItemRef._3RD_AGE_PLATESKIRT,
            true,
            new AttackBonus(0, 0, 0, -25, -2),
            new DefenceBonus(78, 76, 83, -5, 75),
            new SkillsBonus(0, 0, 0, 0),
            2.721,
            ArmourItemRef._3RD_AGE_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 65).build()),
    _3RD_AGE_RANGE_LEGS(
            ArmourItemRef._3RD_AGE_RANGE_LEGS,
            true,
            new AttackBonus(0, 0, 0, -10, 17),
            new DefenceBonus(31, 25, 33, 30, 31),
            new SkillsBonus(0, 0, 0, 0),
            3.0,
            ArmourItemRef._3RD_AGE_RANGE_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 65).hasLevel(DEFENCE, 45).build()),
    _3RD_AGE_LEGS(
            ArmourItemRef._3RD_AGE_ROBE,
            true,
            new AttackBonus(0, 0, 0, 19, 0),
            new DefenceBonus(0, 0, 0, 19, 0),
            new SkillsBonus(0, 0, 1, 0),
            1.8,
            ArmourItemRef._3RD_AGE_ROBE.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 65).build()),
    ADAMANT_PLATELEGS(
            ArmourItemRef.ADAMANT_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(33, 31, 29, -4, 31),
            new SkillsBonus(0, 0, 0, 0),
            10.432,
            ArmourItemRef.ADAMANT_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 30).build()),
    ADAMANT_PLATESKIRT(
            ArmourItemRef.ADAMANT_PLATESKIRT,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(33, 31, 29, -4, 31),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.ADAMANT_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 30).build()),
    AHRIMS_ROBESKIRT_UNDAMAGED(
            ArmourItemRef.AHRIMS_ROBESKIRT_UNDAMAGED,
            true,
            new AttackBonus(0, 0, 0, 22, -7),
            new DefenceBonus(33, 30, 36, 22, 0),
            new SkillsBonus(0, 0, 1, 0),
            11.339,
            ArmourItemRef.AHRIMS_ROBESKIRT_UNDAMAGED.getSimilarItems(),
            new RequirementBuilder().hasLevel(MAGIC, 70).hasLevel(DEFENCE, 70).build()),
    ANCESTRAL_ROBE_BOTTOM(
            ArmourItemRef.ANCESTRAL_ROBE_BOTTOM,
            true,
            new AttackBonus(0, 0, 0, 26, -7),
            new DefenceBonus(27, 24, 30, 20, 0),
            new SkillsBonus(0, 0, 3, 0),
            1.814,
            ArmourItemRef.ANCESTRAL_ROBE_BOTTOM.getSimilarItems(),
            new RequirementBuilder().hasLevel(MAGIC, 75).hasLevel(DEFENCE, 65).build()),
    ANCIENT_CEREMONIAL_LEGS(
            ArmourItemRef.ANCIENT_CEREMONIAL_LEGS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 5),
            0.8,
            ArmourItemRef.ANCIENT_CEREMONIAL_LEGS.getSimilarItems()),
    ANCIENT_CHAPS(
            ArmourItemRef.ANCIENT_CHAPS,
            true,
            new AttackBonus(0, 0, 0, -10, 17),
            new DefenceBonus(31, 25, 33, 28, 31),
            new SkillsBonus(0, 0, 0, 1),
            5.0,
            ArmourItemRef.ANCIENT_CHAPS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 70).build()),
    ANCIENT_PLATELEGS(
            ArmourItemRef.ANCIENT_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 1),
            9.071,
            ArmourItemRef.ANCIENT_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 40).build()),
    ANCIENT_PLATESKIRT(
            ArmourItemRef.ANCIENT_PLATESKIRT,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 1),
            9.071,
            ArmourItemRef.ANCIENT_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 40).build()),
    ANCIENT_ROBE_LEGS(
            ArmourItemRef.ANCIENT_ROBE_LEGS,
            true,
            new AttackBonus(0, 0, 0, 4, 0),
            new DefenceBonus(0, 0, 0, 4, 0),
            new SkillsBonus(0, 0, 0, 5),
            0.005,
            ArmourItemRef.ANCIENT_ROBE_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(PRAYER, 20).build()),
    ANKOUS_LEGGINGS(
            ArmourItemRef.ANKOUS_LEGGINGS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.5,
            ArmourItemRef.ANKOUS_LEGGINGS.getSimilarItems()),
    ARDOUGNE_KNIGHT_PLATELEGS(
            ArmourItemRef.ARDOUGNE_KNIGHT_PLATELEGS,
            true,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(11, 10, 10, -4, 10),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.ARDOUGNE_KNIGHT_PLATELEGS.getSimilarItems()),
    ARMADYL_CHAINSKIRT(
            ArmourItemRef.ARMADYL_CHAINSKIRT,
            true,
            new AttackBonus(-6, -6, -6, -10, 20),
            new DefenceBonus(32, 26, 34, 40, 33),
            new SkillsBonus(0, 0, 0, 1),
            1.0,
            ArmourItemRef.ARMADYL_CHAINSKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 70).hasLevel(DEFENCE, 70).build()),
    ARMADYL_CHAPS(
            ArmourItemRef.ARMADYL_CHAPS,
            true,
            new AttackBonus(0, 0, 0, -10, 17),
            new DefenceBonus(31, 25, 33, 28, 31),
            new SkillsBonus(0, 0, 0, 1),
            5.0,
            ArmourItemRef.ARMADYL_CHAPS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 70).build()),
    ARMADYL_PLATELEGS(
            ArmourItemRef.ARMADYL_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 1),
            9.071,
            ArmourItemRef.ARMADYL_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 40).build()),
    ARMADYL_PLATESKIRT(
            ArmourItemRef.ARMADYL_PLATESKIRT,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 1),
            9.071,
            ArmourItemRef.ARMADYL_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 40).build()),
    ARMADYL_ROBE_LEGS(
            ArmourItemRef.ARMADYL_ROBE_LEGS,
            true,
            new AttackBonus(0, 0, 0, 4, 0),
            new DefenceBonus(0, 0, 0, 4, 0),
            new SkillsBonus(0, 0, 0, 5),
            2.7,
            ArmourItemRef.ARMADYL_ROBE_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(PRAYER, 20).build()),
    BANDOS_CHAPS(
            ArmourItemRef.BANDOS_CHAPS,
            true,
            new AttackBonus(0, 0, 0, -10, 17),
            new DefenceBonus(31, 25, 33, 28, 31),
            new SkillsBonus(0, 0, 0, 1),
            5.0,
            ArmourItemRef.BANDOS_CHAPS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 70).build()),
    BANDOS_PLATELEGS(
            ArmourItemRef.BANDOS_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 1),
            9.071,
            ArmourItemRef.BANDOS_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 40).build()),
    BANDOS_PLATESKIRT(
            ArmourItemRef.BANDOS_PLATESKIRT,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 1),
            9.071,
            ArmourItemRef.BANDOS_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 40).build()),
    BANDOS_ROBE_LEGS(
            ArmourItemRef.BANDOS_ROBE_LEGS,
            true,
            new AttackBonus(0, 0, 0, 4, 0),
            new DefenceBonus(0, 0, 0, 4, 0),
            new SkillsBonus(0, 0, 0, 5),
            2.7,
            ArmourItemRef.BANDOS_ROBE_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(PRAYER, 20).build()),
    BANDOS_TASSETS(
            ArmourItemRef.BANDOS_TASSETS,
            true,
            new AttackBonus(0, 0, 0, -21, -7),
            new DefenceBonus(71, 63, 66, -4, 93),
            new SkillsBonus(2, 0, 0, 1),
            8.0,
            ArmourItemRef.BANDOS_TASSETS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 65).build()),
    BLACK_DHIDE_CHAPS(
            ArmourItemRef.BLACK_DHIDE_CHAPS,
            true,
            new AttackBonus(0, 0, 0, -10, 17),
            new DefenceBonus(18, 20, 26, 23, 26),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            ArmourItemRef.BLACK_DHIDE_CHAPS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 70).build()),
    BLACK_ELEGANT_LEGS(
            ArmourItemRef.BLACK_ELEGANT_LEGS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            ArmourItemRef.BLACK_ELEGANT_LEGS.getSimilarItems()),
    BLACK_PLATELEGS(
            ArmourItemRef.BLACK_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(21, 20, 19, -4, 20),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.BLACK_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 10).build()),
    BLACK_PLATESKIRT(
            ArmourItemRef.BLACK_PLATESKIRT,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(21, 20, 19, -4, 20),
            new SkillsBonus(0, 0, 0, 0),
            8.164,
            ArmourItemRef.BLACK_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 10).build()),
    BLOOD_MOON_LEGS(
            ArmourItemRef.BLOOD_MOON_LEGS,
            true,
            new AttackBonus(0, 0, 0, -21, -7),
            new DefenceBonus(30, 50, 49, 32, 46),
            new SkillsBonus(2, 0, 0, 0),
            4.082,
            ArmourItemRef.BLOOD_MOON_LEGS.getSimilarItems(),
            new RequirementBuilder()
                    .hasLevel(DEFENCE, 50)
                    .hasLevel(STRENGTH, 75)
                    .build()),
    BLOOD_BARK_LEGS(
            ArmourItemRef.BLOOD_BARK_LEGS,
            true,
            new AttackBonus(0, 0, 0, 16, 0),
            new DefenceBonus(33, 31, 38, 17, 0),
            new SkillsBonus(0, 0, 1, 0),
            3.628,
            ArmourItemRef.BLOOD_BARK_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 60).hasLevel(MAGIC, 60).build()),
    BLUE_DHIDE_CHAPS(
            ArmourItemRef.BLUE_DHIDE_CHAPS,
            true,
            new AttackBonus(0, 0, 0, -10, 11),
            new DefenceBonus(13, 16, 20, 14, 20),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            ArmourItemRef.BLUE_DHIDE_CHAPS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 50).build()),
    BLUE_ELEGANT_LEGS(
            ArmourItemRef.BLUE_ELEGANT_LEGS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            ArmourItemRef.BLUE_ELEGANT_LEGS.getSimilarItems()),
    BLUE_ELEGANT_SKIRT(
            ArmourItemRef.BLUE_ELEGANT_SKIRT,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            ArmourItemRef.BLUE_ELEGANT_SKIRT.getSimilarItems()),
    BLUEMOON_TASSETS(
            ArmourItemRef.BLUEMOON_TASSETS,
            true,
            new AttackBonus(0, 0, 0, 22, 0),
            new DefenceBonus(0, 0, 23, 32, 0),
            new SkillsBonus(1, 0, 1, 0),
            1.36,
            ArmourItemRef.BLUEMOON_TASSETS.getSimilarItems(),
            new RequirementBuilder()
                    .hasLevel(MAGIC, 75)
                    .and()
                    .hasLevel(DEFENCE, 50)
                    .build()),
    BLUE_ROBE_BOTTOMS(
            ArmourItemRef.BLUE_ROBE_BOTTOMS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 2, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.BLUE_ROBE_BOTTOMS.getSimilarItems()),
    BRONZE_PLATELEGS(
            ArmourItemRef.BRONZE_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(8, 7, 6, -4, 7),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.BRONZE_PLATELEGS.getSimilarItems()),
    BRONZE_PLATESKIRT(
            ArmourItemRef.BRONZE_PLATESKIRT,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(8, 7, 6, -4, 7),
            new SkillsBonus(0, 0, 0, 0),
            8.164,
            ArmourItemRef.BRONZE_PLATESKIRT.getSimilarItems()),
    CITIZEN_TROUSERS(
            ArmourItemRef.CITIZEN_TROUSERS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 2, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.CITIZEN_TROUSERS.getSimilarItems()),
    CREAM_ROBE_BOTTOMS(
            ArmourItemRef.CREAM_ROBE_BOTTOMS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 2, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.CREAM_ROBE_BOTTOMS.getSimilarItems()),
    CRYSTAL_LEGS(
            ArmourItemRef.CRYSTAL_LEGS,
            true,
            new AttackBonus(0, 0, 0, -12, 18),
            new DefenceBonus(26, 21, 30, 34, 38),
            new SkillsBonus(0, 0, 0, 2),
            1.0,
            ArmourItemRef.CRYSTAL_LEGS.getSimilarItems(),
            new RequirementBuilder()
                    .hasLevel(AGILITY, 50)
                    .and()
                    .hasLevel(DEFENCE, 70)
                    .build()),
    DRAGONHAI_BOTTOM(
            ArmourItemRef.DRAGONHAI_ROBE_BOTTOM,
            true,
            new AttackBonus(0, 0, 0, 18, 0),
            new DefenceBonus(0, 0, 0, 14, 0),
            new SkillsBonus(0, 0, 1, 2),
            1.814,
            ArmourItemRef.DRAGONHAI_ROBE_BOTTOM.getSimilarItems(),
            new RequirementBuilder()
                    .hasLevel(MAGIC, 70)
                    .and()
                    .hasLevel(DEFENCE, 40)
                    .build()),
    DARK_SQUALL_ROBE_BOTTOM(
            ArmourItemRef.DARK_SQUALL_ROBE_BOTTOM,
            true,
            new AttackBonus(0, 0, 0, 3, 0),
            new DefenceBonus(0, 0, 0, 3, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.DARK_SQUALL_ROBE_BOTTOM.getSimilarItems(),
            new RequirementBuilder().finished(PaidQuest.WHILE_GUTHIX_SLEEPS).build()),
    DARK_TROUSERS(
            ArmourItemRef.DARK_TROUSERS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            ArmourItemRef.DARK_TROUSERS.getSimilarItems()),
    DECORATIVE_ARMOUR_GOLD_PLATELEGS(
            ArmourItemRef.DECORATIVE_ARMOUR_GOLD_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(33, 31, 29, -4, 31),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.DECORATIVE_ARMOUR_GOLD_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 30).build()),
    DECORATIVE_ARMOUR_GOLD_PLATESKIRT(
            ArmourItemRef.DECORATIVE_ARMOUR_GOLD_PLATESKIRT,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(33, 31, 29, -4, 31),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.DECORATIVE_ARMOUR_GOLD_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 30).build()),
    DECORATIVE_ARMOUR_MAGIC_LEGS(
            ArmourItemRef.DECORATIVE_ARMOUR_MAGIC_LEGS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(15, 15, 15, 15, 15),
            new SkillsBonus(0, 0, 0, 0),
            8.164,
            ArmourItemRef.DECORATIVE_ARMOUR_MAGIC_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(MAGIC, 20).build()),
    DECORATIVE_ARMOUR_RANGED_LEGS(
            ArmourItemRef.DECORATIVE_ARMOUR_RANGED_LEGS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(15, 15, 15, 15, 15),
            new SkillsBonus(0, 0, 0, 0),
            8.164,
            ArmourItemRef.DECORATIVE_ARMOUR_RANGED_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 30).build()),
    DECORATIVE_ARMOUR_RED_PLATELEGS(
            ArmourItemRef.DECORATIVE_ARMOUR_RED_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(17, 16, 15, -4, 16),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.DECORATIVE_ARMOUR_RED_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 5).build()),
    DECORATIVE_ARMOUR_RED_PLATESKIRT(
            ArmourItemRef.DECORATIVE_ARMOUR_RED_PLATESKIRT,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(17, 16, 15, -4, 16),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.DECORATIVE_ARMOUR_RED_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 5).build()),
    DECORATIVE_ARMOUR_WHITE_PLATELEGS(
            ArmourItemRef.DECORATIVE_ARMOUR_WHITE_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(24, 22, 20, -4, 22),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.DECORATIVE_ARMOUR_WHITE_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 20).build()),
    DECORATIVE_ARMOUR_WHITE_PLATESKIRT(
            ArmourItemRef.DECORATIVE_ARMOUR_WHITE_PLATESKIRT,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(24, 22, 20, -4, 22),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.DECORATIVE_ARMOUR_WHITE_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 20).build()),
    DHAROKS_PLATELEGS(
            ArmourItemRef.DHAROKS_PLATELEGS,
            true,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(85, 82, 83, -4, 92),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.DHAROKS_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 70).build()),
    DRAGON_PLATELEGS(
            ArmourItemRef.DRAGON_PLATELEGS,
            true,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(68, 66, 63, -4, 65),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.DRAGON_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 60).build()),
    DRAGON_PLATE_SKIRT(
            ArmourItemRef.DRAGON_PLATE_SKIRT,
            true,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(68, 66, 63, -4, 65),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.DRAGON_PLATE_SKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 60).build()),
    DRAGONSTONE_PLATELEGS(
            ArmourItemRef.DRAGONSTONE_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.DRAGONSTONE_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 40).build()),
    DRUIDS_ROBE(
            ArmourItemRef.DRUIDS_ROBE,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 4),
            0.907,
            ArmourItemRef.DRUIDS_ROBE.getSimilarItems()),
    ECLIPSE_MOON_TASSETS(
            ArmourItemRef.ECLIPSE_MOON_TASSETS,
            true,
            new AttackBonus(0, 0, 0, -15, 17),
            new DefenceBonus(9, 13, 37, 31, 17),
            new SkillsBonus(1, 0, 0, 0),
            1.0,
            ArmourItemRef.ECLIPSE_MOON_TASSETS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 75).hasLevel(DEFENCE, 50).build()),
    ELDER_CHAOS_ROBE(
            ArmourItemRef.ELDER_CHAOS_ROBE,
            true,
            new AttackBonus(0, 0, 0, 6, 0),
            new DefenceBonus(0, 0, 0, 6, 0),
            new SkillsBonus(0, 0, 1, 0),
            0.18,
            ArmourItemRef.ELDER_CHAOS_ROBE.getSimilarItems(),
            new RequirementBuilder().hasLevel(MAGIC, 40).build()),
    ELITE_BLACK_PLATELEGS(
            ArmourItemRef.ELITE_BLACK_PLATELEGS,
            true,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(24, 22, 20, -4, 22),
            new SkillsBonus(0, 0, 0, 6),
            9.071,
            ArmourItemRef.ELITE_BLACK_PLATELEGS.getSimilarItems(),
            new RequirementBuilder()
                    .finished(PaidQuest.WHILE_GUTHIX_SLEEPS)
                    .and()
                    .hasLevel(DEFENCE, 40)
                    .build()),
    ELITE_VOID_ROBE(
            ArmourItemRef.ELITE_VOID_ROBE,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(30, 30, 30, 30, 30),
            new SkillsBonus(0, 0, 0, 3),
            8.164,
            ArmourItemRef.ELITE_VOID_ROBE.getSimilarItems(),
            new RequirementBuilder()
                    .completed(new WesternProvincesDiary(), DiaryDifficulty.HARD)
                    .and()
                    .hasLevel(ATTACK, 42)
                    .and()
                    .hasLevel(STRENGTH, 42)
                    .and()
                    .hasLevel(DEFENCE, 42)
                    .and()
                    .hasLevel(HITPOINTS, 42)
                    .and()
                    .hasLevel(RANGED, 42)
                    .and()
                    .hasLevel(MAGIC, 42)
                    .and()
                    .hasLevel(PRAYER, 22)
                    .build()),
    ENCHANTED_ROBE(
            ArmourItemRef.ENCHANTED_ROBE,
            true,
            new AttackBonus(0, 0, 0, 15, 0),
            new DefenceBonus(0, 0, 0, 15, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.814,
            ArmourItemRef.ENCHANTED_ROBE.getSimilarItems(),
            new RequirementBuilder().hasLevel(MAGIC, 40).hasLevel(DEFENCE, 20).build()),
    FLARED_TROUSERS(
            ArmourItemRef.FLARED_TROUSERS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            ArmourItemRef.FLARED_TROUSERS.getSimilarItems()),
    FREMENNIK_KILT(
            ArmourItemRef.FREMENNIK_KILT,
            true,
            new AttackBonus(0, 0, 0, -21, -7),
            new DefenceBonus(11, 10, 10, -4, 10),
            new SkillsBonus(1, 0, 0, 0),
            3.0,
            ArmourItemRef.FREMENNIK_KILT.getSimilarItems()),
    FREMENNIK_SKIRT(
            ArmourItemRef.FREMENNIK_SKIRT,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 2, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.FREMENNIK_SKIRT.getSimilarItems()),
    FROG_LEATHER_CHAPS(
            ArmourItemRef.FROG_LEATHER_CHAPS,
            true,
            new AttackBonus(0, 0, 0, -5, 2),
            new DefenceBonus(7, 7, 9, 4, 9),
            new SkillsBonus(0, 0, 0, 0),
            3.0,
            ArmourItemRef.FROG_LEATHER_CHAPS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 25).hasLevel(DEFENCE, 25).build()),
    GHOSTLY_ROBE_BOTTOM(
            ArmourItemRef.GHOSTLY_ROBE_BOTTOM,
            true,
            new AttackBonus(0, 0, 0, 4, 0),
            new DefenceBonus(0, 0, 0, 4, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.001,
            ArmourItemRef.GHOSTLY_ROBE_BOTTOM.getSimilarItems(),
            new RequirementBuilder().finished(MiniQuest.CURSE_OF_THE_EMPTY_LORD).build()),
    GILDED_DHIDE_CHAPS(
            ArmourItemRef.GILDED_DHIDE_CHAPS,
            false,
            new AttackBonus(0, 0, 0, -10, 8),
            new DefenceBonus(22, 16, 24, 8, 22),
            new SkillsBonus(0, 0, 0, 0),
            5.0,
            ArmourItemRef.GILDED_DHIDE_CHAPS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 40).build()),
    GILDED_PLATELEGS(
            ArmourItemRef.GILDED_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.GILDED_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 40).build()),
    GILDED_PLATESKIRT(
            ArmourItemRef.GILDED_PLATESKIRT,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.GILDED_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 40).build()),
    GOLD_ELEGANT_LEGS(
            ArmourItemRef.GOLD_ELEGANT_LEGS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.1,
            ArmourItemRef.GOLD_ELEGANT_LEGS.getSimilarItems()),
    GOLD_ELEGANT_SKIRT(
            ArmourItemRef.GOLD_ELEGANT_SKIRT,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.1,
            ArmourItemRef.GOLD_ELEGANT_SKIRT.getSimilarItems()),
    GRAAHK_LEGS(
            ArmourItemRef.GRAAHK_LEGS,
            true,
            new AttackBonus(0, 0, 0, 0, -7),
            new DefenceBonus(11, 10, 10, 0, 10),
            new SkillsBonus(0, 0, 0, 0),
            0.226,
            ArmourItemRef.GRAAHK_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(HUNTER, 38).build()),
    GRACEFUL_LEGS_ADVENTURER(
            ArmourItemRef.GRACEFUL_LEGS_ADVENTURER,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -6.0,
            ArmourItemRef.GRACEFUL_LEGS_ADVENTURER.getSimilarItems()),
    GRACEFUL_LEGS_AGILITY_ARENA(
            ArmourItemRef.GRACEFUL_LEGS_AGILITY_ARENA,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -6.0,
            ArmourItemRef.GRACEFUL_LEGS_AGILITY_ARENA.getSimilarItems()),
    GRACEFUL_LEGS_ARCEUUS_WORN(
            ArmourItemRef.GRACEFUL_LEGS_ARCEUUS_WORN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -6.0,
            ArmourItemRef.GRACEFUL_LEGS_ARCEUUS_WORN.getSimilarItems()),
    GRACEFUL_LEGS_HALLOWED(
            ArmourItemRef.GRACEFUL_LEGS_HALLOWED,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -6.0,
            ArmourItemRef.GRACEFUL_LEGS_HALLOWED.getSimilarItems()),
    GRACEFUL_LEGS_HOSIDIUS_WORN(
            ArmourItemRef.GRACEFUL_LEGS_HOSIDIUS_WORN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -6.0,
            ArmourItemRef.GRACEFUL_LEGS_HOSIDIUS_WORN.getSimilarItems()),
    GRACEFUL_LEGS_KOUREND_WORN(
            ArmourItemRef.GRACEFUL_LEGS_KOUREND_WORN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -6.0,
            ArmourItemRef.GRACEFUL_LEGS_KOUREND_WORN.getSimilarItems()),
    GRACEFUL_LEGS_LOVAKENGJ_WORN(
            ArmourItemRef.GRACEFUL_LEGS_LOVAKENGJ_WORN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -6.0,
            ArmourItemRef.GRACEFUL_LEGS_LOVAKENGJ_WORN.getSimilarItems()),
    GRACEFUL_LEGS_PISCARILIUS(
            ArmourItemRef.GRACEFUL_LEGS_PISCARILIUS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -6.0,
            ArmourItemRef.GRACEFUL_LEGS_PISCARILIUS.getSimilarItems()),
    GRACEFUL_LEGS_SHAYZIEN_WORN(
            ArmourItemRef.GRACEFUL_LEGS_SHAYZIEN_WORN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -6.0,
            ArmourItemRef.GRACEFUL_LEGS_SHAYZIEN_WORN.getSimilarItems()),
    GRACEFUL_LEGS_TRAILBLAZER(
            ArmourItemRef.GRACEFUL_LEGS_TRAILBLAZER,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -6.0,
            ArmourItemRef.GRACEFUL_LEGS_TRAILBLAZER.getSimilarItems()),
    GRACEFUL_LEGS_VARLAMORE_WORN(
            ArmourItemRef.GRACEFUL_LEGS_VARLAMORE_WORN,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -6.0,
            ArmourItemRef.GRACEFUL_LEGS_VARLAMORE_WORN.getSimilarItems()),
    GRACEFUL_LEGS_EQUIPPED(
            ArmourItemRef.GRACEFUL_LEGS_EQUIPPED,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            -6.0,
            ArmourItemRef.GRACEFUL_LEGS_EQUIPPED.getSimilarItems()),
    GRANITE_LEGS(
            ArmourItemRef.GRANITE_LEGS,
            true,
            new AttackBonus(0, 0, 0, -31, -18),
            new DefenceBonus(43, 45, 41, -4, 68),
            new SkillsBonus(0, 0, 0, 0),
            15.875,
            ArmourItemRef.GRANITE_LEGS.getSimilarItems(),
            new RequirementBuilder()
                    .hasLevel(DEFENCE, 50)
                    .hasLevel(STRENGTH, 50)
                    .build()),
    GREEN_DHIDE_CHAPS(
            ArmourItemRef.GREEN_DHIDE_CHAPS,
            false,
            new AttackBonus(0, 0, 0, -10, 8),
            new DefenceBonus(12, 15, 18, 8, 17),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            ArmourItemRef.GREEN_DHIDE_CHAPS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 40).build()),
    GREEN_ELEGANT_LEGS(
            ArmourItemRef.GREEN_ELEGANT_LEGS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            ArmourItemRef.GREEN_ELEGANT_LEGS.getSimilarItems()),
    GREEN_ELEGANT_SKIRT(
            ArmourItemRef.GREEN_ELEGANT_SKIRT,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            ArmourItemRef.GREEN_ELEGANT_SKIRT.getSimilarItems()),
    GREEN_ROBE_BOTTOMS(
            ArmourItemRef.GREEN_ROBE_BOTTOMS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 2, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.GREEN_ROBE_BOTTOMS.getSimilarItems()),
    GREY_ROBE_BOTTOMS(
            ArmourItemRef.GREY_ROBE_BOTTOMS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 2, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.GREY_ROBE_BOTTOMS.getSimilarItems()),
    GROUP_IRONMAN_PLATELEGS(
            ArmourItemRef.GROUP_IRONMAN_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(11, 10, 10, -4, 10),
            new SkillsBonus(0, 0, 0, 0),
            4.535,
            ArmourItemRef.GROUP_IRONMAN_PLATELEGS.getSimilarItems()),
    GROUP_IRONMAN_PLATELEGS_UNRANKED(
            ArmourItemRef.GROUP_IRONMAN_PLATELEGS_UNRANKED,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(11, 10, 10, -4, 10),
            new SkillsBonus(0, 0, 0, 0),
            4.535,
            ArmourItemRef.GROUP_IRONMAN_PLATELEGS_UNRANKED.getSimilarItems()),
    GUTHANS_CHAINSKIRT(
            ArmourItemRef.GUTHANS_CHAINSKIRT,
            true,
            new AttackBonus(0, 0, 0, -14, -11),
            new DefenceBonus(75, 72, 73, -4, 82),
            new SkillsBonus(0, 0, 0, 0),
            8.164,
            ArmourItemRef.GUTHANS_CHAINSKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 70).build()),
    GUTHIX_CHAPS(
            ArmourItemRef.GUTHIX_CHAPS,
            true,
            new AttackBonus(0, 0, 0, -10, 17),
            new DefenceBonus(31, 25, 33, 28, 31),
            new SkillsBonus(0, 0, 0, 1),
            5.0,
            ArmourItemRef.GUTHIX_CHAPS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 70).build()),
    GUTHIX_PLATELEGS(
            ArmourItemRef.GUTHIX_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 1),
            9.071,
            ArmourItemRef.GUTHIX_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 40).build()),
    GUTHIX_PLATESKIRT(
            ArmourItemRef.GUTHIX_PLATESKIRT,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 1),
            9.071,
            ArmourItemRef.GUTHIX_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 40).build()),
    GUTHIX_ROBE_LEGS(
            ArmourItemRef.GUTHIX_ROBE_LEGS,
            true,
            new AttackBonus(0, 0, 0, 4, 0),
            new DefenceBonus(0, 0, 0, 4, 0),
            new SkillsBonus(0, 0, 0, 5),
            2.7,
            ArmourItemRef.GUTHIX_ROBE_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(PRAYER, 20).build()),
    HAM_ROBE_BOTTOM(
            ArmourItemRef.HAM_ROBE_BOTTOM,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 2, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.HAM_ROBE_BOTTOM.getSimilarItems()),
    HARDCORE_GROUP_IRONMAN_PLATELEGS(
            ArmourItemRef.HARDCORE_GROUP_IRONMAN_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(11, 10, 10, -4, 10),
            new SkillsBonus(0, 0, 0, 0),
            4.535,
            ArmourItemRef.HARDCORE_GROUP_IRONMAN_PLATELEGS.getSimilarItems()),
    HARDCORE_IRONMAN_PLATELEGS(
            ArmourItemRef.HARDCORE_IRONMAN_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(11, 10, 10, -4, 10),
            new SkillsBonus(0, 0, 0, 0),
            4.535,
            ArmourItemRef.HARDCORE_IRONMAN_PLATELEGS.getSimilarItems()),
    HUEYCOATL_HIDE_CHAPS(
            ArmourItemRef.HUEYCOATL_HIDE_CHAPS,
            true,
            new AttackBonus(0, 0, 0, -10, 17),
            new DefenceBonus(31, 25, 33, 30, 31),
            new SkillsBonus(0, 0, 0, 2),
            5.443,
            ArmourItemRef.HUEYCOATL_HIDE_CHAPS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 70).build()),
    INFINITY_BOTTOMS(
            ArmourItemRef.INFINITY_BOTTOMS,
            true,
            new AttackBonus(0, 0, 0, 17, 0),
            new DefenceBonus(0, 0, 0, 17, 0),
            new SkillsBonus(0, 0, 1, 0),
            1.814,
            ArmourItemRef.INFINITY_BOTTOMS.getSimilarItems(),
            new RequirementBuilder().hasLevel(MAGIC, 50).hasLevel(DEFENCE, 25).build()),
    INITIATE_CUISSE(
            ArmourItemRef.INITIATE_CUISSE,
            true,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(24, 22, 20, -4, 22),
            new SkillsBonus(0, 0, 0, 5),
            7.711,
            ArmourItemRef.INITIATE_CUISSE.getSimilarItems(),
            new RequirementBuilder()
                    .finished(PaidQuest.RECRUITMENT_DRIVE)
                    .and()
                    .hasLevel(DEFENCE, 20)
                    .and()
                    .hasLevel(PRAYER, 10)
                    .build()),
    INQUISITORS_PLATESKIRT(
            ArmourItemRef.INQUISITORS_PLATESKIRT,
            true,
            new AttackBonus(-3, -3, 12, -9, -5),
            new DefenceBonus(42, 30, 49, 0, 22),
            new SkillsBonus(2, 0, 0, 2),
            9.071,
            ArmourItemRef.INQUISITORS_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder()
                    .hasLevel(STRENGTH, 70)
                    .hasLevel(DEFENCE, 30)
                    .build()),
    IRON_PLATELEGS(
            ArmourItemRef.IRON_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(11, 10, 10, -4, 10),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.IRON_PLATELEGS.getSimilarItems()),
    IRON_PLATESKIRT(
            ArmourItemRef.IRON_PLATESKIRT,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(11, 10, 10, -4, 10),
            new SkillsBonus(0, 0, 0, 0),
            8.164,
            ArmourItemRef.IRON_PLATESKIRT.getSimilarItems()),
    IRONMAN_PLATELEGS(
            ArmourItemRef.IRONMAN_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(11, 10, 10, -4, 10),
            new SkillsBonus(0, 0, 0, 0),
            4.535,
            ArmourItemRef.IRONMAN_PLATELEGS.getSimilarItems()),
    JUSTICIAR_LEGGUARDS(
            ArmourItemRef.JUSTICIAR_LEGGUARDS,
            true,
            new AttackBonus(0, 0, 0, -31, -17),
            new DefenceBonus(95, 92, 93, -14, 102),
            new SkillsBonus(0, 0, 0, 4),
            9.071,
            ArmourItemRef.JUSTICIAR_LEGGUARDS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 75).build()),
    KARILS_LEATHER_SKIRT(
            ArmourItemRef.KARILS_LEATHER_SKIRT,
            true,
            new AttackBonus(0, 0, 0, -10, 17),
            new DefenceBonus(26, 20, 28, 35, 33),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            ArmourItemRef.KARILS_LEATHER_SKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 70).hasLevel(DEFENCE, 70).build()),
    KYATT_LEGS(
            ArmourItemRef.KYATT_LEGS,
            true,
            new AttackBonus(0, 0, 0, 0, -7),
            new DefenceBonus(11, 10, 10, 0, 10),
            new SkillsBonus(0, 0, 0, 0),
            0.226,
            ArmourItemRef.KYATT_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(HUNTER, 52).build()),
    LARUPIA_LEGS(
            ArmourItemRef.LARUPIA_LEGS,
            true,
            new AttackBonus(0, 0, 0, 0, -7),
            new DefenceBonus(11, 10, 10, 0, 10),
            new SkillsBonus(0, 0, 0, 0),
            0.226,
            ArmourItemRef.LARUPIA_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(HUNTER, 28).build()),
    LEATHER_CHAPS(
            ArmourItemRef.LEATHER_CHAPS,
            false,
            new AttackBonus(0, 0, 0, 0, 4),
            new DefenceBonus(2, 2, 1, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            2.721,
            ArmourItemRef.LEATHER_CHAPS.getSimilarItems()),
    LIGHT_TROUSERS(
            ArmourItemRef.LIGHT_TROUSERS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            ArmourItemRef.LIGHT_TROUSERS.getSimilarItems()),
    LUNAR_LEGS(
            ArmourItemRef.LUNAR_LEGS,
            true,
            new AttackBonus(0, 0, 0, 7, -7),
            new DefenceBonus(20, 19, 23, 9, 0),
            new SkillsBonus(0, 0, 0, 0),
            3.628,
            ArmourItemRef.LUNAR_LEGS.getSimilarItems(),
            new RequirementBuilder()
                    .started(PaidQuest.LUNAR_DIPLOMACY)
                    .and()
                    .hasLevel(MAGIC, 65)
                    .and()
                    .hasLevel(DEFENCE, 40)
                    .build()),
    MASORI_CHAPS(
            ArmourItemRef.MASORI_CHAPS,
            true,
            new AttackBonus(0, 0, 0, -2, 27),
            new DefenceBonus(26, 24, 29, 19, 22),
            new SkillsBonus(0, 2, 0, 0),
            7.0,
            ArmourItemRef.MASORI_CHAPS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 80).hasLevel(DEFENCE, 30).build()),
    MASORI_CHAPS_F(
            ArmourItemRef.MASORI_CHAPS_F,
            true,
            new AttackBonus(0, 0, 0, -2, 27),
            new DefenceBonus(35, 30, 39, 46, 37),
            new SkillsBonus(0, 2, 0, 1),
            8.5,
            ArmourItemRef.MASORI_CHAPS_F.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 80).hasLevel(DEFENCE, 80).build()),
    MITHRIL_PLATELEGS(
            ArmourItemRef.MITHRIL_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(24, 22, 20, -4, 22),
            new SkillsBonus(0, 0, 0, 0),
            7.711,
            ArmourItemRef.MITHRIL_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 20).build()),
    MITHRIL_PLATESKIRT(
            ArmourItemRef.MITHRIL_PLATESKIRT,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(24, 22, 20, -4, 22),
            new SkillsBonus(0, 0, 0, 0),
            7.257,
            ArmourItemRef.MITHRIL_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 20).build()),
    MIXED_HIDE_LEGS(
            ArmourItemRef.MIXED_HIDE_LEGS,
            true,
            new AttackBonus(3, -1, -2, -10, 14),
            new DefenceBonus(20, 23, 22, 16, 20),
            new SkillsBonus(0, 0, 0, 0),
            2.0,
            ArmourItemRef.MIXED_HIDE_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 60).build()),
    MONKS_ROBE(
            ArmourItemRef.MONKS_ROBE,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 5),
            0.907,
            ArmourItemRef.MONKS_ROBE.getSimilarItems()),
    MOONCLAN_SKIRT(
            ArmourItemRef.MOONCLAN_SKIRT,
            true,
            new AttackBonus(0, 0, 0, 5, -7),
            new DefenceBonus(5, 5, 5, 5, -7),
            new SkillsBonus(0, 0, 0, 0),
            3.628,
            ArmourItemRef.MOONCLAN_SKIRT.getSimilarItems()),
    MORYTANIA_LEGS_1(
            ArmourItemRef.MORYTANIA_LEGS_1,
            true,
            new AttackBonus(0, 0, 0, -21, -7),
            new DefenceBonus(11, 10, 10, -4, 10),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.MORYTANIA_LEGS_1.getSimilarItems()),
    MORYTANIA_LEGS_2(
            ArmourItemRef.MORYTANIA_LEGS_2,
            true,
            new AttackBonus(0, 0, 0, -21, -7),
            new DefenceBonus(17, 16, 15, -4, 16),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.MORYTANIA_LEGS_2.getSimilarItems()),
    MORYTANIA_LEGS_3(
            ArmourItemRef.MORYTANIA_LEGS_3,
            true,
            new AttackBonus(0, 0, 0, -21, -7),
            new DefenceBonus(24, 22, 20, -4, 22),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.MORYTANIA_LEGS_3.getSimilarItems()),
    MORYTANIA_LEGS_4(
            ArmourItemRef.MORYTANIA_LEGS_4,
            true,
            new AttackBonus(0, 0, 0, -21, -7),
            new DefenceBonus(33, 31, 29, -4, 31),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.MORYTANIA_LEGS_4.getSimilarItems()),
    MUMMYS_LEGS(
            ArmourItemRef.MUMMYS_LEGS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.5,
            ArmourItemRef.MUMMYS_LEGS.getSimilarItems()),
    MUSKETEER_PANTS(
            ArmourItemRef.MUSKETEER_PANTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.814,
            ArmourItemRef.MUSKETEER_PANTS.getSimilarItems()),
    MYSTIC_ROBE_BOTTOM(
            ArmourItemRef.MYSTIC_ROBE_BOTTOM,
            true,
            new AttackBonus(0, 0, 0, 15, 0),
            new DefenceBonus(0, 0, 0, 15, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.814,
            ArmourItemRef.MYSTIC_ROBE_BOTTOM.getSimilarItems(),
            new RequirementBuilder().hasLevel(MAGIC, 40).hasLevel(DEFENCE, 20).build()),
    OATHPLATE_LEGS(
            ArmourItemRef.OATHPLATE_LEGS,
            true,
            new AttackBonus(0, 12, 0, -12, -14),
            new DefenceBonus(75, 100, 73, -3, 81),
            new SkillsBonus(2, 0, 0, 0),
            9.071,
            ArmourItemRef.OATHPLATE_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 78).build()),
    OBSIDIAN_PLATELEGS(
            ArmourItemRef.OBSIDIAN_PLATELEGS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(46, 43, 41, -10, 40),
            new SkillsBonus(1, 0, 0, 0),
            9.071,
            ArmourItemRef.OBSIDIAN_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 60).build()),
    PANTALOONS(
            ArmourItemRef.PANTALOONS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            ArmourItemRef.PANTALOONS.getSimilarItems()),
    PENANCE_SKIRT(
            ArmourItemRef.PENANCE_SKIRT,
            true,
            new AttackBonus(0, 0, 0, -10, 15),
            new DefenceBonus(26, 21, 28, 19, 26),
            new SkillsBonus(0, 0, 0, 0),
            3.0,
            ArmourItemRef.PENANCE_SKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 60).hasLevel(DEFENCE, 40).build()),
    PINK_ELEGANT_LEGS(
            ArmourItemRef.PINK_ELEGANT_LEGS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.1,
            ArmourItemRef.PINK_ELEGANT_LEGS.getSimilarItems()),
    PINK_ELEGANT_SKIRT(
            ArmourItemRef.PINK_ELEGANT_SKIRT,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.1,
            ArmourItemRef.PINK_ELEGANT_SKIRT.getSimilarItems()),
    PINK_ROBE_BOTTOMS(
            ArmourItemRef.PINK_ROBE_BOTTOMS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 2, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.PINK_ROBE_BOTTOMS.getSimilarItems()),
    PINK_SKIRT(
            ArmourItemRef.PINK_SKIRT,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.PINK_SKIRT.getSimilarItems()),
    PRIEST_GOWN_BOTTOM(
            ArmourItemRef.PRIEST_GOWN_BOTTOM,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 3),
            1.814,
            ArmourItemRef.PRIEST_GOWN_BOTTOM.getSimilarItems()),
    PROSELYTE_CUISSE(
            ArmourItemRef.PROSELYTE_CUISSE,
            true,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(33, 31, 29, -4, 31),
            new SkillsBonus(0, 0, 0, 6),
            7.711,
            ArmourItemRef.PROSELYTE_CUISSE.getSimilarItems(),
            new RequirementBuilder()
                    .finished(PaidQuest.THE_SLUG_MENACE)
                    .and()
                    .hasLevel(DEFENCE, 30)
                    .and()
                    .hasLevel(PRAYER, 20)
                    .build()),
    PROSELYTE_TASSET(
            ArmourItemRef.PROSELYTE_TASSET,
            true,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(33, 31, 29, -4, 31),
            new SkillsBonus(0, 0, 0, 6),
            8.164,
            ArmourItemRef.PROSELYTE_TASSET.getSimilarItems(),
            new RequirementBuilder()
                    .finished(PaidQuest.THE_SLUG_MENACE)
                    .and()
                    .hasLevel(DEFENCE, 30)
                    .and()
                    .hasLevel(PRAYER, 20)
                    .build()),
    PURPLE_ELEGANT_LEGS(
            ArmourItemRef.PURPLE_ELEGANT_LEGS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            ArmourItemRef.PURPLE_ELEGANT_LEGS.getSimilarItems()),
    PURPLE_ELEGANT_SKIRT(
            ArmourItemRef.PURPLE_ELEGANT_SKIRT,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            ArmourItemRef.PURPLE_ELEGANT_SKIRT.getSimilarItems()),
    PURPLE_ROBE_BOTTOMS(
            ArmourItemRef.PURPLE_ROBE_BOTTOMS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 2, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.PURPLE_ROBE_BOTTOMS.getSimilarItems()),
    RADIANT_OATHPLATE_LEGS(
            ArmourItemRef.RADIANT_OATHPLATE_LEGS,
            true,
            new AttackBonus(0, 12, 0, -12, -14),
            new DefenceBonus(75, 100, 73, -3, 81),
            new SkillsBonus(2, 0, 0, 0),
            9.071,
            ArmourItemRef.RADIANT_OATHPLATE_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 78).build()),
    RANGERS_TIGHTS(
            ArmourItemRef.RANGERS_TIGHTS,
            true,
            new AttackBonus(0, 0, 0, -10, 15),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            ArmourItemRef.RANGERS_TIGHTS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 40).build()),
    RED_DHIDE_CHAPS(
            ArmourItemRef.RED_DHIDE_CHAPS,
            true,
            new AttackBonus(0, 0, 0, -10, 14),
            new DefenceBonus(15, 18, 22, 18, 20),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            ArmourItemRef.RED_DHIDE_CHAPS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 60).build()),
    RED_ELEGANT_LEGS(
            ArmourItemRef.RED_ELEGANT_LEGS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            ArmourItemRef.RED_ELEGANT_LEGS.getSimilarItems()),
    RED_ELEGANT_SKIRT(
            ArmourItemRef.RED_ELEGANT_SKIRT,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            ArmourItemRef.RED_ELEGANT_SKIRT.getSimilarItems()),
    RED_ROBE_BOTTOMS(
            ArmourItemRef.RED_ROBE_BOTTOMS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 2, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.RED_ROBE_BOTTOMS.getSimilarItems()),
    ROBE_BOTTOM_OF_DARKNESS(
            ArmourItemRef.ROBE_BOTTOM_OF_DARKNESS,
            true,
            new AttackBonus(0, 0, 0, 15, 0),
            new DefenceBonus(0, 0, 0, 15, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.814,
            ArmourItemRef.ROBE_BOTTOM_OF_DARKNESS.getSimilarItems(),
            new RequirementBuilder().hasLevel(MAGIC, 40).hasLevel(DEFENCE, 20).build()),
    ROCKSHELL_LEGS(
            ArmourItemRef.ROCKSHELL_LEGS,
            true,
            new AttackBonus(0, 0, 0, -21, -7),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.ROCKSHELL_LEGS.getSimilarItems(),
            new RequirementBuilder()
                    .finished(PaidQuest.THE_FREMENNIK_TRIALS)
                    .and()
                    .hasLevel(DEFENCE, 40)
                    .build()),
    ROGUE_TROUSERS(
            ArmourItemRef.ROGUE_TROUSERS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(7, 7, 7, 7, 7),
            new SkillsBonus(0, 0, 0, 0),
            0.453,
            ArmourItemRef.ROGUE_TROUSERS.getSimilarItems()),
    ROYAL_GOWN_BOTTOM(
            ArmourItemRef.ROYAL_GOWN_BOTTOM,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.36,
            ArmourItemRef.ROYAL_GOWN_BOTTOM.getSimilarItems()),
    RUNE_PLATELEGS(
            ArmourItemRef.RUNE_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.RUNE_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 40).build()),
    RUNE_PLATESKIRT(
            ArmourItemRef.RUNE_PLATESKIRT,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 0),
            8.164,
            ArmourItemRef.RUNE_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 40).build()),
    SAMURAI_GREAVES(
            ArmourItemRef.SAMURAI_GREAVES,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(42, 40, 38, 3, 40),
            new SkillsBonus(0, 0, 0, 0),
            1.5,
            ArmourItemRef.SAMURAI_GREAVES.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 35).build()),
    SANDWICH_LADY_BOTTOM(
            ArmourItemRef.SANDWICH_LADY_BOTTOM,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.SANDWICH_LADY_BOTTOM.getSimilarItems()),
    SANGUINE_TORVA_PLATELEGS(
            ArmourItemRef.SANGUINE_TORVA_PLATELEGS,
            true,
            new AttackBonus(0, 0, 0, -24, -11),
            new DefenceBonus(87, 78, 79, -9, 102),
            new SkillsBonus(4, 0, 0, 1),
            9.071,
            ArmourItemRef.SANGUINE_TORVA_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 80).build()),
    SARADOMIN_CHAPS(
            ArmourItemRef.SARADOMIN_CHAPS,
            true,
            new AttackBonus(0, 0, 0, -10, 17),
            new DefenceBonus(31, 25, 33, 28, 31),
            new SkillsBonus(0, 0, 0, 1),
            5.0,
            ArmourItemRef.SARADOMIN_CHAPS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 70).build()),
    SARADOMIN_PLATELEGS(
            ArmourItemRef.SARADOMIN_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 1),
            9.071,
            ArmourItemRef.SARADOMIN_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 40).build()),
    SARADOMIN_PLATESKIRT(
            ArmourItemRef.SARADOMIN_PLATESKIRT,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 1),
            9.071,
            ArmourItemRef.SARADOMIN_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 40).build()),
    SARADOMIN_ROBE_LEGS(
            ArmourItemRef.SARADOMIN_ROBE_LEGS,
            true,
            new AttackBonus(0, 0, 0, 4, 0),
            new DefenceBonus(0, 0, 0, 4, 0),
            new SkillsBonus(0, 0, 0, 5),
            2.7,
            ArmourItemRef.SARADOMIN_ROBE_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(PRAYER, 20).build()),
    SHADE_ROBE(
            ArmourItemRef.SHADE_ROBE,
            false,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 4),
            0.907,
            ArmourItemRef.SHADE_ROBE.getSimilarItems()),
    SHAYZIEN_GREAVES_1(
            ArmourItemRef.SHAYZIEN_GREAVES_1,
            true,
            new AttackBonus(0, 0, 0, -10, -2),
            new DefenceBonus(10, 9, 8, -2, 10),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.SHAYZIEN_GREAVES_1.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 20).build()),
    SHAYZIEN_GREAVES_2(
            ArmourItemRef.SHAYZIEN_GREAVES_2,
            true,
            new AttackBonus(0, 0, 0, -14, -3),
            new DefenceBonus(14, 13, 12, -3, 14),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.SHAYZIEN_GREAVES_2.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 20).build()),
    SHAYZIEN_GREAVES_3(
            ArmourItemRef.SHAYZIEN_GREAVES_3,
            true,
            new AttackBonus(0, 0, 0, -17, -4),
            new DefenceBonus(17, 16, 15, -3, 17),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.SHAYZIEN_GREAVES_3.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 20).build()),
    SHAYZIEN_GREAVES_4(
            ArmourItemRef.SHAYZIEN_GREAVES_4,
            true,
            new AttackBonus(0, 0, 0, -20, -5),
            new DefenceBonus(20, 19, 18, -4, 20),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.SHAYZIEN_GREAVES_4.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 20).build()),
    SHAYZIEN_GREAVES(
            ArmourItemRef.SHAYZIEN_GREAVES,
            true,
            new AttackBonus(0, 0, 0, -20, 6),
            new DefenceBonus(23, 22, 21, -4, 23),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.SHAYZIEN_GREAVES.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 20).build()),
    SILLY_JESTER_TIGHTS(
            ArmourItemRef.SILLY_JESTER_TIGHTS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 5, -5),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.SILLY_JESTER_TIGHTS.getSimilarItems()),
    SKELETAL_BOTTOMS(
            ArmourItemRef.SKELETAL_BOTTOMS,
            true,
            new AttackBonus(0, 0, 0, 6, -7),
            new DefenceBonus(22, 20, 24, 10, 0),
            new SkillsBonus(0, 0, 0, 0),
            4.082,
            ArmourItemRef.SKELETAL_BOTTOMS.getSimilarItems(),
            new RequirementBuilder()
                    .finished(PaidQuest.THE_FREMENNIK_TRIALS)
                    .and()
                    .hasLevel(DEFENCE, 40)
                    .and()
                    .hasLevel(MAGIC, 40)
                    .build()),
    SNAKESKIN_CHAPS(
            ArmourItemRef.SNAKESKIN_CHAPS,
            true,
            new AttackBonus(0, 0, 0, -5, 6),
            new DefenceBonus(8, 8, 10, 4, 10),
            new SkillsBonus(0, 0, 0, 0),
            3.628,
            ArmourItemRef.SNAKESKIN_CHAPS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 30).hasLevel(DEFENCE, 30).build()),
    SPINED_CHAPS(
            ArmourItemRef.SPINED_CHAPS,
            true,
            new AttackBonus(0, 0, 0, -10, 8),
            new DefenceBonus(22, 16, 24, 8, 22),
            new SkillsBonus(0, 0, 0, 0),
            5.443,
            ArmourItemRef.SPINED_CHAPS.getSimilarItems(),
            new RequirementBuilder()
                    .hasLevel(RANGED, 40)
                    .and()
                    .hasLevel(DEFENCE, 40)
                    .and()
                    .finished(PaidQuest.THE_FREMENNIK_TRIALS)
                    .build()),
    SPLITBARK_LEGS(
            ArmourItemRef.SPLITBARK_LEGS,
            true,
            new AttackBonus(0, 0, 0, 7, -7),
            new DefenceBonus(22, 20, 25, 10, 0),
            new SkillsBonus(0, 0, 0, 0),
            3.628,
            ArmourItemRef.SPLITBARK_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(MAGIC, 40).hasLevel(DEFENCE, 40).build()),
    STEEL_PLATELEGS(
            ArmourItemRef.STEEL_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(17, 16, 15, -4, 16),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.STEEL_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 5).build()),
    STEEL_PLATESKIRT(
            ArmourItemRef.STEEL_PLATESKIRT,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(17, 16, 15, -4, 16),
            new SkillsBonus(0, 0, 0, 0),
            8.164,
            ArmourItemRef.STEEL_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 5).build()),
    STUDDED_CHAPS(
            ArmourItemRef.STUDDED_CHAPS,
            false,
            new AttackBonus(0, 0, 0, -5, 6),
            new DefenceBonus(15, 16, 17, 6, 16),
            new SkillsBonus(0, 0, 0, 0),
            4.535,
            ArmourItemRef.STUDDED_CHAPS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 20).build()),
    SUNFIRE_FANATIC_CHAUSSES(
            ArmourItemRef.SUNFIRE_FANATIC_CHAUSSES,
            true,
            new AttackBonus(0, 0, 0, -4, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 8),
            7.711,
            ArmourItemRef.SUNFIRE_FANATIC_CHAUSSES.getSimilarItems(),
            new RequirementBuilder().hasLevel(PRAYER, 60).hasLevel(DEFENCE, 40).build()),
    SWAMP_BARK_LEGS(
            ArmourItemRef.SWAMP_BARK_LEGS,
            true,
            new AttackBonus(0, 0, 0, 10, 0),
            new DefenceBonus(20, 22, 24, 15, 0),
            new SkillsBonus(0, 0, 0, 0),
            3.628,
            ArmourItemRef.SWAMP_BARK_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(MAGIC, 50).hasLevel(DEFENCE, 50).build()),
    TEAL_ROBE_BOTTOMS(
            ArmourItemRef.TEAL_ROBE_BOTTOMS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 2, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.TEAL_ROBE_BOTTOMS.getSimilarItems()),
    TORAGS_PLATELEGS(
            ArmourItemRef.TORAGS_PLATELEGS,
            true,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(85, 82, 83, -4, 92),
            new SkillsBonus(0, 0, 0, 0),
            9.071,
            ArmourItemRef.TORAGS_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 70).build()),
    TORVA_PLATELEGS(
            ArmourItemRef.TORVA_PLATELEGS,
            true,
            new AttackBonus(0, 0, 0, -24, -11),
            new DefenceBonus(87, 78, 79, -9, 102),
            new SkillsBonus(4, 0, 0, 1),
            9.071,
            ArmourItemRef.TORVA_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 80).build()),
    TURQUOISE_ROBE_BOTTOMS(
            ArmourItemRef.TURQUOISE_ROBE_BOTTOMS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 2, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.TURQUOISE_ROBE_BOTTOMS.getSimilarItems()),
    TWISTED_ANCESTRAL_BOTTOM(
            ArmourItemRef.TWISTED_ANCESTRAL_BOTTOM,
            true,
            new AttackBonus(0, 0, 0, 26, -7),
            new DefenceBonus(27, 24, 30, 20, 0),
            new SkillsBonus(0, 0, 3, 0),
            1.814,
            ArmourItemRef.TWISTED_ANCESTRAL_BOTTOM.getSimilarItems(),
            new RequirementBuilder().hasLevel(MAGIC, 75).hasLevel(DEFENCE, 65).build()),
    ULTIMATE_IRONMAN_PLATELEGS(
            ArmourItemRef.ULTIMATE_IRONMAN_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(11, 10, 10, -4, 10),
            new SkillsBonus(0, 0, 0, 0),
            4.535,
            ArmourItemRef.ULTIMATE_IRONMAN_PLATELEGS.getSimilarItems()),
    VERACS_PLATESKIRT_UNDAMAGED(
            ArmourItemRef.VERACS_PLATESKIRT_UNDAMAGED,
            true,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(85, 82, 83, 0, 84),
            new SkillsBonus(0, 0, 0, 4),
            4.535,
            ArmourItemRef.VERACS_PLATESKIRT_UNDAMAGED.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 70).build()),
    VIRTUS_ROBE_BOTTOM(
            ArmourItemRef.VIRTUS_ROBE_BOTTOM,
            true,
            new AttackBonus(0, 0, 0, 26, -9),
            new DefenceBonus(31, 28, 34, 22, 0),
            new SkillsBonus(0, 0, 2, 1),
            3.79,
            ArmourItemRef.VIRTUS_ROBE_BOTTOM.getSimilarItems(),
            new RequirementBuilder().hasLevel(MAGIC, 78).hasLevel(DEFENCE, 75).build()),
    VOID_KNIGHT_ROBE(
            ArmourItemRef.VOID_KNIGHT_ROBE,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(30, 30, 30, 30, 30),
            new SkillsBonus(0, 0, 0, 0),
            8.164,
            ArmourItemRef.VOID_KNIGHT_ROBE.getSimilarItems(),
            new RequirementBuilder()
                    .hasLevel(ATTACK, 42)
                    .hasLevel(STRENGTH, 42)
                    .hasLevel(DEFENCE, 42)
                    .hasLevel(HITPOINTS, 42)
                    .hasLevel(RANGED, 42)
                    .hasLevel(MAGIC, 42)
                    .hasLevel(PRAYER, 22)
                    .build()),
    VYREWATCH_LEGS(
            ArmourItemRef.VYREWATCH_LEGS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 2, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.VYREWATCH_LEGS.getSimilarItems()),
    WHITE_ELEGANT_SKIRT(
            ArmourItemRef.WHITE_ELEGANT_SKIRT,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            1.0,
            ArmourItemRef.WHITE_ELEGANT_SKIRT.getSimilarItems()),
    WHITE_PLATELEGS(
            ArmourItemRef.WHITE_PLATELEGS,
            true,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(21, 20, 19, -4, 20),
            new SkillsBonus(0, 0, 0, 1),
            9.071,
            ArmourItemRef.WHITE_PLATELEGS.getSimilarItems(),
            new RequirementBuilder()
                    .finished(PaidQuest.WANTED)
                    .and()
                    .hasLevel(DEFENCE, 10)
                    .build()),
    WHITE_PLATESKIRT(
            ArmourItemRef.WHITE_PLATESKIRT,
            true,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(21, 20, 19, -4, 20),
            new SkillsBonus(0, 0, 0, 1),
            8.164,
            ArmourItemRef.WHITE_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder()
                    .finished(PaidQuest.WANTED)
                    .and()
                    .hasLevel(DEFENCE, 10)
                    .build()),
    XERICIAN_BOTTOMS(
            ArmourItemRef.XERICIAN_ROBE,
            true,
            new AttackBonus(0, 0, 0, 4, 0),
            new DefenceBonus(0, 0, 0, 7, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.18,
            ArmourItemRef.XERICIAN_ROBE.getSimilarItems(),
            new RequirementBuilder().hasLevel(MAGIC, 20).hasLevel(DEFENCE, 10).build()),
    YAK_HIDE_ARMOUR_LEGS(
            ArmourItemRef.YAK_HIDE_ARMOUR_LEGS,
            true,
            new AttackBonus(0, 0, 0, -5, 10),
            new DefenceBonus(25, 20, 15, -2, 10),
            new SkillsBonus(0, 0, 0, 0),
            2.721,
            ArmourItemRef.YAK_HIDE_ARMOUR_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 20).build()),
    YELLOW_ROBE_BOTTOMS(
            ArmourItemRef.YELLOW_ROBE_BOTTOMS,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 2, 2, 0, 0),
            new SkillsBonus(0, 0, 0, 0),
            0.907,
            ArmourItemRef.YELLOW_ROBE_BOTTOMS.getSimilarItems()),
    ZAMORAK_CHAPS(
            ArmourItemRef.ZAMORAK_CHAPS,
            true,
            new AttackBonus(0, 0, 0, -10, 17),
            new DefenceBonus(31, 25, 33, 28, 31),
            new SkillsBonus(0, 0, 0, 1),
            5.0,
            ArmourItemRef.ZAMORAK_CHAPS.getSimilarItems(),
            new RequirementBuilder().hasLevel(RANGED, 70).build()),
    ZAMORACK_MONK_BOTTOM(
            ArmourItemRef.ZAMORACK_MONK_BOTTOM,
            false,
            new AttackBonus(0, 0, 0, 2, 0),
            new DefenceBonus(0, 0, 0, 3, 0),
            new SkillsBonus(0, 0, 0, 3),
            0.907,
            ArmourItemRef.ZAMORACK_MONK_BOTTOM.getSimilarItems()),
    ZAMORAK_PLATELEGS(
            ArmourItemRef.ZAMORAK_PLATELEGS,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 1),
            9.071,
            ArmourItemRef.ZAMORAK_PLATELEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 40).build()),
    ZAMORAK_PLATESKIRT(
            ArmourItemRef.ZAMORAK_PLATESKIRT,
            false,
            new AttackBonus(0, 0, 0, -21, -11),
            new DefenceBonus(51, 49, 47, -4, 49),
            new SkillsBonus(0, 0, 0, 1),
            9.071,
            ArmourItemRef.ZAMORAK_PLATESKIRT.getSimilarItems(),
            new RequirementBuilder().hasLevel(DEFENCE, 40).build()),
    ZAMORAK_ROBE_LEGS(
            ArmourItemRef.ZAMORAK_ROBE_LEGS,
            true,
            new AttackBonus(0, 0, 0, 4, 0),
            new DefenceBonus(0, 0, 0, 4, 0),
            new SkillsBonus(0, 0, 0, 5),
            2.7,
            ArmourItemRef.ZAMORAK_ROBE_LEGS.getSimilarItems(),
            new RequirementBuilder().hasLevel(PRAYER, 20).build()),
    ZEALOT_BOTTOM(
            ArmourItemRef.ZEALOT_BOTTOM,
            true,
            new AttackBonus(0, 0, 0, 0, 0),
            new DefenceBonus(0, 0, 0, 0, 0),
            new SkillsBonus(0, 0, 0, 6),
            0.907,
            ArmourItemRef.ZEALOT_BOTTOM.getSimilarItems());

    private final EquipmentSlot slot = EquipmentSlot.LEGS;
    private final GenericItemRef itemRef;
    private final boolean members;
    private final AttackBonus attackBonus;
    private final DefenceBonus defenceBonus;
    private final SkillsBonus skillsBonus;
    private final double weight;
    private final GenericItemRef[] similarItems;
    private final Requirement requirement;

    LegsSlotRef(
            GenericItemRef itemRef,
            boolean members,
            AttackBonus attackBonus,
            DefenceBonus defenceBonus,
            SkillsBonus skillsBonus,
            double weight,
            GenericItemRef[] similarItems) {
        this(
                itemRef,
                members,
                attackBonus,
                defenceBonus,
                skillsBonus,
                weight,
                similarItems,
                new RequirementBuilder().alwaysTrue().build());
    }
}
